package aoc2023;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.IntStream;

public class Day7 {
    private static void a(Input input) {
        Comparator<HandAndBid> ranker = (h1, h2) -> {
            int cmp = h2.type.compareTo(h1.type);
            if (cmp != 0) {
                return cmp;
            }
            for (int i = 0; i < h1.cards.size(); i++) {
                Card c1 = h1.cards.get(i);
                Card c2 = h2.cards.get(i);
                cmp = Integer.compare(c1.value, c2.value);
                if (cmp != 0) {
                    return cmp;
                }
            }
            return cmp;
        };

        List<HandAndBid> ranked = input.hands.stream().sorted(ranker).toList();
        int sum = IntStream.range(0, ranked.size()).map(i -> (i + 1) * ranked.get(i).bid).sum();
        System.out.println(sum);
    }

    private static void b(Input input) {
        Comparator<HandAndBid> ranker = (h1, h2) -> {
            int cmp = h2.typeB.compareTo(h1.typeB);
            if (cmp != 0) {
                return cmp;
            }
            for (int i = 0; i < h1.cards.size(); i++) {
                Card c1 = h1.cards.get(i);
                Card c2 = h2.cards.get(i);
                int val1 = c1.c == 'J' ? 1 : c1.value;
                int val2 = c2.c == 'J' ? 1 : c2.value;
                cmp = Integer.compare(val1, val2);
                if (cmp != 0) {
                    return cmp;
                }
            }
            return cmp;
        };

        List<HandAndBid> ranked = input.hands.stream().sorted(ranker).toList();
        int sum = IntStream.range(0, ranked.size()).map(i -> (i + 1) * ranked.get(i).bid).sum();
        System.out.println(sum);
    }

    record Card(char c, int value) {}

    record HandAndBid(List<Card> cards, int bid, Type type, Type typeB) {}

    enum Type {FIVE, FOUR, FULL_HOUSE, THREE, TWO, ONE, HIGH}

    record Input(List<HandAndBid> hands) {
        static Input parse(String input) {
            List<HandAndBid> handAndBids = new ArrayList<>();
            for (String line : input.lines().toList()) {
                String[] parts = line.split(" ");
                List<Card> cards = new ArrayList<>();
                Map<Character, Integer> valToCount = new HashMap<>();
                for (char c : parts[0].toCharArray()) {
                    int val = switch (c) {
                        case 'A' -> 14;
                        case 'K' -> 13;
                        case 'Q' -> 12;
                        case 'J' -> 11;
                        case 'T' -> 10;
                        default -> c - '0';
                    };
                    valToCount.put(c, valToCount.containsKey(c) ? valToCount.get(c) + 1 : 1);
                    cards.add(new Card(c, val));
                }
                handAndBids.add(new HandAndBid(cards, Integer.parseInt(parts[1]), calcType(valToCount), calcTypeB(valToCount)));
            }
            return new Input(handAndBids);
        }

        static Type calcType(Map<Character, Integer> cards) {
            int maxCount = cards.values().stream().mapToInt(c -> c).max().orElse(0);
            int minCount = cards.values().stream().mapToInt(c -> c).min().orElse(0);
            if (maxCount == 5) {
                return Type.FIVE;
            } else if (maxCount == 4) {
                return Type.FOUR;
            } else if (maxCount == 3) {
                if (minCount == 2) {
                    return Type.FULL_HOUSE;
                } else {
                    return Type.THREE;
                }
            } else if (maxCount == 2) {
                if (cards.values().stream().mapToInt(c -> c).filter(c -> c == 2).count() == 2) {
                    return Type.TWO;
                } else {
                    return Type.ONE;
                }
            } else {
                return Type.HIGH;
            }
        }

        static Type calcTypeB(Map<Character, Integer> cards) {
            int js = cards.getOrDefault('J', 0);
            Map<Character, Integer> template = new HashMap<>(cards);
            template.remove('J');
            Type best = calcType(cards);
            for (Character c : template.keySet().toArray(Character[]::new)) {
                Map<Character, Integer> hand = new HashMap<>(template);
                hand.put(c, hand.get(c) + js);
                Type type = calcType(hand);
                if (type.ordinal() < best.ordinal()) {
                    best = type;
                }
            }
            return best;
        }
    }

    private static final String TEST_INPUT = "32T3K 765\n"
                                             + "T55J5 684\n"
                                             + "KK677 28\n"
                                             + "KTJJT 220\n"
                                             + "QQQJA 483";

    private static final String INPUT = "342QK 491\n"
                                        + "36QAT 619\n"
                                        + "85663 606\n"
                                        + "33K3A 23\n"
                                        + "K7775 814\n"
                                        + "T67T6 105\n"
                                        + "49T8T 200\n"
                                        + "2KAT2 317\n"
                                        + "96669 251\n"
                                        + "4A827 285\n"
                                        + "QTQ6Q 308\n"
                                        + "A2T58 930\n"
                                        + "838T8 692\n"
                                        + "AAAKK 535\n"
                                        + "3T338 612\n"
                                        + "QAAQQ 526\n"
                                        + "55655 329\n"
                                        + "AQQQ2 621\n"
                                        + "KQQ88 190\n"
                                        + "97QQ8 870\n"
                                        + "8J833 494\n"
                                        + "6AJT8 318\n"
                                        + "AA4QQ 125\n"
                                        + "62KK6 876\n"
                                        + "7A7QK 241\n"
                                        + "TT2T2 385\n"
                                        + "43234 632\n"
                                        + "57798 393\n"
                                        + "5A4J8 623\n"
                                        + "93QA8 935\n"
                                        + "46KT2 288\n"
                                        + "37J73 503\n"
                                        + "7A55Q 668\n"
                                        + "2J368 525\n"
                                        + "36223 226\n"
                                        + "A6T36 291\n"
                                        + "2AJ8T 740\n"
                                        + "QQQ52 411\n"
                                        + "893A6 778\n"
                                        + "TA438 197\n"
                                        + "T2242 25\n"
                                        + "23TJ9 769\n"
                                        + "43Q32 782\n"
                                        + "77J35 659\n"
                                        + "JJA87 756\n"
                                        + "6T666 237\n"
                                        + "JAKAA 238\n"
                                        + "86348 869\n"
                                        + "A9959 671\n"
                                        + "2TA36 51\n"
                                        + "35Q5T 65\n"
                                        + "A8T6T 212\n"
                                        + "T5T5T 962\n"
                                        + "27722 893\n"
                                        + "5T962 562\n"
                                        + "4J463 338\n"
                                        + "QQ4JA 134\n"
                                        + "J2TK7 925\n"
                                        + "Q89K2 389\n"
                                        + "43463 349\n"
                                        + "99998 764\n"
                                        + "76QT5 683\n"
                                        + "T6733 92\n"
                                        + "QKKQQ 599\n"
                                        + "2TQ9Q 206\n"
                                        + "99T6Q 816\n"
                                        + "5434T 14\n"
                                        + "527Q5 466\n"
                                        + "3T384 944\n"
                                        + "5A927 907\n"
                                        + "TQTTQ 93\n"
                                        + "38377 425\n"
                                        + "96A99 864\n"
                                        + "JJJ28 304\n"
                                        + "88688 841\n"
                                        + "245KT 365\n"
                                        + "6T668 364\n"
                                        + "7AAQQ 586\n"
                                        + "JAJAA 973\n"
                                        + "24442 669\n"
                                        + "23432 293\n"
                                        + "QJ8T5 649\n"
                                        + "8K492 86\n"
                                        + "96446 278\n"
                                        + "JTT99 217\n"
                                        + "99292 381\n"
                                        + "4T666 803\n"
                                        + "79A9J 20\n"
                                        + "8A7A8 332\n"
                                        + "9948T 940\n"
                                        + "683TA 810\n"
                                        + "5J666 106\n"
                                        + "6J6Q6 972\n"
                                        + "JJJJJ 928\n"
                                        + "KK664 781\n"
                                        + "JJQTQ 957\n"
                                        + "TT49K 775\n"
                                        + "32337 707\n"
                                        + "A6Q53 548\n"
                                        + "K6K6K 703\n"
                                        + "T89KQ 1\n"
                                        + "95399 372\n"
                                        + "K8484 267\n"
                                        + "T3633 561\n"
                                        + "93868 136\n"
                                        + "TT23T 771\n"
                                        + "87QT3 547\n"
                                        + "AAK4A 465\n"
                                        + "2JJJK 966\n"
                                        + "3J48J 277\n"
                                        + "56Q82 266\n"
                                        + "AA6TA 87\n"
                                        + "73QTK 596\n"
                                        + "T2T22 988\n"
                                        + "A9999 948\n"
                                        + "Q2K6J 851\n"
                                        + "9KKK9 639\n"
                                        + "2Q987 824\n"
                                        + "29733 981\n"
                                        + "55Q73 723\n"
                                        + "KK222 378\n"
                                        + "22322 186\n"
                                        + "A9634 904\n"
                                        + "K67JT 558\n"
                                        + "TK329 856\n"
                                        + "77T77 736\n"
                                        + "A7J66 339\n"
                                        + "994AJ 798\n"
                                        + "9JK46 460\n"
                                        + "25286 58\n"
                                        + "TKTKK 761\n"
                                        + "3TA75 680\n"
                                        + "2TT9K 980\n"
                                        + "37376 284\n"
                                        + "KK23T 920\n"
                                        + "A5AAA 730\n"
                                        + "A5J65 551\n"
                                        + "TATTT 282\n"
                                        + "KTT44 324\n"
                                        + "33434 882\n"
                                        + "8K89K 479\n"
                                        + "82563 832\n"
                                        + "TTQQQ 990\n"
                                        + "A623K 780\n"
                                        + "JQQT7 565\n"
                                        + "T358Q 513\n"
                                        + "9298A 970\n"
                                        + "QQ7Q5 382\n"
                                        + "82826 863\n"
                                        + "7K23Q 340\n"
                                        + "QQ4Q5 590\n"
                                        + "66A66 699\n"
                                        + "44QA4 83\n"
                                        + "4TTTT 776\n"
                                        + "T5995 929\n"
                                        + "8Q78Q 786\n"
                                        + "222J4 380\n"
                                        + "9TK25 582\n"
                                        + "J6KA3 270\n"
                                        + "8888J 793\n"
                                        + "JJJ2J 209\n"
                                        + "Q5J7K 353\n"
                                        + "645QQ 445\n"
                                        + "54TTT 804\n"
                                        + "77747 898\n"
                                        + "22J52 515\n"
                                        + "3QQQ3 118\n"
                                        + "2443K 536\n"
                                        + "AQ8K5 55\n"
                                        + "TQAKJ 111\n"
                                        + "A96A3 688\n"
                                        + "54Q4K 676\n"
                                        + "JK546 315\n"
                                        + "J9J99 689\n"
                                        + "944T2 442\n"
                                        + "J3663 949\n"
                                        + "J9999 49\n"
                                        + "K7JAA 833\n"
                                        + "4AK4K 956\n"
                                        + "3A3A3 115\n"
                                        + "KKKKT 234\n"
                                        + "76K23 712\n"
                                        + "K82T6 463\n"
                                        + "J3729 15\n"
                                        + "8988J 187\n"
                                        + "AAA55 327\n"
                                        + "22K65 757\n"
                                        + "5Q55Q 744\n"
                                        + "88878 989\n"
                                        + "TKTTT 601\n"
                                        + "58855 746\n"
                                        + "T33J3 166\n"
                                        + "J9922 334\n"
                                        + "5Q3QQ 594\n"
                                        + "2Q2QQ 84\n"
                                        + "KJTKK 252\n"
                                        + "QA3AA 598\n"
                                        + "8QT8Q 609\n"
                                        + "52TA4 32\n"
                                        + "T66QT 992\n"
                                        + "TJAJT 215\n"
                                        + "J3227 743\n"
                                        + "2684Q 996\n"
                                        + "JKQQ8 36\n"
                                        + "8J558 351\n"
                                        + "98A78 233\n"
                                        + "T7TTT 54\n"
                                        + "QQ55J 927\n"
                                        + "483JK 648\n"
                                        + "QA99K 228\n"
                                        + "2TJA6 110\n"
                                        + "373JQ 732\n"
                                        + "TT24J 820\n"
                                        + "A83T7 654\n"
                                        + "95J8J 563\n"
                                        + "62866 313\n"
                                        + "6633K 726\n"
                                        + "J5556 881\n"
                                        + "J4464 967\n"
                                        + "4TQQT 985\n"
                                        + "422QA 222\n"
                                        + "8T88J 386\n"
                                        + "44JJ4 179\n"
                                        + "J66TT 410\n"
                                        + "96699 296\n"
                                        + "AA2AK 788\n"
                                        + "QQ396 176\n"
                                        + "7786K 917\n"
                                        + "3666J 477\n"
                                        + "Q6996 527\n"
                                        + "99444 41\n"
                                        + "2KT3A 675\n"
                                        + "KQKKQ 936\n"
                                        + "KQ493 437\n"
                                        + "7862J 502\n"
                                        + "T74A8 947\n"
                                        + "6J97A 801\n"
                                        + "66363 903\n"
                                        + "668Q8 352\n"
                                        + "T529T 330\n"
                                        + "26A6A 416\n"
                                        + "7J837 390\n"
                                        + "756A4 710\n"
                                        + "43Q68 33\n"
                                        + "66242 56\n"
                                        + "88Q88 868\n"
                                        + "7AAA7 273\n"
                                        + "AQ2AA 628\n"
                                        + "5Q522 938\n"
                                        + "23K36 216\n"
                                        + "38839 685\n"
                                        + "49J45 286\n"
                                        + "4774K 303\n"
                                        + "25Q55 915\n"
                                        + "849J7 57\n"
                                        + "42545 859\n"
                                        + "KA9AA 472\n"
                                        + "K4822 489\n"
                                        + "444K4 542\n"
                                        + "88Q55 538\n"
                                        + "99599 13\n"
                                        + "AAAK6 274\n"
                                        + "39636 354\n"
                                        + "933J3 568\n"
                                        + "78Q79 566\n"
                                        + "46664 402\n"
                                        + "TKTQ7 617\n"
                                        + "8676T 454\n"
                                        + "3KJ2K 650\n"
                                        + "8A585 999\n"
                                        + "2QQQQ 9\n"
                                        + "TT555 377\n"
                                        + "K2699 807\n"
                                        + "A5289 577\n"
                                        + "K7273 48\n"
                                        + "3QQQQ 818\n"
                                        + "KAKKK 152\n"
                                        + "93553 213\n"
                                        + "8QK2K 507\n"
                                        + "66J6J 202\n"
                                        + "TK5QT 931\n"
                                        + "84T57 844\n"
                                        + "QQ8JQ 960\n"
                                        + "28248 760\n"
                                        + "Q6987 890\n"
                                        + "JTAT5 496\n"
                                        + "99933 122\n"
                                        + "33KKT 729\n"
                                        + "A8349 815\n"
                                        + "K2369 645\n"
                                        + "93333 687\n"
                                        + "KKKK7 879\n"
                                        + "7727T 74\n"
                                        + "Q6K52 253\n"
                                        + "933Q7 462\n"
                                        + "748K9 597\n"
                                        + "AT5J9 384\n"
                                        + "83838 552\n"
                                        + "3TQ5K 774\n"
                                        + "899J3 260\n"
                                        + "777A7 301\n"
                                        + "95K26 713\n"
                                        + "JK3T5 711\n"
                                        + "45456 311\n"
                                        + "AKKA4 46\n"
                                        + "KK248 280\n"
                                        + "KJ755 878\n"
                                        + "69T8Q 653\n"
                                        + "Q966J 371\n"
                                        + "4K839 17\n"
                                        + "7T77K 556\n"
                                        + "7AQ44 362\n"
                                        + "6K626 986\n"
                                        + "7KQQQ 261\n"
                                        + "555T8 272\n"
                                        + "89984 229\n"
                                        + "4JA6K 320\n"
                                        + "J4494 627\n"
                                        + "J3444 310\n"
                                        + "62Q37 846\n"
                                        + "8K588 942\n"
                                        + "JQJQJ 147\n"
                                        + "5J876 952\n"
                                        + "KKJ89 717\n"
                                        + "KKKQ9 618\n"
                                        + "3TQ4J 663\n"
                                        + "7J5Q9 448\n"
                                        + "A7A73 862\n"
                                        + "793T2 979\n"
                                        + "377J6 73\n"
                                        + "3TAJJ 146\n"
                                        + "KTJ4Q 755\n"
                                        + "3K3K7 208\n"
                                        + "22J38 569\n"
                                        + "222QT 811\n"
                                        + "Q33JT 195\n"
                                        + "K666T 625\n"
                                        + "8QA47 295\n"
                                        + "J9J79 860\n"
                                        + "62AK2 221\n"
                                        + "7J755 417\n"
                                        + "37232 414\n"
                                        + "AATAA 470\n"
                                        + "TQQQQ 469\n"
                                        + "9344J 749\n"
                                        + "4333A 492\n"
                                        + "65576 767\n"
                                        + "K7677 160\n"
                                        + "Q5QQQ 434\n"
                                        + "KQ764 837\n"
                                        + "AQQQQ 580\n"
                                        + "AAA66 359\n"
                                        + "58923 735\n"
                                        + "J2J88 169\n"
                                        + "56T5K 60\n"
                                        + "J8T8T 595\n"
                                        + "3A8J9 982\n"
                                        + "A44AJ 900\n"
                                        + "KK77K 418\n"
                                        + "QT525 792\n"
                                        + "22282 250\n"
                                        + "Q84Q4 412\n"
                                        + "J5754 836\n"
                                        + "9JT3T 640\n"
                                        + "44A44 290\n"
                                        + "7AJAA 969\n"
                                        + "85AK2 85\n"
                                        + "25257 873\n"
                                        + "95959 604\n"
                                        + "KAJ8K 919\n"
                                        + "4AJA2 759\n"
                                        + "44A47 830\n"
                                        + "QQKQA 127\n"
                                        + "8Q8TJ 116\n"
                                        + "87783 543\n"
                                        + "JJ77J 300\n"
                                        + "K3Q5A 766\n"
                                        + "3TT3T 440\n"
                                        + "779Q4 916\n"
                                        + "42555 819\n"
                                        + "6JQ45 541\n"
                                        + "T2225 157\n"
                                        + "99JJ2 443\n"
                                        + "235A4 642\n"
                                        + "95455 559\n"
                                        + "8J865 660\n"
                                        + "K7K7J 512\n"
                                        + "6AA6Q 791\n"
                                        + "97977 341\n"
                                        + "9QQ99 456\n"
                                        + "6666Q 336\n"
                                        + "34Q3Q 433\n"
                                        + "A75T2 724\n"
                                        + "AJQ98 405\n"
                                        + "65A2J 509\n"
                                        + "A833J 420\n"
                                        + "29396 299\n"
                                        + "9954Q 438\n"
                                        + "J77J7 827\n"
                                        + "3333J 498\n"
                                        + "7KK9K 170\n"
                                        + "828TT 976\n"
                                        + "QT22T 120\n"
                                        + "KTK55 256\n"
                                        + "JAQ4T 858\n"
                                        + "888J3 264\n"
                                        + "7K58K 768\n"
                                        + "A9668 401\n"
                                        + "555A9 497\n"
                                        + "AA2AA 709\n"
                                        + "TT9TK 444\n"
                                        + "38T2J 370\n"
                                        + "AAAA8 138\n"
                                        + "9K4AT 693\n"
                                        + "9TAK8 275\n"
                                        + "Q684K 53\n"
                                        + "AATAT 933\n"
                                        + "2T32T 974\n"
                                        + "45444 581\n"
                                        + "88882 37\n"
                                        + "J9QQ7 388\n"
                                        + "43T33 537\n"
                                        + "AK729 823\n"
                                        + "AJ88A 828\n"
                                        + "225JT 510\n"
                                        + "4AJJA 21\n"
                                        + "72266 529\n"
                                        + "A8AAT 464\n"
                                        + "92222 843\n"
                                        + "A3J8Q 678\n"
                                        + "KTT83 100\n"
                                        + "86386 716\n"
                                        + "J4K59 690\n"
                                        + "J62K5 214\n"
                                        + "3KJAQ 842\n"
                                        + "K53A7 2\n"
                                        + "AJAAA 797\n"
                                        + "JAAKK 787\n"
                                        + "2QJ82 658\n"
                                        + "TT9T9 914\n"
                                        + "J4J4J 428\n"
                                        + "6465T 694\n"
                                        + "AK4A4 739\n"
                                        + "62484 398\n"
                                        + "AAKKK 636\n"
                                        + "6J576 167\n"
                                        + "AJA33 822\n"
                                        + "37K39 585\n"
                                        + "55959 149\n"
                                        + "9KA45 44\n"
                                        + "7JJ85 840\n"
                                        + "78882 344\n"
                                        + "J262Q 124\n"
                                        + "3496T 891\n"
                                        + "K4457 165\n"
                                        + "Q563T 977\n"
                                        + "J7882 159\n"
                                        + "A8899 519\n"
                                        + "3QJ28 734\n"
                                        + "6466J 587\n"
                                        + "TTJJT 355\n"
                                        + "87J7A 908\n"
                                        + "222QJ 103\n"
                                        + "7T762 883\n"
                                        + "4J444 995\n"
                                        + "TT3QT 248\n"
                                        + "TTQTT 451\n"
                                        + "8T53A 257\n"
                                        + "86649 331\n"
                                        + "KKA4K 185\n"
                                        + "85988 968\n"
                                        + "54555 958\n"
                                        + "T8T8T 705\n"
                                        + "T8JT9 909\n"
                                        + "4KK44 236\n"
                                        + "74735 239\n"
                                        + "88694 923\n"
                                        + "9J929 375\n"
                                        + "223T2 825\n"
                                        + "T7445 708\n"
                                        + "TJ63K 727\n"
                                        + "339Q9 452\n"
                                        + "28JJ4 408\n"
                                        + "7A33J 993\n"
                                        + "9T52Q 622\n"
                                        + "5K7A4 684\n"
                                        + "TJK44 289\n"
                                        + "2863A 544\n"
                                        + "65626 795\n"
                                        + "2A8J5 424\n"
                                        + "AAQQA 471\n"
                                        + "3K55K 750\n"
                                        + "77755 316\n"
                                        + "6AJ66 589\n"
                                        + "486T5 360\n"
                                        + "Q838T 395\n"
                                        + "32363 62\n"
                                        + "KAQAK 667\n"
                                        + "233K2 506\n"
                                        + "KK779 175\n"
                                        + "53A65 328\n"
                                        + "JK99K 892\n"
                                        + "TJTA2 276\n"
                                        + "9T9K9 204\n"
                                        + "63239 584\n"
                                        + "44222 714\n"
                                        + "K3K83 126\n"
                                        + "6J527 96\n"
                                        + "32333 861\n"
                                        + "KA247 913\n"
                                        + "J75QQ 436\n"
                                        + "82QJ9 885\n"
                                        + "89387 839\n"
                                        + "QAT39 109\n"
                                        + "2KTT7 545\n"
                                        + "33337 391\n"
                                        + "22227 560\n"
                                        + "6QQ44 848\n"
                                        + "29939 532\n"
                                        + "K6JKK 984\n"
                                        + "54484 108\n"
                                        + "4Q444 369\n"
                                        + "K88Q8 523\n"
                                        + "K55A5 624\n"
                                        + "85888 459\n"
                                        + "8Q8Q8 196\n"
                                        + "643T4 348\n"
                                        + "88J28 258\n"
                                        + "69999 88\n"
                                        + "8TT3T 486\n"
                                        + "2T56K 255\n"
                                        + "JT4T4 403\n"
                                        + "J8484 162\n"
                                        + "K88TA 82\n"
                                        + "JAJ9A 90\n"
                                        + "4K569 194\n"
                                        + "53535 481\n"
                                        + "TKJTK 367\n"
                                        + "48888 404\n"
                                        + "4T8TJ 34\n"
                                        + "QKA3T 476\n"
                                        + "252T5 620\n"
                                        + "7T77T 600\n"
                                        + "TJAAT 427\n"
                                        + "K3A97 143\n"
                                        + "46645 578\n"
                                        + "79497 570\n"
                                        + "TK9JK 68\n"
                                        + "J3J33 153\n"
                                        + "222A2 572\n"
                                        + "Q9999 243\n"
                                        + "3553J 983\n"
                                        + "4J277 630\n"
                                        + "TK4Q8 508\n"
                                        + "T44AQ 399\n"
                                        + "A3AA3 140\n"
                                        + "9QJ85 611\n"
                                        + "J8734 230\n"
                                        + "A5AA9 435\n"
                                        + "4J5AA 192\n"
                                        + "2Q222 540\n"
                                        + "65922 751\n"
                                        + "A9A7A 664\n"
                                        + "56598 906\n"
                                        + "99929 896\n"
                                        + "6Q67T 268\n"
                                        + "25J5J 198\n"
                                        + "J47AJ 45\n"
                                        + "262A6 63\n"
                                        + "4TKTK 571\n"
                                        + "622JT 480\n"
                                        + "K8KQK 574\n"
                                        + "47477 24\n"
                                        + "K2222 696\n"
                                        + "A9J28 342\n"
                                        + "Q4Q4Q 783\n"
                                        + "722T2 704\n"
                                        + "529A5 888\n"
                                        + "7TKT5 151\n"
                                        + "AA9AA 953\n"
                                        + "8KT8J 608\n"
                                        + "QQQJT 81\n"
                                        + "Q6K82 231\n"
                                        + "4TAAA 796\n"
                                        + "QK5J9 133\n"
                                        + "A83K2 634\n"
                                        + "6J666 662\n"
                                        + "75TJ8 77\n"
                                        + "T3444 148\n"
                                        + "QQ222 383\n"
                                        + "K4K77 91\n"
                                        + "T8TTT 178\n"
                                        + "A3K65 902\n"
                                        + "62225 413\n"
                                        + "TA5TT 19\n"
                                        + "996A6 826\n"
                                        + "6QQKK 946\n"
                                        + "888K8 183\n"
                                        + "56289 738\n"
                                        + "K8J28 887\n"
                                        + "55JKK 779\n"
                                        + "99K29 520\n"
                                        + "7623J 326\n"
                                        + "26222 918\n"
                                        + "39K86 853\n"
                                        + "T2Q63 975\n"
                                        + "27T2J 189\n"
                                        + "TTTJT 76\n"
                                        + "66994 686\n"
                                        + "78KKK 994\n"
                                        + "88333 482\n"
                                        + "A33A7 43\n"
                                        + "626TT 64\n"
                                        + "555J5 576\n"
                                        + "22T22 104\n"
                                        + "T44A4 439\n"
                                        + "2J666 79\n"
                                        + "A85Q6 978\n"
                                        + "3TTTT 59\n"
                                        + "78K47 865\n"
                                        + "4T6T4 602\n"
                                        + "27K55 546\n"
                                        + "T9K9T 831\n"
                                        + "66299 702\n"
                                        + "37444 706\n"
                                        + "J6825 309\n"
                                        + "T444T 426\n"
                                        + "J6QQQ 27\n"
                                        + "A2A8A 337\n"
                                        + "A97A7 499\n"
                                        + "29752 666\n"
                                        + "QTQKQ 191\n"
                                        + "KKK43 429\n"
                                        + "KKQKJ 583\n"
                                        + "AAA22 467\n"
                                        + "Q8898 813\n"
                                        + "J55JK 610\n"
                                        + "666KJ 18\n"
                                        + "Q3T6J 269\n"
                                        + "5T553 747\n"
                                        + "8T857 912\n"
                                        + "T6TA5 809\n"
                                        + "2J2J2 592\n"
                                        + "Q7QQQ 135\n"
                                        + "57K64 356\n"
                                        + "7374Q 113\n"
                                        + "48484 8\n"
                                        + "52992 790\n"
                                        + "AJ34Q 419\n"
                                        + "7777K 263\n"
                                        + "766J6 271\n"
                                        + "62967 745\n"
                                        + "ATA9A 899\n"
                                        + "K6K4K 895\n"
                                        + "3323J 52\n"
                                        + "AT423 965\n"
                                        + "JJJ8J 644\n"
                                        + "64444 500\n"
                                        + "A65KQ 188\n"
                                        + "75766 637\n"
                                        + "T2QT7 29\n"
                                        + "54527 661\n"
                                        + "5JJ5A 101\n"
                                        + "K3KJ3 453\n"
                                        + "33A33 991\n"
                                        + "52J52 910\n"
                                        + "2J48K 665\n"
                                        + "J8K26 163\n"
                                        + "J3JJ3 834\n"
                                        + "55K55 884\n"
                                        + "K63K2 376\n"
                                        + "3K2KK 721\n"
                                        + "892JK 205\n"
                                        + "57472 550\n"
                                        + "75JT3 11\n"
                                        + "Q5555 731\n"
                                        + "93738 112\n"
                                        + "AA466 312\n"
                                        + "66744 808\n"
                                        + "389KQ 924\n"
                                        + "K2JAJ 357\n"
                                        + "22233 71\n"
                                        + "JKKKJ 591\n"
                                        + "2Q294 762\n"
                                        + "QK58T 40\n"
                                        + "686J8 210\n"
                                        + "94499 493\n"
                                        + "QQ9QQ 421\n"
                                        + "K45KK 373\n"
                                        + "QKTA8 400\n"
                                        + "JJT56 521\n"
                                        + "QK9KT 812\n"
                                        + "67575 397\n"
                                        + "2KTQT 635\n"
                                        + "T4K3Q 1000\n"
                                        + "A88QQ 423\n"
                                        + "88J8J 573\n"
                                        + "56656 867\n"
                                        + "49454 518\n"
                                        + "T66T4 30\n"
                                        + "KJK7T 172\n"
                                        + "22422 961\n"
                                        + "34T34 530\n"
                                        + "T6TTT 5\n"
                                        + "K3KJK 857\n"
                                        + "6J583 817\n"
                                        + "K73JA 72\n"
                                        + "6K646 607\n"
                                        + "JK222 199\n"
                                        + "AAQA6 672\n"
                                        + "A7J68 488\n"
                                        + "9K5TQ 579\n"
                                        + "9K999 80\n"
                                        + "9JQQ9 715\n"
                                        + "39J34 533\n"
                                        + "6K978 633\n"
                                        + "2668A 150\n"
                                        + "2J322 657\n"
                                        + "KA2KA 934\n"
                                        + "28K82 850\n"
                                        + "TQK97 490\n"
                                        + "KKQJ9 361\n"
                                        + "4J453 937\n"
                                        + "2888T 314\n"
                                        + "6K666 193\n"
                                        + "T94A3 254\n"
                                        + "39KJJ 613\n"
                                        + "6336Q 350\n"
                                        + "45455 292\n"
                                        + "K7A89 741\n"
                                        + "45K4T 656\n"
                                        + "4Q63A 805\n"
                                        + "3T353 674\n"
                                        + "88778 305\n"
                                        + "277J2 889\n"
                                        + "33565 638\n"
                                        + "63333 799\n"
                                        + "54884 69\n"
                                        + "J9AAA 752\n"
                                        + "65AKT 28\n"
                                        + "357QT 128\n"
                                        + "74JA5 242\n"
                                        + "977J9 950\n"
                                        + "67676 838\n"
                                        + "369K4 246\n"
                                        + "9947A 306\n"
                                        + "Q6TJ9 97\n"
                                        + "53624 821\n"
                                        + "687K5 765\n"
                                        + "TA397 524\n"
                                        + "A6A66 218\n"
                                        + "AJ577 333\n"
                                        + "8J6KK 181\n"
                                        + "T77TA 647\n"
                                        + "3A8KQ 871\n"
                                        + "TQK42 955\n"
                                        + "QAAJA 220\n"
                                        + "48444 16\n"
                                        + "JTT7T 458\n"
                                        + "55A5J 845\n"
                                        + "33T33 232\n"
                                        + "83T8T 737\n"
                                        + "T4928 39\n"
                                        + "9AQ27 905\n"
                                        + "336JA 281\n"
                                        + "3Q4QQ 549\n"
                                        + "44699 432\n"
                                        + "72Q8Q 10\n"
                                        + "A7392 753\n"
                                        + "544K5 131\n"
                                        + "85458 806\n"
                                        + "33QAA 897\n"
                                        + "A55A5 279\n"
                                        + "2226J 485\n"
                                        + "T7388 207\n"
                                        + "5843T 849\n"
                                        + "4Q279 971\n"
                                        + "7J3Q7 652\n"
                                        + "T77QQ 643\n"
                                        + "86868 911\n"
                                        + "J3K77 718\n"
                                        + "2JQ94 954\n"
                                        + "A4449 963\n"
                                        + "T3KKK 742\n"
                                        + "8QATA 877\n"
                                        + "88336 6\n"
                                        + "7KJ8K 651\n"
                                        + "958QA 94\n"
                                        + "QJKQ4 987\n"
                                        + "96573 631\n"
                                        + "Q7586 719\n"
                                        + "Q66KA 130\n"
                                        + "A3TT2 247\n"
                                        + "AA385 894\n"
                                        + "QKQ2Q 629\n"
                                        + "QK44A 872\n"
                                        + "Q2T24 302\n"
                                        + "62QT8 616\n"
                                        + "7T5AT 225\n"
                                        + "44443 396\n"
                                        + "95299 156\n"
                                        + "43434 7\n"
                                        + "27T98 901\n"
                                        + "99J74 441\n"
                                        + "QA8K7 926\n"
                                        + "96967 35\n"
                                        + "3AAAA 789\n"
                                        + "68J26 484\n"
                                        + "83632 387\n"
                                        + "67666 158\n"
                                        + "T8TT4 615\n"
                                        + "495Q5 415\n"
                                        + "T9QA7 38\n"
                                        + "7JQT5 835\n"
                                        + "93996 449\n"
                                        + "97J99 998\n"
                                        + "2A2Q2 345\n"
                                        + "9ATTJ 655\n"
                                        + "37KQ7 495\n"
                                        + "A52J3 886\n"
                                        + "999AT 777\n"
                                        + "7K48K 932\n"
                                        + "T5T52 31\n"
                                        + "33392 99\n"
                                        + "43333 997\n"
                                        + "T6TT9 528\n"
                                        + "KAKK7 593\n"
                                        + "49837 473\n"
                                        + "4A73K 679\n"
                                        + "5628A 758\n"
                                        + "82537 245\n"
                                        + "99K9K 511\n"
                                        + "KKKK5 114\n"
                                        + "222A6 325\n"
                                        + "JJ553 379\n"
                                        + "2K777 89\n"
                                        + "777J7 641\n"
                                        + "T9TTT 262\n"
                                        + "K7K3K 681\n"
                                        + "222J2 129\n"
                                        + "J9JJ9 447\n"
                                        + "AQAAA 132\n"
                                        + "TJ77J 137\n"
                                        + "7844T 847\n"
                                        + "97QQQ 691\n"
                                        + "25J79 161\n"
                                        + "5Q22Q 154\n"
                                        + "Q4Q73 941\n"
                                        + "39773 468\n"
                                        + "9T92T 144\n"
                                        + "99297 75\n"
                                        + "4288K 392\n"
                                        + "TA3K5 107\n"
                                        + "8T8T8 223\n"
                                        + "7JTJ4 141\n"
                                        + "3K272 235\n"
                                        + "QQ5K7 773\n"
                                        + "TJA83 78\n"
                                        + "6Q7A2 142\n"
                                        + "696J9 227\n"
                                        + "QKKA6 298\n"
                                        + "222J8 701\n"
                                        + "JA93A 117\n"
                                        + "383AA 455\n"
                                        + "K3972 287\n"
                                        + "3433J 446\n"
                                        + "TTT2T 854\n"
                                        + "K9J99 184\n"
                                        + "8848K 224\n"
                                        + "KQ995 322\n"
                                        + "592Q2 307\n"
                                        + "9J676 95\n"
                                        + "7Q9J4 555\n"
                                        + "AA8Q7 102\n"
                                        + "9QQQ2 670\n"
                                        + "A6A2A 431\n"
                                        + "T844K 319\n"
                                        + "34534 802\n"
                                        + "9AQT5 409\n"
                                        + "7TJ62 875\n"
                                        + "TKQTK 406\n"
                                        + "74J77 219\n"
                                        + "KK55K 733\n"
                                        + "J8529 852\n"
                                        + "444Q2 478\n"
                                        + "98282 829\n"
                                        + "A9369 483\n"
                                        + "JJQQQ 430\n"
                                        + "5T2AJ 794\n"
                                        + "K2495 698\n"
                                        + "8A27J 50\n"
                                        + "33JJK 119\n"
                                        + "2K5K5 422\n"
                                        + "AJ957 47\n"
                                        + "76776 501\n"
                                        + "T593J 557\n"
                                        + "99974 951\n"
                                        + "KK2K2 203\n"
                                        + "6J777 259\n"
                                        + "QKJ33 368\n"
                                        + "88J99 407\n"
                                        + "94969 614\n"
                                        + "Q9J53 754\n"
                                        + "587K2 855\n"
                                        + "93Q28 504\n"
                                        + "7788J 682\n"
                                        + "7J7JQ 66\n"
                                        + "KKTTT 474\n"
                                        + "36343 70\n"
                                        + "4K3AJ 785\n"
                                        + "KKK6A 605\n"
                                        + "T9Q88 164\n"
                                        + "4Q445 139\n"
                                        + "7676K 67\n"
                                        + "89888 3\n"
                                        + "AATAJ 182\n"
                                        + "99977 374\n"
                                        + "644QJ 240\n"
                                        + "77577 770\n"
                                        + "QQ47Q 168\n"
                                        + "KAQKK 588\n"
                                        + "KKKK9 123\n"
                                        + "7K665 646\n"
                                        + "955J8 394\n"
                                        + "8A566 244\n"
                                        + "88JJJ 323\n"
                                        + "9K4T6 531\n"
                                        + "2922A 283\n"
                                        + "TAA22 673\n"
                                        + "J935K 505\n"
                                        + "Q52TK 358\n"
                                        + "J334K 475\n"
                                        + "2JK44 180\n"
                                        + "T64KA 335\n"
                                        + "4T6T9 553\n"
                                        + "226Q2 564\n"
                                        + "T674K 945\n"
                                        + "4A34T 457\n"
                                        + "QJQQQ 61\n"
                                        + "66686 575\n"
                                        + "AA9J6 554\n"
                                        + "KKKK4 171\n"
                                        + "QTQKK 700\n"
                                        + "99Q95 4\n"
                                        + "5TQ5Q 921\n"
                                        + "645TK 177\n"
                                        + "95Q5Q 155\n"
                                        + "J347T 728\n"
                                        + "2927K 748\n"
                                        + "3A6J6 461\n"
                                        + "9TAK7 567\n"
                                        + "48T69 343\n"
                                        + "QQQ77 321\n"
                                        + "T42TT 522\n"
                                        + "5Q656 514\n"
                                        + "KK8KK 363\n"
                                        + "K3293 784\n"
                                        + "2QKK6 249\n"
                                        + "4AA4A 534\n"
                                        + "23233 173\n"
                                        + "Q3933 12\n"
                                        + "33A87 880\n"
                                        + "KK3A7 725\n"
                                        + "6J326 347\n"
                                        + "3K3KK 98\n"
                                        + "AQAA5 346\n"
                                        + "26262 959\n"
                                        + "J493J 294\n"
                                        + "J32J6 763\n"
                                        + "63J4K 866\n"
                                        + "3T366 201\n"
                                        + "Q43KQ 297\n"
                                        + "66KK6 939\n"
                                        + "J6KJT 677\n"
                                        + "JAJ6T 517\n"
                                        + "QJ899 487\n"
                                        + "QKKQ5 450\n"
                                        + "5T2JT 121\n"
                                        + "3T982 695\n"
                                        + "999JT 772\n"
                                        + "55444 265\n"
                                        + "J9A99 800\n"
                                        + "337JJ 211\n"
                                        + "4A683 722\n"
                                        + "2KKQJ 697\n"
                                        + "22225 922\n"
                                        + "K8KK8 964\n"
                                        + "53Q93 366\n"
                                        + "47AJ6 174\n"
                                        + "A28Q8 603\n"
                                        + "99222 874\n"
                                        + "23QK2 539\n"
                                        + "A256K 26\n"
                                        + "66688 943\n"
                                        + "36676 626\n"
                                        + "JK952 145\n"
                                        + "94A42 516\n"
                                        + "KJKKK 720\n"
                                        + "K55K6 42\n"
                                        + "Q44Q4 22";

    public static void main(String[] args) {
        Util.time(() -> a(Input.parse(TEST_INPUT)));
        Util.time(() -> a(Input.parse(INPUT)));
        Util.time(() -> b(Input.parse(TEST_INPUT)));
        Util.time(() -> b(Input.parse(INPUT)));
    }
}
