package aoc2018;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class Day2 {

    public static void main(String[] args) {
        a();
        b();
    }

    private static void b() {
        String[] ids = Util.parseStrings(INPUT);
        Set<String> seen = new HashSet<>();
        for (int ignoredIx = 0; ignoredIx < ids[0].length(); ignoredIx++) {
            seen.clear();
            for (String id : ids) {
                String s = id.substring(0, ignoredIx);
                s += id.substring(ignoredIx + 1);
                if (!seen.add(s)) {
                    System.out.println(s);
                    break;
                }
            }
        }
    }

    private static void a() {
        int numberOf2s = 0;
        int numberOf3s = 0;
        String[] ids = Util.parseStrings(INPUT);
        int[] freqs = new int[30];
        for (String id : ids) {
            Arrays.fill(freqs, 0);
            for (int i = 0; i < id.length(); i++) {
                char c = id.charAt(i);
                freqs[c - 'a']++;
            }
            boolean has2 = false;
            boolean has3 = false;
            for (int freq : freqs) {
                has2 |= freq == 2;
                has3 |= freq == 3;
            }
            numberOf2s += has2 ? 1 : 0;
            numberOf3s += has3 ? 1 : 0;
        }

        int sum = numberOf2s * numberOf3s;
        System.out.println(numberOf2s + "*" + numberOf3s + "=" + sum);
    }

    private static final String INPUT = "crruafyzloguvxwctqmphenbkd\n"
                                        + "srcjafyzlcguvrwctqmphenbkd\n"
                                        + "srijafyzlogbpxwctgmphenbkd\n"
                                        + "zrijafyzloguvxrctqmphendkd\n"
                                        + "srijabyzloguvowcqqmphenbkd\n"
                                        + "srijafyzsoguvxwctbmpienbkd\n"
                                        + "srirtfyzlognvxwctqmphenbkd\n"
                                        + "srijafyzloguvxwctgmphenbmq\n"
                                        + "senjafyzloguvxectqmphenbkd\n"
                                        + "srijafyeloguvxwwtqmphembkd\n"
                                        + "srijafyzlogurxtctqmpkenbkd\n"
                                        + "srijafyzlkguvxictqhphenbkd\n"
                                        + "srijafgzlogunxwctqophenbkd\n"
                                        + "shijabyzloguvxwctqmqhenbkd\n"
                                        + "srjoafyzloguvxwctqmphenbwd\n"
                                        + "srijafyhloguvxwmtqmphenkkd\n"
                                        + "srijadyzlogwvxwctqmphenbed\n"
                                        + "brijafyzloguvmwctqmphenhkd\n"
                                        + "smijafyzlhguvxwctqmphjnbkd\n"
                                        + "sriqafvzloguvxwctqmpheebkd\n"
                                        + "srijafyzloguvxwisqmpuenbkd\n"
                                        + "mrijakyuloguvxwctqmphenbkd\n"
                                        + "srnfafyzloguvxwctqmphgnbkd\n"
                                        + "srijadyzloguvxwhfqmphenbkd\n"
                                        + "srijafhzloguvxwctdmlhenbkd\n"
                                        + "srijafyzloguvxwcsqmphykbkd\n"
                                        + "srijafyzlogwvxwatqmphhnbkd\n"
                                        + "srijafyzlozqvxwctqmphenbku\n"
                                        + "srijafyzloguvxwcbamphenbgd\n"
                                        + "srijafyzlfguvxwctqmphzybkd\n"
                                        + "srijafyzloguqxwetqmphenkkd\n"
                                        + "srijafyylogubxwttqmphenbkd\n"
                                        + "srijafyzloguvxzctadphenbkd\n"
                                        + "srijafyzloguoxwhtqmchenbkd\n"
                                        + "srijafyzloguvxwcvqmzhenbko\n"
                                        + "srijnfyzloguvxwctqmchenjkd\n"
                                        + "srijaryzloggvxwctqzphenbkd\n"
                                        + "srijafhzleguvxwcxqmphenbkd\n"
                                        + "ssijafyzllguvxfctqmphenbkd\n"
                                        + "srijafyzloguvxdctqmfhenbcd\n"
                                        + "srijafyzloguvxfctqmplynbkd\n"
                                        + "srijaftzlogavxwcrqmphenbkd\n"
                                        + "sriwaoyzloguvxwctqmphenbtd\n"
                                        + "srijahyzlogunxwctqmphenbvd\n"
                                        + "srjjafyzloguzxwctumphenbkd\n"
                                        + "nrijafyzlxguvxwctqmphanbkd\n"
                                        + "srijafezlqguyxwctqmphenbkd\n"
                                        + "srijafygloguvxwjtqcphenbkd\n"
                                        + "erijafyzloguvxoctqmnhenbkd\n"
                                        + "ssijafyzllguvxwbtqmphenbkd\n"
                                        + "sriaafyzloguvxwctqqphenbkv\n"
                                        + "frijafyzloguvswctwmphenbkd\n"
                                        + "srijafyzyogkvxwctqmprenbkd\n"
                                        + "syijafyzuoguvxwctqmkhenbkd\n"
                                        + "srijafyzloganxwctqmphenbkf\n"
                                        + "srijafyzloguvxwftqmxhenbkq\n"
                                        + "srijafyflogxvxwctqmghenbkd\n"
                                        + "srijafyzsoguvxwctqmpjenwkd\n"
                                        + "srujafylloguvxwctqmphenckd\n"
                                        + "srijafyzlpzuvxwctqmphenbud\n"
                                        + "srijafyzlogfvxwctqmhhenbwd\n"
                                        + "srijafjzlogusxwctqmphepbkd\n"
                                        + "srijlfyzloguvxwctqfphenzkd\n"
                                        + "srijafyzlogwvxwctqyphenbqd\n"
                                        + "srijafyzloluvxwctqtphenukd\n"
                                        + "srizafyzlowuvxwctqmphqnbkd\n"
                                        + "sritafkzlkguvxwctqmphenbkd\n"
                                        + "sbijafdzloguvxgctqmphenbkd\n"
                                        + "crijafyeloguvxwctqmpsenbkd\n"
                                        + "srijafyvlogulxwctqmphenbkk\n"
                                        + "srijafyologuvxwctqmehegbkd\n"
                                        + "siijafyzloguvxwctjmphenbmd\n"
                                        + "srijafyzlupuvxwctqmpheabkd\n"
                                        + "srijafyzlogumxwctqqphanbkd\n"
                                        + "srijxfyzlogujxwcqqmphenbkd\n"
                                        + "irijafizeoguvxwctqmphenbkd\n"
                                        + "sgijafyzloguvtwctqmpfenbkd\n"
                                        + "srijzfyzloguvmwctnmphenbkd\n"
                                        + "srijafyzwohuvxwctqmthenbkd\n"
                                        + "srijafyzlhguvxoctqwphenbkd\n"
                                        + "srgjafyplogxvxwctqmphenbkd\n"
                                        + "srijafyqlogovxwctqzphenbkd\n"
                                        + "srijafjzloguvlnvtqmphenbkd\n"
                                        + "srijafyzooguvxwctqmphenvud\n"
                                        + "srijafyzgoguvxwctumphgnbkd\n"
                                        + "srijaffzloguvxwdqqmphenbkd\n"
                                        + "srijafyzlogugxwctqxphenbkr\n"
                                        + "srijafyzlogutxwctqmmcenbkd\n"
                                        + "srifafyzlhguwxwctqmphenbkd\n"
                                        + "mrimajyzloguvxwctqmphenbkd\n"
                                        + "sriyafyzloguvxwcthmphejbkd\n"
                                        + "srieakyzlokuvxwctqmphenbkd\n"
                                        + "srisafyzloguhxwctqmphecbkd\n"
                                        + "srijanyzloguvxcctqmxhenbkd\n"
                                        + "srijafyzypguvxwctqmqhenbkd\n"
                                        + "sryjtfyzlvguvxwctqmphenbkd\n"
                                        + "srijafyzlsguvxwctqmqfenbkd\n"
                                        + "srijafyzlogudxwbtqwphenbkd\n"
                                        + "srijysyzloguvxwctqmpvenbkd\n"
                                        + "srijafyzloggvxwjtqmphegbkd\n"
                                        + "srijgfyzloguvxwctqmbhdnbkd\n"
                                        + "ssijufyzloguvawctqmphenbkd\n"
                                        + "skojafyzloguvxwctqmphenbnd\n"
                                        + "srijafylloguvxwcqqmpienbkd\n"
                                        + "trioafyzloguvqwctqmphenbkd\n"
                                        + "srijafydloguvxwctqmpzjnbkd\n"
                                        + "saijafvzloguvxwcqqmphenbkd\n"
                                        + "srhjapyzloguvxwctqmbhenbkd\n"
                                        + "srijafyzlfguvxwcsqmpwenbkd\n"
                                        + "shijafyzboguvxwctqmphenbmd\n"
                                        + "srizafysloguvxwrtqmphenbkd\n"
                                        + "srijafyzloguvxwciqmwhenbkj\n"
                                        + "qrijafyzloduvxwctqmphenbko\n"
                                        + "srijefyuloguvxwctqmphenbed\n"
                                        + "srijafyzlobuvxwctqmphenhbd\n"
                                        + "srijafyzloxuvxwctqmpheabkq\n"
                                        + "srijafyzloguvrwctqmghenkkd\n"
                                        + "sfisafywloguvxwctqmphenbkd\n"
                                        + "srgjafyzlogurxwctqmphenbkp\n"
                                        + "srijafhzloguvxwcjqmphenhkd\n"
                                        + "srijafyylogufxwrtqmphenbkd\n"
                                        + "srijafyzvoguvxwzkqmphenbkd\n"
                                        + "sqijafyzloguvxwctqmpheqbxd\n"
                                        + "srijafyvloguvxwctqzpherbkd\n"
                                        + "srijufyzloguvxlcsqmphenbkd\n"
                                        + "srijafykloguvxlccqmphenbkd\n"
                                        + "srijafyzloguexwcrqmphenzkd\n"
                                        + "sridifyzloguyxwctqmphenbkd\n"
                                        + "srijafyzlogfvxwctqlphenbkl\n"
                                        + "srijafyzlodqdxwctqmphenbkd\n"
                                        + "srijafyzloruvxactqmphenekd\n"
                                        + "grijafyzloguvxpctmmphenbkd\n"
                                        + "srsjakyzloguvxwctqmphvnbkd\n"
                                        + "srikafyvloguvxwrtqmphenbkd\n"
                                        + "srijafyzloguvxwctqjpserbkd\n"
                                        + "jrijafyzloguvxwctqmpgesbkd\n"
                                        + "swijafyzluguvxwctqmfhenbkd\n"
                                        + "srijanynlogovxwctqmphenbkd\n"
                                        + "jrijafyzloguvxwctymphrnbkd\n"
                                        + "srinafyzloguvewctqmphenbzd\n"
                                        + "srijakyzloguvxwctqmphcnbka\n"
                                        + "srijafyhlobuvxwctqmphenbka\n"
                                        + "srijafyzcogusxwctqmphwnbkd\n"
                                        + "srijavyzlosuvxwctqmphjnbkd\n"
                                        + "orijafyzxoguvxwcnqmphenbkd\n"
                                        + "srijafyzlogcvxwvtqmthenbkd\n"
                                        + "srijapyzloauvxwctqmphenvkd\n"
                                        + "srijaflzloguhxwctqmphenbwd\n"
                                        + "smijafyzlonuvxwctqmphenbkw\n"
                                        + "jrijafyzloguvxwclqmnhenbkd\n"
                                        + "srijaqyzloguvqwctqmphenskd\n"
                                        + "srijasyzloguvxwctqmvhenbku\n"
                                        + "crijtfyzloguvxwctqmthenbkd\n"
                                        + "srrkafyzvoguvxwctqmphenbkd\n"
                                        + "srijatyzloguvewctqmphenbld\n"
                                        + "srfjafyyloguvnwctqmphenbkd\n"
                                        + "srijafyzloguvxwctqjpbenbkt\n"
                                        + "hrijafyzooguvxwctqmphenbld\n"
                                        + "srijafbzlogscxwctqmphenbkd\n"
                                        + "srinafyzlogxvxwctqqphenbkd\n"
                                        + "slijafyzloglvxwctqmphenbdd\n"
                                        + "srijafyzlogjvxwcsqmphenbld\n"
                                        + "sryjcfyzloguvewctqmphenbkd\n"
                                        + "srijafyzloguexwctqmohknbkd\n"
                                        + "jaijafyzlogevxwctqmphenbkd\n"
                                        + "srijafbzlogavxwctqmphenbki\n"
                                        + "srijafozlogpvxwctqmphgnbkd\n"
                                        + "srijdfyzloguvxwczqmphenbkm\n"
                                        + "srijafyzlobuvxwctqmphxndkd\n"
                                        + "mrijifyzlhguvxwctqmphenbkd\n"
                                        + "srijafyzloguvxbctumphjnbkd\n"
                                        + "srijafyzloyuvxwptqmphlnbkd\n"
                                        + "arijafyzloguvxwcsqmohenbkd\n"
                                        + "srijaftzioguvxwttqmphenbkd\n"
                                        + "srijafyzlqsuvxwctqmphxnbkd\n"
                                        + "srijafyzioguvxwctqnphetbkd\n"
                                        + "prijafbzloguvxdctqmphenbkd\n"
                                        + "srijaeyzlnguvxwmtqmphenbkd\n"
                                        + "srijofyzloguvqwctqmphonbkd\n"
                                        + "srixaryzpoguvxwctqmphenbkd\n"
                                        + "srijafyzlowuvxwcwhmphenbkd\n"
                                        + "srijafydloguvxwctqmptenikd\n"
                                        + "srijqfyzlogtvfwctqmphenbkd\n"
                                        + "srijafyzloguvxlctqmpvenbgd\n"
                                        + "srijafyzlbguvxwjtqgphenbkd\n"
                                        + "srijafyzlohuqxwctqmphenbka\n"
                                        + "srijafyzroguvxictqmphynbkd\n"
                                        + "srijafyzloguvxdctjmphenjkd\n"
                                        + "srijaoczloguvxwctqmphenbjd\n"
                                        + "srajafhzloguvxwctqmphenbke\n"
                                        + "srijofyzloduvxwctqmphanbkd\n"
                                        + "srijafytloguvxwmtnmphenbkd\n"
                                        + "srijafyzuoguvxwceqmpgenbkd\n"
                                        + "rrijafyzloyuvxwctqmphlnbkd\n"
                                        + "srljafyzloguvxictqmohenbkd\n"
                                        + "srijafyzlogulxwcrqrphenbkd\n"
                                        + "srajafyzloguvxwctqmphanbke\n"
                                        + "srijafyzlhguvxwxtqmpheabkd\n"
                                        + "sxijafyzloggwxwctqmphenbkd\n"
                                        + "srijafyultguvxwctqmphinbkd\n"
                                        + "srijafyzloguvtwctqmfhvnbkd\n"
                                        + "srijafwzloruvxwctquphenbkd\n"
                                        + "srbjafyzxoguuxwctqmphenbkd\n"
                                        + "erijafyzlxguvxbctqmphenbkd\n"
                                        + "srijagyzlojubxwctqmphenbkd\n"
                                        + "srijafyzloguvxwdtqmchenakd\n"
                                        + "srijafkzlogukxwctqiphenbkd\n"
                                        + "mridafyzloguvxwctqmphenrkd\n"
                                        + "szqjafyzloguvxwctqmpheibkd\n"
                                        + "srijahyzloguvxwctcmphenekd\n"
                                        + "srijafyzloguvxwczpuphenbkd\n"
                                        + "srijafyzcoguvfwctqmphenbkq\n"
                                        + "qriiafyzloguvxwctqmpheebkd\n"
                                        + "srijpfyzloguvxlctqmphenokd\n"
                                        + "srijzfyzlotuvxwcjqmphenbkd\n"
                                        + "srinafyqloguvxwctfmphenbkd\n"
                                        + "srijafyzlogjvxpltqmphenbkd\n"
                                        + "srijafyzlotuvxwutqmphenbtd\n"
                                        + "sridafyzloguvxwctqmpyenokd\n"
                                        + "srxjafyzqogyvxwctqmphenbkd\n"
                                        + "ssijafyzzoguvxwctqmphenbad\n"
                                        + "srijafrzloguvxwctqmphekpkd\n"
                                        + "srijafyzlfgrvxactqmphenbkd\n"
                                        + "srijafyzroguvxwttqmphekbkd\n"
                                        + "srijefyzloguvxwctqmpqenbrd\n"
                                        + "srijefycloguvxwctqmchenbkd\n"
                                        + "srzjafyzloguvxwcqqmphanbkd\n"
                                        + "srijauyzlhguvxwctqmphenbgd\n"
                                        + "srijafyzloguvmwvnqmphenbkd\n"
                                        + "srihafyzloguvlwotqmphenbkd\n"
                                        + "srigafyzloguvxwctqmphennsd\n"
                                        + "sriuafzzloguvxwcuqmphenbkd\n"
                                        + "srijavuzllguvxwctqmphenbkd\n"
                                        + "srijafjzloguvlnctqmphenbkd\n"
                                        + "lrirafyzloguvxwctqmphenbld\n"
                                        + "soijarxzloguvxwctqmphenbkd\n"
                                        + "srijapyzlnguvxwctqmdhenbkd\n"
                                        + "srijafyzkogujxmctqmphenbkd\n"
                                        + "srijafuzloguvxwcsqvphenbkd\n"
                                        + "srijagyzzoguvxwctqmpvenbkd\n"
                                        + "srijafyzlovuvxwctqmrhenbxd\n"
                                        + "srijafyzqoguvxwctwmpienbkd\n"
                                        + "sxijafyzloguvxwutqmphenlkd\n"
                                        + "srijafyzlhgzvxwctqmphqnbkd\n"
                                        + "srijajyzloguvxwcbwmphenbkd\n"
                                        + "srijazyzloguvxwhtqmphenbkx\n"
                                        + "srgjafyzloguvvwctqmphdnbkd\n"
                                        + "rrivafyzloguvxjctqmphenbkd\n"
                                        + "srijifyzdoguvxwctqmphenbka\n"
                                        + "hrijafyzloguvxectqmpheybkd";
}
