package aoc2020;

import static java.lang.Integer.parseInt;

import aoc2020.Util.Pos;

// 65701 to high
// 25129 to low
public class Day12 {
    public static void main(String[] args) {
//        String input = TEST_INPUT;
        String input = INPUT;
        a(input);
        b(input);
    }

    enum Dir {N, S, W, E}

    enum Action {N, S, E, W, L, R, F}

    static class Instruction {
        final Action action;
        final int value;

        Instruction(Action action, int value) {
            this.action = action;
            this.value = value;
        }
    }

    private static void b(String input) {
        Instruction[] instructions = input.lines()
                                          .map(l -> new Instruction(Action.valueOf(l.substring(0, 1)), parseInt(l.substring(1))))
                                          .toArray(Instruction[]::new);
        Pos ship = new Pos(0, 0);
        Pos waypoint = new Pos(10, 1);
        for (Instruction instruction : instructions) {
            switch (instruction.action) {
            case N:
                waypoint = new Pos(waypoint.x, waypoint.y + instruction.value);
                break;
            case S:
                waypoint = new Pos(waypoint.x, waypoint.y - instruction.value);
                break;
            case E:
                waypoint = new Pos(waypoint.x + instruction.value, waypoint.y);
                break;
            case W:
                waypoint = new Pos(waypoint.x - instruction.value, waypoint.y);
                break;
            case L:
                waypoint = waypoint.rotate(instruction.value, ship);
                break;
            case R:
                waypoint = waypoint.rotate(-instruction.value, ship);
                break;
            case F:
                int velX = (waypoint.x - ship.x) * instruction.value;
                int velY = (waypoint.y - ship.y) * instruction.value;
                ship = new Pos(ship.x + (velX), ship.y + (velY));
                waypoint = new Pos(waypoint.x + (velX), waypoint.y + (velY));
            }
            System.out.println(instruction.action.name() + instruction.value + " => " + ship.x + ", " + ship.y + " | " + waypoint.x + ", " + waypoint.y);
        }
        System.out.println(Math.abs(ship.x) + " " + Math.abs(ship.y) + " = " + (Math.abs(ship.x) + Math.abs(ship.y)));

    }

    private static void a(String input) {
        Instruction[] instructions = input.lines()
                                          .map(l -> new Instruction(Action.valueOf(l.substring(0, 1)), parseInt(l.substring(1))))
                                          .toArray(Instruction[]::new);
        Dir dir = Dir.E;
        int x = 0;
        int y = 0;
        for (Instruction instruction : instructions) {
            int degrees;
            switch (instruction.action) {
            case N:
                y += instruction.value;
                break;
            case S:
                y -= instruction.value;
                break;
            case E:
                x += instruction.value;
                break;
            case W:
                x -= instruction.value;
                break;
            case L:
                degrees = instruction.value;
                while (degrees > 0) {
                    degrees -= 90;
                    switch (dir) {
                    case N:
                        dir = Dir.W;
                        break;
                    case S:
                        dir = Dir.E;
                        break;
                    case E:
                        dir = Dir.N;
                        break;
                    case W:
                        dir = Dir.S;
                        break;
                    }
                }
                break;
            case R:
                degrees = instruction.value;
                while (degrees > 0) {
                    degrees -= 90;
                    switch (dir) {
                    case N:
                        dir = Dir.E;
                        break;
                    case S:
                        dir = Dir.W;
                        break;
                    case E:
                        dir = Dir.S;
                        break;
                    case W:
                        dir = Dir.N;
                        break;
                    }
                }
                break;
            case F:
                switch (dir) {
                case N:
                    y += instruction.value;
                    break;
                case S:
                    y -= instruction.value;
                    break;
                case E:
                    x += instruction.value;
                    break;
                case W:
                    x -= instruction.value;
                    break;
                }
            }
        }
        System.out.println(Math.abs(x) + " " + Math.abs(y) + " = " + (Math.abs(x) + Math.abs(y)));
    }

    private static final String TEST_INPUT = "F10\n"
                                             + "N3\n"
                                             + "F7\n"
                                             + "R90\n"
                                             + "F11";

    private static final String INPUT = "L90\n"
                                        + "F67\n"
                                        + "R270\n"
                                        + "W1\n"
                                        + "R180\n"
                                        + "F5\n"
                                        + "E5\n"
                                        + "F59\n"
                                        + "E4\n"
                                        + "L180\n"
                                        + "F70\n"
                                        + "S2\n"
                                        + "F35\n"
                                        + "N3\n"
                                        + "E5\n"
                                        + "F58\n"
                                        + "L90\n"
                                        + "N1\n"
                                        + "F46\n"
                                        + "R90\n"
                                        + "S1\n"
                                        + "R90\n"
                                        + "E1\n"
                                        + "L180\n"
                                        + "W4\n"
                                        + "F99\n"
                                        + "N2\n"
                                        + "F84\n"
                                        + "N1\n"
                                        + "R90\n"
                                        + "N5\n"
                                        + "W4\n"
                                        + "F26\n"
                                        + "E1\n"
                                        + "F97\n"
                                        + "N1\n"
                                        + "F36\n"
                                        + "W1\n"
                                        + "F21\n"
                                        + "S4\n"
                                        + "F31\n"
                                        + "S3\n"
                                        + "F76\n"
                                        + "S5\n"
                                        + "S1\n"
                                        + "L90\n"
                                        + "S4\n"
                                        + "W4\n"
                                        + "R90\n"
                                        + "E4\n"
                                        + "F14\n"
                                        + "R90\n"
                                        + "S2\n"
                                        + "R90\n"
                                        + "S3\n"
                                        + "F21\n"
                                        + "N1\n"
                                        + "W4\n"
                                        + "S4\n"
                                        + "E1\n"
                                        + "L180\n"
                                        + "N5\n"
                                        + "F30\n"
                                        + "N3\n"
                                        + "F4\n"
                                        + "N5\n"
                                        + "F100\n"
                                        + "N2\n"
                                        + "R270\n"
                                        + "E1\n"
                                        + "S1\n"
                                        + "F79\n"
                                        + "N4\n"
                                        + "F72\n"
                                        + "W4\n"
                                        + "F50\n"
                                        + "L90\n"
                                        + "W5\n"
                                        + "S4\n"
                                        + "E2\n"
                                        + "N5\n"
                                        + "E4\n"
                                        + "S5\n"
                                        + "W5\n"
                                        + "L90\n"
                                        + "E4\n"
                                        + "L90\n"
                                        + "S4\n"
                                        + "E4\n"
                                        + "R90\n"
                                        + "N1\n"
                                        + "W5\n"
                                        + "R270\n"
                                        + "W5\n"
                                        + "N4\n"
                                        + "R180\n"
                                        + "E5\n"
                                        + "F86\n"
                                        + "L90\n"
                                        + "W3\n"
                                        + "F79\n"
                                        + "W5\n"
                                        + "F87\n"
                                        + "L180\n"
                                        + "N4\n"
                                        + "E2\n"
                                        + "S1\n"
                                        + "W3\n"
                                        + "N3\n"
                                        + "F31\n"
                                        + "W2\n"
                                        + "N1\n"
                                        + "F86\n"
                                        + "E1\n"
                                        + "L90\n"
                                        + "L90\n"
                                        + "F2\n"
                                        + "E3\n"
                                        + "F8\n"
                                        + "L90\n"
                                        + "F54\n"
                                        + "W3\n"
                                        + "S5\n"
                                        + "E3\n"
                                        + "F89\n"
                                        + "N5\n"
                                        + "R90\n"
                                        + "E3\n"
                                        + "F70\n"
                                        + "N2\n"
                                        + "R90\n"
                                        + "F55\n"
                                        + "W3\n"
                                        + "R90\n"
                                        + "F44\n"
                                        + "E2\n"
                                        + "F36\n"
                                        + "L90\n"
                                        + "E3\n"
                                        + "S2\n"
                                        + "F23\n"
                                        + "N4\n"
                                        + "F2\n"
                                        + "W5\n"
                                        + "L180\n"
                                        + "E4\n"
                                        + "N4\n"
                                        + "W3\n"
                                        + "F58\n"
                                        + "W1\n"
                                        + "R90\n"
                                        + "W1\n"
                                        + "L90\n"
                                        + "E1\n"
                                        + "F99\n"
                                        + "W4\n"
                                        + "S4\n"
                                        + "E5\n"
                                        + "N2\n"
                                        + "R180\n"
                                        + "E5\n"
                                        + "F82\n"
                                        + "N3\n"
                                        + "F99\n"
                                        + "L90\n"
                                        + "N4\n"
                                        + "E4\n"
                                        + "S5\n"
                                        + "R90\n"
                                        + "N3\n"
                                        + "F17\n"
                                        + "S5\n"
                                        + "E4\n"
                                        + "F58\n"
                                        + "E1\n"
                                        + "N1\n"
                                        + "E5\n"
                                        + "R90\n"
                                        + "F32\n"
                                        + "N1\n"
                                        + "R90\n"
                                        + "F84\n"
                                        + "E4\n"
                                        + "W4\n"
                                        + "R180\n"
                                        + "E4\n"
                                        + "R90\n"
                                        + "N1\n"
                                        + "F26\n"
                                        + "W4\n"
                                        + "R90\n"
                                        + "F96\n"
                                        + "E5\n"
                                        + "S2\n"
                                        + "F86\n"
                                        + "R90\n"
                                        + "F95\n"
                                        + "S4\n"
                                        + "F81\n"
                                        + "R90\n"
                                        + "W4\n"
                                        + "F44\n"
                                        + "N3\n"
                                        + "W3\n"
                                        + "N5\n"
                                        + "L180\n"
                                        + "L90\n"
                                        + "F71\n"
                                        + "S4\n"
                                        + "R90\n"
                                        + "E5\n"
                                        + "N4\n"
                                        + "F63\n"
                                        + "W2\n"
                                        + "F75\n"
                                        + "N3\n"
                                        + "R90\n"
                                        + "S2\n"
                                        + "E3\n"
                                        + "F75\n"
                                        + "R90\n"
                                        + "W3\n"
                                        + "F4\n"
                                        + "L90\n"
                                        + "E3\n"
                                        + "F96\n"
                                        + "L180\n"
                                        + "F53\n"
                                        + "W5\n"
                                        + "L90\n"
                                        + "F12\n"
                                        + "N2\n"
                                        + "F100\n"
                                        + "W2\n"
                                        + "R270\n"
                                        + "S1\n"
                                        + "F37\n"
                                        + "E4\n"
                                        + "S1\n"
                                        + "E1\n"
                                        + "L270\n"
                                        + "W2\n"
                                        + "S5\n"
                                        + "F10\n"
                                        + "L90\n"
                                        + "N3\n"
                                        + "F63\n"
                                        + "L90\n"
                                        + "F96\n"
                                        + "S3\n"
                                        + "W1\n"
                                        + "N4\n"
                                        + "R180\n"
                                        + "E2\n"
                                        + "F51\n"
                                        + "L90\n"
                                        + "N4\n"
                                        + "F27\n"
                                        + "W3\n"
                                        + "N5\n"
                                        + "R90\n"
                                        + "N4\n"
                                        + "L180\n"
                                        + "F4\n"
                                        + "N1\n"
                                        + "L180\n"
                                        + "F71\n"
                                        + "E5\n"
                                        + "S5\n"
                                        + "F94\n"
                                        + "L90\n"
                                        + "F98\n"
                                        + "E3\n"
                                        + "N4\n"
                                        + "E5\n"
                                        + "R90\n"
                                        + "F75\n"
                                        + "S1\n"
                                        + "F19\n"
                                        + "E2\n"
                                        + "F53\n"
                                        + "S3\n"
                                        + "L90\n"
                                        + "F29\n"
                                        + "R180\n"
                                        + "F88\n"
                                        + "R180\n"
                                        + "F3\n"
                                        + "S2\n"
                                        + "E5\n"
                                        + "F16\n"
                                        + "L90\n"
                                        + "E1\n"
                                        + "S2\n"
                                        + "E3\n"
                                        + "F28\n"
                                        + "E5\n"
                                        + "F22\n"
                                        + "L180\n"
                                        + "S2\n"
                                        + "E1\n"
                                        + "S1\n"
                                        + "F6\n"
                                        + "E2\n"
                                        + "S3\n"
                                        + "F14\n"
                                        + "R90\n"
                                        + "N4\n"
                                        + "S5\n"
                                        + "F77\n"
                                        + "L90\n"
                                        + "N3\n"
                                        + "R90\n"
                                        + "N2\n"
                                        + "L180\n"
                                        + "F99\n"
                                        + "E2\n"
                                        + "F85\n"
                                        + "S3\n"
                                        + "F81\n"
                                        + "N1\n"
                                        + "W1\n"
                                        + "F91\n"
                                        + "F31\n"
                                        + "N5\n"
                                        + "W5\n"
                                        + "R90\n"
                                        + "S1\n"
                                        + "F40\n"
                                        + "N2\n"
                                        + "E1\n"
                                        + "S3\n"
                                        + "L90\n"
                                        + "E5\n"
                                        + "R180\n"
                                        + "E2\n"
                                        + "L90\n"
                                        + "F88\n"
                                        + "R90\n"
                                        + "F45\n"
                                        + "R270\n"
                                        + "W4\n"
                                        + "F67\n"
                                        + "W4\n"
                                        + "S1\n"
                                        + "W4\n"
                                        + "F65\n"
                                        + "L90\n"
                                        + "F19\n"
                                        + "R90\n"
                                        + "F83\n"
                                        + "S1\n"
                                        + "R90\n"
                                        + "E2\n"
                                        + "R180\n"
                                        + "F78\n"
                                        + "E1\n"
                                        + "E1\n"
                                        + "L180\n"
                                        + "S1\n"
                                        + "E1\n"
                                        + "N4\n"
                                        + "W5\n"
                                        + "F98\n"
                                        + "L90\n"
                                        + "E4\n"
                                        + "L90\n"
                                        + "N2\n"
                                        + "E1\n"
                                        + "N4\n"
                                        + "E1\n"
                                        + "N5\n"
                                        + "L90\n"
                                        + "S3\n"
                                        + "F52\n"
                                        + "W5\n"
                                        + "F55\n"
                                        + "S4\n"
                                        + "R180\n"
                                        + "F56\n"
                                        + "S5\n"
                                        + "E1\n"
                                        + "R90\n"
                                        + "F97\n"
                                        + "E5\n"
                                        + "N4\n"
                                        + "L90\n"
                                        + "E1\n"
                                        + "N1\n"
                                        + "W1\n"
                                        + "N4\n"
                                        + "L270\n"
                                        + "F7\n"
                                        + "N3\n"
                                        + "L90\n"
                                        + "W3\n"
                                        + "L270\n"
                                        + "F27\n"
                                        + "E2\n"
                                        + "N5\n"
                                        + "F90\n"
                                        + "N3\n"
                                        + "R90\n"
                                        + "F79\n"
                                        + "N4\n"
                                        + "F58\n"
                                        + "L90\n"
                                        + "W5\n"
                                        + "F90\n"
                                        + "F9\n"
                                        + "E5\n"
                                        + "R90\n"
                                        + "F16\n"
                                        + "E4\n"
                                        + "F50\n"
                                        + "S1\n"
                                        + "R90\n"
                                        + "N5\n"
                                        + "E2\n"
                                        + "F86\n"
                                        + "E3\n"
                                        + "L270\n"
                                        + "W3\n"
                                        + "L90\n"
                                        + "W1\n"
                                        + "F17\n"
                                        + "N2\n"
                                        + "L180\n"
                                        + "N1\n"
                                        + "W4\n"
                                        + "R180\n"
                                        + "F10\n"
                                        + "N3\n"
                                        + "W3\n"
                                        + "L90\n"
                                        + "E2\n"
                                        + "F12\n"
                                        + "S5\n"
                                        + "L90\n"
                                        + "N3\n"
                                        + "W4\n"
                                        + "N3\n"
                                        + "F19\n"
                                        + "E5\n"
                                        + "F54\n"
                                        + "E1\n"
                                        + "F34\n"
                                        + "F2\n"
                                        + "S4\n"
                                        + "F14\n"
                                        + "R90\n"
                                        + "S4\n"
                                        + "F2\n"
                                        + "N1\n"
                                        + "E3\n"
                                        + "N2\n"
                                        + "L180\n"
                                        + "E5\n"
                                        + "F67\n"
                                        + "L180\n"
                                        + "F66\n"
                                        + "E3\n"
                                        + "S4\n"
                                        + "W3\n"
                                        + "F51\n"
                                        + "L270\n"
                                        + "N5\n"
                                        + "F51\n"
                                        + "W3\n"
                                        + "S2\n"
                                        + "E2\n"
                                        + "N2\n"
                                        + "F27\n"
                                        + "W5\n"
                                        + "F77\n"
                                        + "E4\n"
                                        + "N5\n"
                                        + "E2\n"
                                        + "F20\n"
                                        + "N5\n"
                                        + "E4\n"
                                        + "S5\n"
                                        + "F67\n"
                                        + "S2\n"
                                        + "F81\n"
                                        + "L90\n"
                                        + "F68\n"
                                        + "E4\n"
                                        + "F71\n"
                                        + "L90\n"
                                        + "F48\n"
                                        + "N3\n"
                                        + "F1\n"
                                        + "N5\n"
                                        + "R90\n"
                                        + "F76\n"
                                        + "W5\n"
                                        + "S5\n"
                                        + "F74\n"
                                        + "S1\n"
                                        + "E2\n"
                                        + "F52\n"
                                        + "R90\n"
                                        + "W1\n"
                                        + "S4\n"
                                        + "F13\n"
                                        + "F69\n"
                                        + "L180\n"
                                        + "F59\n"
                                        + "N3\n"
                                        + "F34\n"
                                        + "F84\n"
                                        + "R90\n"
                                        + "F63\n"
                                        + "W2\n"
                                        + "L90\n"
                                        + "F12\n"
                                        + "L90\n"
                                        + "W5\n"
                                        + "F25\n"
                                        + "F83\n"
                                        + "E4\n"
                                        + "N1\n"
                                        + "R90\n"
                                        + "F36\n"
                                        + "S1\n"
                                        + "W2\n"
                                        + "F41\n"
                                        + "R90\n"
                                        + "N3\n"
                                        + "W1\n"
                                        + "R180\n"
                                        + "W2\n"
                                        + "L90\n"
                                        + "N4\n"
                                        + "F87\n"
                                        + "E3\n"
                                        + "S4\n"
                                        + "F10\n"
                                        + "S3\n"
                                        + "F33\n"
                                        + "R90\n"
                                        + "E1\n"
                                        + "L180\n"
                                        + "F32\n"
                                        + "W5\n"
                                        + "S3\n"
                                        + "F23\n"
                                        + "R90\n"
                                        + "F44\n"
                                        + "L90\n"
                                        + "F45\n"
                                        + "E2\n"
                                        + "L270\n"
                                        + "F41\n"
                                        + "W1\n"
                                        + "F54\n"
                                        + "L180\n"
                                        + "F31\n"
                                        + "R90\n"
                                        + "F43\n"
                                        + "S3\n"
                                        + "F91\n"
                                        + "F88\n"
                                        + "L180\n"
                                        + "F2\n"
                                        + "W2\n"
                                        + "N5\n"
                                        + "W2\n"
                                        + "S1\n"
                                        + "L180\n"
                                        + "F12\n"
                                        + "N2\n"
                                        + "F2\n"
                                        + "N3\n"
                                        + "W2\n"
                                        + "R90\n"
                                        + "S2\n"
                                        + "E4\n"
                                        + "F66\n"
                                        + "S2\n"
                                        + "W4\n"
                                        + "F94\n"
                                        + "S5\n"
                                        + "E1\n"
                                        + "L180\n"
                                        + "N5\n"
                                        + "F2\n"
                                        + "N2\n"
                                        + "R180\n"
                                        + "E3\n"
                                        + "F3\n"
                                        + "E1\n"
                                        + "R90\n"
                                        + "S3\n"
                                        + "F28\n"
                                        + "L90\n"
                                        + "F12\n"
                                        + "L90\n"
                                        + "S2\n"
                                        + "F100\n"
                                        + "L90\n"
                                        + "F84\n"
                                        + "E2\n"
                                        + "R90\n"
                                        + "W4\n"
                                        + "F14\n"
                                        + "N1\n"
                                        + "W3\n"
                                        + "F33\n"
                                        + "W1\n"
                                        + "N5\n"
                                        + "R180\n"
                                        + "F93\n"
                                        + "W5\n"
                                        + "N2\n"
                                        + "E4\n"
                                        + "L180\n"
                                        + "W3\n"
                                        + "F2\n"
                                        + "S1\n"
                                        + "W4\n"
                                        + "L90\n"
                                        + "F8\n"
                                        + "W2\n"
                                        + "F83\n"
                                        + "E5\n"
                                        + "R180\n"
                                        + "W4\n"
                                        + "S4\n"
                                        + "R90\n"
                                        + "E4\n"
                                        + "R180\n"
                                        + "F84\n"
                                        + "E2\n"
                                        + "N3\n"
                                        + "W3\n"
                                        + "N1\n"
                                        + "L90\n"
                                        + "F76\n"
                                        + "W1\n"
                                        + "F9\n"
                                        + "E1\n"
                                        + "S1\n"
                                        + "E5\n"
                                        + "L90\n"
                                        + "S1\n"
                                        + "S5\n"
                                        + "W4\n"
                                        + "S3\n"
                                        + "F20\n"
                                        + "N2\n"
                                        + "F52\n"
                                        + "R180\n"
                                        + "F21\n"
                                        + "W4\n"
                                        + "N2\n"
                                        + "L90\n"
                                        + "F42\n"
                                        + "S3\n"
                                        + "E5\n"
                                        + "N4\n"
                                        + "F100\n"
                                        + "E5\n"
                                        + "N5\n"
                                        + "F56\n"
                                        + "L90\n"
                                        + "F90\n"
                                        + "S1\n"
                                        + "E2\n"
                                        + "N2\n"
                                        + "F42\n"
                                        + "E3\n"
                                        + "L90\n"
                                        + "W4\n"
                                        + "R180\n"
                                        + "F22\n"
                                        + "L90\n"
                                        + "R90\n"
                                        + "F48\n"
                                        + "E4\n"
                                        + "N4\n"
                                        + "E5\n"
                                        + "F10\n"
                                        + "L90\n"
                                        + "N5\n"
                                        + "F99\n"
                                        + "S4\n"
                                        + "E3\n"
                                        + "R90\n"
                                        + "N5\n"
                                        + "E3\n"
                                        + "F85\n"
                                        + "F83\n"
                                        + "W1\n"
                                        + "R180\n"
                                        + "L90\n"
                                        + "W4\n"
                                        + "R90\n"
                                        + "W1\n"
                                        + "L90\n"
                                        + "S4\n"
                                        + "L90\n"
                                        + "N3\n"
                                        + "W5\n"
                                        + "L90\n"
                                        + "R90\n"
                                        + "F68\n"
                                        + "N2\n"
                                        + "W5\n"
                                        + "N4\n"
                                        + "W3\n"
                                        + "L90\n"
                                        + "E1\n"
                                        + "W1\n"
                                        + "L180\n"
                                        + "R90\n"
                                        + "F45\n"
                                        + "E5\n"
                                        + "R90\n"
                                        + "W5\n"
                                        + "S4\n"
                                        + "F5\n"
                                        + "L180\n"
                                        + "N1\n"
                                        + "R90\n"
                                        + "S4\n"
                                        + "E3\n"
                                        + "F22\n"
                                        + "R180\n"
                                        + "W4\n"
                                        + "L180\n"
                                        + "S3\n"
                                        + "L90\n"
                                        + "N5\n"
                                        + "E5\n"
                                        + "N1\n"
                                        + "F6\n"
                                        + "S5\n"
                                        + "W1\n"
                                        + "F86\n"
                                        + "R180\n"
                                        + "S1\n"
                                        + "R90\n"
                                        + "E5\n"
                                        + "N2\n"
                                        + "L90\n"
                                        + "W4\n"
                                        + "N1\n"
                                        + "W3\n"
                                        + "R90\n"
                                        + "F1\n"
                                        + "R180\n"
                                        + "F94\n"
                                        + "L90\n"
                                        + "E5\n"
                                        + "F7\n"
                                        + "R90\n"
                                        + "F72\n"
                                        + "R90\n"
                                        + "N3\n"
                                        + "N1\n"
                                        + "L180\n"
                                        + "N4\n"
                                        + "L90\n"
                                        + "N5\n"
                                        + "E1\n"
                                        + "N1\n"
                                        + "L270\n"
                                        + "S2\n"
                                        + "R90\n"
                                        + "F8\n"
                                        + "N4\n"
                                        + "E2\n"
                                        + "F8\n"
                                        + "S5\n"
                                        + "E2\n"
                                        + "S3\n"
                                        + "L90\n"
                                        + "F67\n"
                                        + "E4\n"
                                        + "F54\n"
                                        + "E1\n"
                                        + "F100\n"
                                        + "N2\n"
                                        + "F20";
}
