package aoc2020;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

public class Day19 {
    public static void main(String[] args) {
//        a(TEST_INPUT);
        a(INPUT);
//        b(TEST_INPUT);
//        b(INPUT);
    }


    private static void b(String input) {
    }

    private static void a(String input) {
        String[] rules = input.lines().filter(l -> l.contains(":")).toArray(String[]::new);
        String[] data = input.lines().filter(l -> !l.contains(":") && !l.isEmpty()).toArray(String[]::new);
        String eight = "42";
        String eleven = "42 31";
        int index0 = 0;
        for (int i = 0; i < rules.length; i++) {
            if (rules[i].startsWith("8:")) {
                for (int j = 1; j < 5; j++) {
                    eight += " | " + "42 ".repeat(j + 1);
                }
            } else if (rules[i].startsWith("11:")) {
                for (int j = 1; j < 5; j++) {
                    eleven += " | " + "42 ".repeat(j + 1) + " 31 ".repeat(j+1);
                }
            } else if (rules[i].startsWith("0:")) {
                index0 = i;
            }
        }
        rules[index0] = "0: ( " + eight + " ) ( " + eleven + " )";
        while (Arrays.stream(rules).anyMatch(r -> !full(r))) {
            String rule0 = Arrays.stream(rules).filter(r -> r.startsWith("0:")).findFirst().get();
            boolean hasDigits = false;
            for (int i = 2; i < rule0.length(); i++) {
                if (Character.isDigit(rule0.charAt(i))) {
                    hasDigits = true;
                    break;
                }
            }

            if (!hasDigits) {
                rules = new String[]{rule0};
                break;
            }

            for (int i = 0; i < rules.length; i++) {
                String rule = rules[i];
                String r = rule.substring(rule.indexOf(":") + 2);
                if (full(rule)) {
                    for (int j = 0; j < rules.length; j++) {
                        String rule2 = rules[j];
                        String nr2 = rule2.substring(0, rule2.indexOf(":") + 2);
                        String r2 = rule2.substring(rule2.indexOf(":") + 2);
                        String[] orParts = r2.split(" \\| ");
                        boolean matches = false;
                        for (int op = 0; op < orParts.length; op++) {
                            String orPart = orParts[op];
                            String[] parts = orPart.split(" ");
                            for (int p = 0; p < parts.length; p++) {
                                if (parts[p].equals(rule.substring(0, rule.indexOf(":")))) {
                                    parts[p] = rule.contains("|") ? "(" + r + ")" : r;
                                    matches = true;
                                }
                            }
                            if (matches) {
                                orParts[op] = String.join(" ", parts);
                            }
                        }
                        if (matches) {
                            rules[j] = nr2 + String.join(" | ", orParts);
                        }
                    }
                }
            }
        }
        for (int i = 0; i < rules.length; i++) {
            rules[i] = rules[i].replaceAll("\" \"", "");
            rules[i] = rules[i].replaceAll("\"", "");
        }
        String rule0 = Arrays.stream(rules).filter(r -> r.startsWith("0:")).findFirst().map(s -> s.substring(2).replaceAll(" ", "")).get();
        System.out.println(Arrays.stream(data).filter(d -> Pattern.matches(rule0, d)).count());
//        Set<String> expanded = expand(rule0);
//        System.out.println(Arrays.stream(data).filter(expanded::contains).count());

    }

    static Set<String> seen = new HashSet<>();

    static boolean full(String rule) {
        rule = rule.substring(rule.indexOf(":") + 2);
        return Arrays.stream(rule.replaceAll(" \\| ", " ").split(" ")).allMatch(r -> r.startsWith("\"") || r.startsWith("("));
    }

    private static final String TEST_INPUT = "0: 4 1 5\n"
                                             + "1: 2 3 | 3 2\n"
                                             + "2: 4 4 | 5 5\n"
                                             + "3: 4 5 | 5 4\n"
                                             + "4: \"a\"\n"
                                             + "5: \"b\"\n"
                                             + "\n"
                                             + "ababbb\n"
                                             + "bababa\n"
                                             + "abbbab\n"
                                             + "aaabbb\n"
                                             + "aaaabbb";

    private static final String INPUT = "101: 118 64\n"
                                        + "83: 132 118 | 108 2\n"
                                        + "61: 19 2\n"
                                        + "33: 126 2 | 68 118\n"
                                        + "80: 2 48 | 118 91\n"
                                        + "47: 38 2 | 64 118\n"
                                        + "40: 25 2 | 93 118\n"
                                        + "18: 38 2 | 108 118\n"
                                        + "2: \"a\"\n"
                                        + "74: 118 108 | 2 12\n"
                                        + "41: 118 17 | 2 58\n"
                                        + "56: 125 2 | 132 118\n"
                                        + "66: 12 2 | 27 118\n"
                                        + "62: 118 52 | 2 125\n"
                                        + "58: 2 128 | 118 99\n"
                                        + "89: 110 2 | 3 118\n"
                                        + "30: 118 85 | 2 21\n"
                                        + "20: 2 70 | 118 111\n"
                                        + "85: 118 115 | 2 52\n"
                                        + "98: 118 46 | 2 10\n"
                                        + "12: 118 2 | 43 118\n"
                                        + "99: 102 118 | 56 2\n"
                                        + "127: 2 119 | 118 100\n"
                                        + "53: 125 2 | 108 118\n"
                                        + "15: 2 27 | 118 108\n"
                                        + "22: 95 2 | 61 118\n"
                                        + "109: 115 2 | 46 118\n"
                                        + "90: 76 2 | 121 118\n"
                                        + "37: 15 118 | 23 2\n"
                                        + "27: 118 2 | 118 118\n"
                                        + "104: 2 46 | 118 12\n"
                                        + "32: 64 2\n"
                                        + "26: 35 118 | 32 2\n"
                                        + "123: 131 2 | 89 118\n"
                                        + "21: 118 132 | 2 115\n"
                                        + "95: 112 118 | 125 2\n"
                                        + "79: 88 2 | 60 118\n"
                                        + "34: 107 2 | 133 118\n"
                                        + "6: 2 101 | 118 110\n"
                                        + "55: 118 112 | 2 64\n"
                                        + "10: 2 118\n"
                                        + "115: 2 118 | 2 2\n"
                                        + "39: 2 61 | 118 81\n"
                                        + "42: 92 118 | 124 2\n"
                                        + "105: 38 2 | 10 118\n"
                                        + "7: 10 2 | 27 118\n"
                                        + "106: 87 2 | 1 118\n"
                                        + "75: 118 46\n"
                                        + "28: 2 71 | 118 16\n"
                                        + "120: 118 27 | 2 112\n"
                                        + "100: 69 2 | 109 118\n"
                                        + "102: 46 118 | 132 2\n"
                                        + "5: 39 118 | 51 2\n"
                                        + "14: 57 2 | 96 118\n"
                                        + "8: 42\n"
                                        + "25: 118 59 | 2 67\n"
                                        + "3: 19 118 | 52 2\n"
                                        + "59: 2 74 | 118 83\n"
                                        + "87: 118 72 | 2 78\n"
                                        + "130: 111 2 | 117 118\n"
                                        + "112: 2 43 | 118 118\n"
                                        + "116: 118 38 | 2 108\n"
                                        + "17: 2 122 | 118 29\n"
                                        + "124: 41 118 | 40 2\n"
                                        + "11: 42 31\n"
                                        + "38: 43 43\n"
                                        + "44: 118 123 | 2 114\n"
                                        + "23: 12 2\n"
                                        + "29: 2 113 | 118 129\n"
                                        + "121: 2 10 | 118 19\n"
                                        + "93: 2 26 | 118 36\n"
                                        + "13: 19 118 | 46 2\n"
                                        + "107: 118 132 | 2 10\n"
                                        + "54: 118 27 | 2 12\n"
                                        + "63: 2 105 | 118 82\n"
                                        + "84: 2 37 | 118 73\n"
                                        + "52: 118 2 | 2 118\n"
                                        + "50: 118 111 | 2 9\n"
                                        + "111: 118 112 | 2 27\n"
                                        + "82: 118 46 | 2 108\n"
                                        + "118: \"b\"\n"
                                        + "133: 115 2\n"
                                        + "103: 34 2 | 22 118\n"
                                        + "36: 66 2 | 65 118\n"
                                        + "31: 33 118 | 79 2\n"
                                        + "69: 12 2 | 115 118\n"
                                        + "122: 54 118 | 66 2\n"
                                        + "114: 6 118 | 80 2\n"
                                        + "92: 118 14 | 2 44\n"
                                        + "0: 8 11\n"
                                        + "117: 132 2 | 108 118\n"
                                        + "76: 64 2 | 27 118\n"
                                        + "126: 2 28 | 118 127\n"
                                        + "113: 125 2 | 19 118\n"
                                        + "43: 118 | 2\n"
                                        + "46: 118 118 | 2 118\n"
                                        + "132: 118 118 | 2 2\n"
                                        + "49: 118 130 | 2 50\n"
                                        + "129: 19 118 | 27 2\n"
                                        + "24: 2 27 | 118 52\n"
                                        + "119: 118 47 | 2 98\n"
                                        + "91: 19 118 | 10 2\n"
                                        + "35: 115 118 | 46 2\n"
                                        + "57: 2 63 | 118 90\n"
                                        + "125: 118 118 | 43 2\n"
                                        + "108: 118 118\n"
                                        + "4: 115 118 | 19 2\n"
                                        + "94: 112 2 | 115 118\n"
                                        + "1: 2 55 | 118 75\n"
                                        + "9: 38 118 | 112 2\n"
                                        + "71: 2 18 | 118 53\n"
                                        + "60: 103 2 | 86 118\n"
                                        + "51: 116 2 | 24 118\n"
                                        + "128: 24 118 | 117 2\n"
                                        + "45: 118 2\n"
                                        + "16: 104 2 | 62 118\n"
                                        + "70: 118 115 | 2 45\n"
                                        + "77: 118 13 | 2 94\n"
                                        + "131: 61 2 | 107 118\n"
                                        + "68: 2 49 | 118 84\n"
                                        + "86: 118 97 | 2 30\n"
                                        + "78: 118 38 | 2 12\n"
                                        + "88: 5 2 | 106 118\n"
                                        + "81: 2 45 | 118 52\n"
                                        + "64: 2 2\n"
                                        + "19: 2 43 | 118 2\n"
                                        + "110: 132 2 | 64 118\n"
                                        + "96: 2 77 | 118 20\n"
                                        + "67: 104 118 | 4 2\n"
                                        + "65: 115 118 | 38 2\n"
                                        + "73: 118 110 | 2 120\n"
                                        + "72: 64 2 | 115 118\n"
                                        + "48: 2 46 | 118 10\n"
                                        + "97: 7 118 | 133 2\n"
                                        + "\n"
                                        + "aaaaaababababbbbbababaab\n"
                                        + "aaababbabbbbbbabaaaabbaaabababaabababaaa\n"
                                        + "abaabababaababbaaaabbaaabaabbbaa\n"
                                        + "aabbaaaaabbbaabbaabbbabbbabaabbbaaabaabababaaabb\n"
                                        + "bababbbbbaaaaaababbbabbb\n"
                                        + "bababbaabbaaaaabbaabbabbbabbabbbbbbbbbababbbabab\n"
                                        + "aaabaababbaabbbbaaabaaabaabababb\n"
                                        + "babaaababbbaabaaaabababa\n"
                                        + "aaababbabbbbbaabaababbaabbababbbabaabbbbabababaaaaabbaab\n"
                                        + "baabbbbabaabaababbbbbabaabaabaabbaaaabab\n"
                                        + "bbbbaaabbabbbbabaaaabbabbbbbabaaaaaabbaa\n"
                                        + "bbababbbaabbaabaababbbab\n"
                                        + "bbaabbbabbbaababbbabbabb\n"
                                        + "abbaabbaaabbbaaaaabaabababbaabbababaabbbaaaabbaa\n"
                                        + "bbaababbbbbbbaabbbabaaab\n"
                                        + "baabbbaabbababbbababaaabaabbaabb\n"
                                        + "baaabbbababbbabbabbaabaa\n"
                                        + "bbaaabaabbbababbbbbbbabb\n"
                                        + "aabaabbbabaaaaabbbbaaaaa\n"
                                        + "babbbaaababbbbaaaabaaabbbabaabba\n"
                                        + "abbabbbbaabbaaaaabbbbbaabbbbbabbbaabaabb\n"
                                        + "aabbbbaaaabaaabbaabaaababbbbbabbbbaababa\n"
                                        + "abaaaabaabbaaabaabaaaabbabaaabaaaaabaaab\n"
                                        + "babaabbbbaaabaabbbababbbaabbababaaaaabababbbbaababbbbbbb\n"
                                        + "ababaaababaaaabbbababaab\n"
                                        + "bbbbabaabbbabbabbabbabbaaaabbaab\n"
                                        + "abababbbaaabababbbbbabbbaabbbabbbabaabaababbbbabaababbbb\n"
                                        + "bbaaaababaabbaabaabbababaabbbbba\n"
                                        + "abbaabaaabaaabaabababbbbbbaabaaaabbbabababbababbbabaabaabbabaaaa\n"
                                        + "bbbbaabaaaabaabbabababab\n"
                                        + "abbabbaabbbbbababbaabbbb\n"
                                        + "bbbbaabbababbbbbbbbbaabaaabbabaaaabaaaba\n"
                                        + "bbbbbaaaabbaabbbaaabbaaaabaabbaabbbbbabb\n"
                                        + "bbaaabaabbbbbbbbabbbbbaa\n"
                                        + "baabbbbaaababbababbaaabb\n"
                                        + "aaaababbbbaababaabbbbbbbaababbbb\n"
                                        + "aaaaabababaaaababbbaaaaa\n"
                                        + "abbbaabbbababbaaabaaabaa\n"
                                        + "bbbbbababbbbaabbaabaaaba\n"
                                        + "aabbbabbbbbababbaaaabbba\n"
                                        + "aabaaaaabbaaaabababaabab\n"
                                        + "bbbbbaaabbbabbabaabaaaab\n"
                                        + "bbbabbbaaabbbabbaabaaabbbbabbababbabaabbbbababab\n"
                                        + "abaababbabaabbaaaabbbbbababbbbaaababaaaabbbbabba\n"
                                        + "abaababbbbbababbabaaaabbababababaaabaaab\n"
                                        + "baaabbabaabbbabbaaaabbabbabababbbbbabaabaababbbbbababbba\n"
                                        + "bababbabbbbbbbaaaabbbabaabaaababbbbaaaaa\n"
                                        + "baabaaabaaabaaaabbaaaabb\n"
                                        + "bbbabbbbbabbbbbaababbaab\n"
                                        + "bbaaaabaaabaababbaaaaabbbbaaaabb\n"
                                        + "abbabbaabaaaaaabbaababaa\n"
                                        + "aaaaaaaaabaaaaabaaaabbabaabababa\n"
                                        + "bbbbaabaabbabbaabaabaabb\n"
                                        + "bbbbabbababaabbbabaaabbb\n"
                                        + "aaabaabbaabbaaaabbbaaaaa\n"
                                        + "abbabaaababababbbbbbaabaabbbaabbaaabaaaaaabbabaaabaabaaa\n"
                                        + "baaaabbbbabaaabaabaababbabaaaaaaabbabaaabbabbaab\n"
                                        + "abbbaabababbbaaababbbbaaabaabbbbbaaaaaababbabaaaabbbbbaabbbabababbabbaaa\n"
                                        + "aaaaaaaaaabbbaaabbabbaab\n"
                                        + "bbabbbaabbabbbbabbaababaaaabbabaaaabaaba\n"
                                        + "abbaaaaabbaaaaabbbaababbaabbbababababbbabbabbbbabbbaaaabaabaabab\n"
                                        + "bbbabaabaaabbaaabaabaaabbaabbbbb\n"
                                        + "aaabbaaabbabababababbaabbabaaaaabbbaabbbbabaabab\n"
                                        + "abaabbbbabbbbaaabaaaabab\n"
                                        + "abbaababbbbababbababaaaa\n"
                                        + "bbbbbaabbbabbabaababaaaa\n"
                                        + "bbbaabbaabbbbbabaabbbabbabbbaababaababbbaaaaabbbbaaaaaba\n"
                                        + "aabbbabbbaabbaaaaabbaabb\n"
                                        + "aaabbaaaabaaaabaabbbabab\n"
                                        + "bbbbaababbbbbaabaaaaababbabbbaababbabaab\n"
                                        + "baabbbbabaabbaabbabaabaaabaabbabaaabaaaaababbbabaababaaa\n"
                                        + "bbbbaaaabbbabbbbabbbbbaa\n"
                                        + "abaababbbbbbababbababababaabaaababbbbbaa\n"
                                        + "aaabaaaabbaabaaaabbbabaa\n"
                                        + "bbbabbabaabbababbaabbbaababbaaaaabbabaab\n"
                                        + "aabaaabbabbbbabaabaabaaa\n"
                                        + "bbbbaabbabababbbaaaaaababababaaabbbababa\n"
                                        + "bbbabbbabbabaabbaaabbbbb\n"
                                        + "abaaabbabaaababbaaabbbab\n"
                                        + "bbbbabaabaaabbbbaaaabbabbbaaabaababbbaab\n"
                                        + "abbaaaabaababbabaabaababbbabbaab\n"
                                        + "aabbabbaaaabbbbababaaaab\n"
                                        + "abbbabbaabbbbababbbbbaabbababbabaaabaaabababbbab\n"
                                        + "bbabaabaabaaaabababbbbbb\n"
                                        + "bbbbbbbbaaababbaabbbaaab\n"
                                        + "bbaabbababbbbaaabbaaaabb\n"
                                        + "babbabbbbaabbabbababaaba\n"
                                        + "baaabaabaaabbbbaababbbbaaaabbbaaaaabbbaabbbababaaabbbaab\n"
                                        + "aaaaabababbabaaabaaabbbaabababababaabbba\n"
                                        + "baaaabbbaaabbaaabaababbabababbababbabbaabaababbaaaabbabaaababaaa\n"
                                        + "babbbaaaabbaabbbbabbbbbb\n"
                                        + "bbbbbaaabbaabbbabaaaabba\n"
                                        + "abbbabaabbbbabbaabaabaaabaaaabbabbbaaaabbbaabbabababbaabbaaaabaa\n"
                                        + "babbababaababbababbababa\n"
                                        + "abaabbbbabbaabababbaaaaa\n"
                                        + "bbbabbaaaaabababbbaabbaabbababaabbbabaaa\n"
                                        + "abaaaabaababbbbbaabaaaaabbbabbbabbababab\n"
                                        + "aababbababbaabbbbbbbbabb\n"
                                        + "bbababbbaabaaaaabbababbabababbabbbabbaaa\n"
                                        + "abbbbabbbababbbaaaaabbabbbabbbabaaabbbaabbbaabbaaaaaabba\n"
                                        + "ababaaabababbbbaaaaabbababbbbaab\n"
                                        + "baabbbbabaaabaaaabaababaaaabbaba\n"
                                        + "baababbabbbbbabbbaabaabb\n"
                                        + "bbbababbbababbaaaabaabbbbbbbbabaabbaaabb\n"
                                        + "baabaabaababbaaaababaaabbbbbbbba\n"
                                        + "babbaababbbbababbaabaabb\n"
                                        + "aabbbabaaabbaaaaabbaaabababaabba\n"
                                        + "bababbbbbaabaaabbbaababa\n"
                                        + "bbbababbbaabbabbabbbaabaabababaa\n"
                                        + "bababbaaaabaabbbbbbbaaab\n"
                                        + "bababbabaabbaaaabbbaaaba\n"
                                        + "baabbaabaabaabababaaaaaababaabab\n"
                                        + "baabaaabbbaabaaabbbbbbab\n"
                                        + "abbbbbbabbaabbbabbaabbbaabbaabbababbaabb\n"
                                        + "babbbaaaabaabbbbaabbaabb\n"
                                        + "baabbbababbbababbabaaaaabbababab\n"
                                        + "babababbaaabababbbbababbaaaababa\n"
                                        + "abbbbaaaaabbabbaabbaaaaa\n"
                                        + "bbbbabaababbbbaaaaaaaaab\n"
                                        + "abbabbaabbbbaabbbabaabbbbaaabaaaaaaabaabbbbbbbaa\n"
                                        + "bababbbbbbababaaaabaabba\n"
                                        + "bbbbbaabbbabaababaaaabab\n"
                                        + "aaabaabbbbaababbaababbbaabbbbbbabababbab\n"
                                        + "aaaaaaaaabaababbbbabbaab\n"
                                        + "abababbbabbabaaabaaabbaabbaaaabb\n"
                                        + "babbbaaabaabaaaaabbbaabaabbbbbbaaaabbabbabbbabab\n"
                                        + "babbabbbbbbbaabbaaaabaaa\n"
                                        + "baabbbbaabbbabbabbaabaab\n"
                                        + "bbbbabbabbababbabbbabbabbabbbaaaaaaabbabaaaaaabb\n"
                                        + "abbaabbbababbaaabaaaabaa\n"
                                        + "babbbaaababababbbaabbbbb\n"
                                        + "bababbaaaaababbaaabbaabb\n"
                                        + "bbbbabbbbbaabbaaabbbabbabababbbbbababbabbabbabba\n"
                                        + "abbabaaabbaabbaababbbbaaaaababbaabbababb\n"
                                        + "baababbabbbbababbbbabbabbbbbbaaaabbaabba\n"
                                        + "babbbbbaabbabbbbabbaabba\n"
                                        + "baaaabbbabaabbbbbaaaaabbbbbabbabaaaabbbabbaaabab\n"
                                        + "abbabbbbbbbaababababaaaa\n"
                                        + "baaabaabbbbbababbabaabbbbbbbbbbabbabbaab\n"
                                        + "bbbbbaabbabaaabaaababbabbabbbbabaabaabaa\n"
                                        + "bbaaaaababbbbabababbabbbaaababbb\n"
                                        + "aababbbaabbbaabbabaababababaaaab\n"
                                        + "bbbabbbbaaaaababaabbbbba\n"
                                        + "bbabaabaabbbabbabbbbbaabbbbbabababaaaababbbaaaabbbbbbabb\n"
                                        + "bbbbbabaabbbbababbababab\n"
                                        + "bbbaabbaabbbbbbabbbabbbaabbbbaaaabababab\n"
                                        + "baaabaaaabaaaabaaababbaabaabbabbababbbbabbaaabab\n"
                                        + "baaabaaaaaabaaaaabbbbabb\n"
                                        + "abaaaababbabbabaabaaaaaababbaaaaabbbbabb\n"
                                        + "baaabbbababababbaaaabbbb\n"
                                        + "aaabbbaaabaaabbababaabbbbbaabaabbbaaabbb\n"
                                        + "bbbababbaaababababbbbaaaaaabaabbbaabbbbb\n"
                                        + "abaabbbbababbbbaabbaabbbaabaababbbbaaaba\n"
                                        + "aabbbabbabaabababaabaaabbbbabbaaaaabbbbbbaaaabab\n"
                                        + "aaaaabaaabaababababbbbbb\n"
                                        + "bbbbababbaabbbbababababaabbbaaab\n"
                                        + "baaabbbbaaabbaaababbaabb\n"
                                        + "aabbbabbbbbbbaababbabbab\n"
                                        + "babaabaaabbbbbbaabaaaabbbbaabaaaaabbaabaaabbabbb\n"
                                        + "baaaabbbaabaabbbaaaababb\n"
                                        + "aabbababaaabababbabbabbaaabaabaaaababaaa\n"
                                        + "abbbbbabbaabaaababbbaabbabbaabababababbbaaaabbabaabbbbbabbabbbaabbbaaaba\n"
                                        + "baababbaababbaaaaaaabbba\n"
                                        + "bbbbaabbbaaaabbbbaaaaaaa\n"
                                        + "bbbbababaaaaaabaaaababbb\n"
                                        + "aabaaaaabbaaaaabbbbababbbbbaabbabbbbbabb\n"
                                        + "bbbbaababaabbabbabbbaabbbbbbaabaabaabbbbabbababbbbbaaaaa\n"
                                        + "abbaaaabbbabbabaababbaaaaababbabababbbabababbabb\n"
                                        + "bbababbbbaaaabbbabbbbbaa\n"
                                        + "bbaabbaabbbbabaaabbbbaaababababbabbbbbaabbaabaab\n"
                                        + "bbaabbbabbbbbaaaaabbabaabaaabbbbababbbbb\n"
                                        + "baababbabbbababbbbbbbbab\n"
                                        + "abbbbbbaaaabbaaaaaaaabba\n"
                                        + "bbaabbbababbabbaaaaabaab\n"
                                        + "bbbaabaababbbbbabbabbaaa\n"
                                        + "bbababbbabbbaabbbaabbbbb\n"
                                        + "bbaaaabaaaabaaaaaabbabbabaaabbaabbbababa\n"
                                        + "aaabababaaabbbbaabaaabbb\n"
                                        + "bbaababbaabbabbabaababbb\n"
                                        + "babbbabbaabbabbaaaabbaaabbbaabaababaaabbaabbbbabbbaaaabb\n"
                                        + "babbbbababbbaababaababbb\n"
                                        + "bbbbabbabababababbbbaabaaabaabbbabbaabbbbbaabbaabbabaaaabbbaaaba\n"
                                        + "aabaaaaaabbaaaabbbbababbbbaaabaabbaabbabbbabbbaa\n"
                                        + "bababbaabaaabaaabababbbbbbaaabbbabbababa\n"
                                        + "aaabbbbaaaaaaaaabbbaaabb\n"
                                        + "bbbbabbabbbbaabbbaaabbaabbbaaaabbaaaabab\n"
                                        + "babaabaabaaaabbbbaaaabba\n"
                                        + "abbbaabbbabbabbbbaaabaaaabbabbaabbbaaabb\n"
                                        + "bbbbaabbaababbabaaabbaaaabaabbaaabbabbab\n"
                                        + "abbbbaaaabbbaabaabaaaaaabbaaaabaaabababa\n"
                                        + "baaabaaaabaaaaababbabbbbbababbba\n"
                                        + "baabaaaabbaaaaabaaababbaababaabbaabaabaa\n"
                                        + "baaababbbaabbaababbbabaa\n"
                                        + "babbbbaaaaababbababbbbbb\n"
                                        + "bbaabaaaaabbabbabaaaabbbaabaaabbbbabaaaaabbababa\n"
                                        + "baabbbaaaabbaaaabbaaaabb\n"
                                        + "baabbbbabaabaaabaabaabaa\n"
                                        + "bbbabbbbbbbabbaaababaaababbabaab\n"
                                        + "aaaaaabaaabbbbaaabaaabaa\n"
                                        + "ababbbbaabbaababaababbbb\n"
                                        + "abaaaaababbbbbabbbbbbbba\n"
                                        + "aababbbabbaaaaababbbbbaabbabaaabaaababaa\n"
                                        + "aaabaaaaabbbabbaabaaabbb\n"
                                        + "bbaababbbbbbaabaabbaaaaa\n"
                                        + "bbababbbbababbaabaaabbbbabaaaaababbbbaabaaaabbba\n"
                                        + "abbabaaabbaabaaaababaaaa\n"
                                        + "aaabaabbabaaaababaaabaaaaabbbabbbabbbbabbbabbababaabbbbbaababababababaab\n"
                                        + "abaabababbababbbbbbaaaba\n"
                                        + "abbbbababbaabbbaaaababaa\n"
                                        + "aaaaabaaaababbbaaaaabbba\n"
                                        + "abbaababbbbabaababaababbbbabaabbbbbbbbaa\n"
                                        + "abbbaaaabbbbabbabbaaaaaabaaabaababbaaabbababaaaaaabbaaabbbabbaaaaababababababbbbbaaaabab\n"
                                        + "ababbaaababaabbbbabaaababbbaabbb\n"
                                        + "bbbaabbabbbaabaaaabbbbaaaaaaabaaaababbabbbabbbbaabaabbaabbbababa\n"
                                        + "bbbbaabbabbbbabababaaaab\n"
                                        + "aaabbaaaaabaaaaababbbbbabbabbbab\n"
                                        + "bbbbaaaaabbbbbbabbaababa\n"
                                        + "abaaaabbbbababbabaaaabbbbabbbbbabbababaabbabbbabaabaabbabababbba\n"
                                        + "baaabbbabbbabbaabbabaaab\n"
                                        + "aaababababaabbbbbabaaaab\n"
                                        + "bbaaabaaaabaabbbbabbbabababaaaaa\n"
                                        + "abababaaaabbbbaabbabbbaababbbbaaaaaaaabbabababbbbaaaabaa\n"
                                        + "baabbbbabaababbabbabbbba\n"
                                        + "baabbbaaaabaabbbabababab\n"
                                        + "abaababbbbbababbaababbabababbbab\n"
                                        + "baaabaabbabababaaaaaaaaaabbabbbbbaaaabba\n"
                                        + "baaaaabbbaaabbbababaaaaa\n"
                                        + "baabbaaabbaabbabbabbbbbb\n"
                                        + "babbababaaabababaabbaabb\n"
                                        + "bbbabbbbaabbabbabbbaaaaa\n"
                                        + "bbbabbabababbaaabbbaaabb\n"
                                        + "aaabababababbaaabbabababbaaabbabaaaaabbbbabbbbaaaaabbaab\n"
                                        + "aabbbbaabaaaabbbbbabbbaa\n"
                                        + "bbaabbaaaaaaaababbaabbaabbaabaaabaaaaaaaababbaab\n"
                                        + "bababbaabbaaaaabbabaabbaababababaaaaababaabbaabbbbabaaabbaaaabbabaabbbbaabbabbbb\n"
                                        + "baabaababbbbaaaababbbbbb\n"
                                        + "baaabbaaabbbaabaaaaaabaabbbabbababbaabbbaaabaaaaaaaabababbbaabbbbbbaaaabababbabbbababaab\n"
                                        + "aaababbabbaabaaaaabaaaab\n"
                                        + "bbbabbabbbbbababaabbabbababababbaababbbaaababaaa\n"
                                        + "babbbabbbbaaaaabbbaaabaabbbaaaaa\n"
                                        + "bbaaabbabbaaabaaaaaabaab\n"
                                        + "bababbbbbaabbaaabaaabaaabababbabbaabaabaabaaabaa\n"
                                        + "bbbbbabababbbbaaaaabababaaaabbabaabbbbab\n"
                                        + "bbbbaaaaaababbbaabaaaabbaabbaabb\n"
                                        + "babaabaabbaaaaabbaabaabababbbbbaababbaaabaaaabbbbbbbbbabaabaabaa\n"
                                        + "babbbabaaaaaaaaaaababaaa\n"
                                        + "bababbabbabbbbbaaaababbb\n"
                                        + "abbaaababbaaaababaaababa\n"
                                        + "bababbaabaaababbbbbbaaaabbbaabababbabbba\n"
                                        + "baaabbbbaabbbaaaaaaabbababaaaaaaabbabbababbbaaaaababaabb\n"
                                        + "babbbabbbbababbaabbbaaaabaaabbbabbababbabbbbbaabaaaaababaaabaaaa\n"
                                        + "ababbbbbbbbbabbaaabaabaa\n"
                                        + "bababbaababbbbaaaaababababaaaaabbbaaabbb\n"
                                        + "bbbbbaabbbaabbaaaaabababbaababab\n"
                                        + "aabaaabbabbabbbbaabaaaaaaaabbbbb\n"
                                        + "bbaabbabbbbbabbaababaaba\n"
                                        + "aaabbbbaaabbabbababaabbbaabbababbabbaaabaabbbbba\n"
                                        + "babbbbabaaaabbabbbbbbabb\n"
                                        + "babbbabaaabaaaaaaabbbbaababbaabaaababaababbaaaaa\n"
                                        + "aaabaaaaaabbabbaaabbbabaabbaaabaabbaaaaa\n"
                                        + "babababbbbbbabaaabbbbbbaababaaaaaabaabaa\n"
                                        + "aabbabbababbbaaabbbaabbb\n"
                                        + "aabbaaaaabbaaaaaaaabbbaaaaababbbbbbabbabbbbabaabababaaaaababbbaaaabbbaab\n"
                                        + "bbbabbaabbbbaaaaabaabbba\n"
                                        + "babbbabbaabaabbbaabbabbb\n"
                                        + "abaaabbabaaaabbbaaaaabaaababaaabbabbbabaabaaabababababab\n"
                                        + "aabbaaaabbbbbaaababbaabababbaababbaaaabaabbabbbaabbaaabbbbabababbaaaaaaa\n"
                                        + "bbbbbbbbbbaaaababbbbbabbaaabaaababbbababaaabaaba\n"
                                        + "aabbbababaabbaaaabbaabba\n"
                                        + "bbbbbaabbbbaabbabbbbbababaabbbbbaaaaabba\n"
                                        + "abbabababbbabaababaaaabbbbbaaabbbaabababbbaabbbabbaabababbabbbba\n"
                                        + "aabbbabbababbbbbaaabbbab\n"
                                        + "bbbbbaaabbbababbbbbabbbaaaabbababbabbbaa\n"
                                        + "bbbabaababbaabbbabbbbabb\n"
                                        + "bbaabbbaaabbababbababaaa\n"
                                        + "abbabbbbbbaaabbaabbbabbb\n"
                                        + "abbbbaaaaabbaabaabbaabba\n"
                                        + "bbababaabbbabaabaababaabbbaaaaabaababbaababbaabbaaabbbabbabaaaaa\n"
                                        + "baaabbaabbbabbabbaabaabb\n"
                                        + "bbbabbbbabbbbabaababaaababbabbbabbababab\n"
                                        + "bbbbbaaababaaabaaabbbababbababababbaabba\n"
                                        + "baabbaababbbabbabaabbabbabbbabaaaaabbabb\n"
                                        + "bbbbbaaabbbabbaabbabbaab\n"
                                        + "babbbababbaaaaabbabbbbbb\n"
                                        + "abaaaabaaaababbaaabababa\n"
                                        + "bbbababaaaabbbbabbbbabbaaabbaaaababbaaaababbaaaaabbaaaaa\n"
                                        + "abbabbaaaaaabbabbbaaabab\n"
                                        + "bbbaabababaabbbbbabaabab\n"
                                        + "babbbaaaababbbbbbaaaabba\n"
                                        + "bbaababbbbbbababbbaabbbb\n"
                                        + "aabbbbaabaaabbbbababbaaabaaabbababbabbbbbbabaaaa\n"
                                        + "bbababbabababbaabbaaabbaabaaabbabaaabbaaaaaabaaaababaaaaabbbbbaabbabaaaaaabbabaaaaaabaab\n"
                                        + "baaabbbbbabbaababbbaaaaabbbaaabaabbaababbaababbbbbbbbbbaaabbabbaabbaabbaaababbbaaaaabbabbbbbaaba\n"
                                        + "aaaaaaaabaaaaabbbaabbaba\n"
                                        + "baaaabbbbaabaaaababaaaaa\n"
                                        + "baaaabbbbaaaaaabaaabbbbabbabaabaababbabaaaaabaabababbbaa\n"
                                        + "bbbbabbbabaaaabaabbabbaaabaabaaa\n"
                                        + "baaabbaababbbbbaaabbaabaaabaaabbabaabaaabbabababababaaba\n"
                                        + "bbaaaababaabaabaaaabbbaaaabbaaaabbbbbabb\n"
                                        + "bbbbabbbbbababbbbbabaaab\n"
                                        + "bababababbbbaababaababbaababbbbbaabaabba\n"
                                        + "bbaabbbaaaaaaababababbba\n"
                                        + "bbbbaabaabaaaababbabbabb\n"
                                        + "bbbaabbaabbbbaaaababbabb\n"
                                        + "abbaaaabbaabbabbaabbbbaabaabbaba\n"
                                        + "abbbbbbabaaaaababbaaabababbbbabbaabbbbba\n"
                                        + "babbabbabbbaabaabbbaabaabbaaaaaababbbbbb\n"
                                        + "abbaaaabababbaaaaaabbbbb\n"
                                        + "bbaaaababbaaabbaabbbbbbaabbaaaabbbabbaabababbbaabaabbbbb\n"
                                        + "aababaabababbabbaaabbaababaabbbabaaaabbaabbaaabbbbbbaabbaaababbabababbaaaaabaaba\n"
                                        + "bbbbaabbbbaabbaaaaababbaabbbaabbbbbabaaa\n"
                                        + "abbbbababbbaababbabbbaaabaabbaabbbbaaabb\n"
                                        + "aaaaababbaaabbabaabaabaaaaabaabaabbbabaaabbbabaababaabaa\n"
                                        + "aabbbbbbabaabaababaaababbabbbabbababaabaaaabbabb\n"
                                        + "bbaabaaabaaababbaaaaabababbaabbbaaababbbbababaaa\n"
                                        + "bbabaaabbabbbabaabaaaaaababbbababaaaaaaaaaaabbabbabaabbabbbaaaabaaaababb\n"
                                        + "baaaabbbbaaabbabbabbbbbabaaababbaabbbabbaaabbbabbbabbbbbaabaabaa\n"
                                        + "babbaabababbbaaabaababbaababbabbbbbabaaabbabaaababbbabbbbbbababaabbaaaaa\n"
                                        + "abaabbababaabbabaaaabaaa\n"
                                        + "bbababbaabbaaababaabbaba\n"
                                        + "baaabbaaaabbababbaabaabb\n"
                                        + "aabbbbaabababbabbbabaabaaaaaaabb\n"
                                        + "bbbabbaabbbbaabaaabababb\n"
                                        + "aaabbbbabababbaabaaaabab\n"
                                        + "abababbbbbabaabbbbbaabbabbabbaabbbaaaabb\n"
                                        + "aaaaaaaaabbaaabaabbaaabb\n"
                                        + "babbabbaabbbaababbabbbba\n"
                                        + "aaaaaabaaabaaabbbabababbbbabbabb\n"
                                        + "babaaabbbbbabaaababbabaabaaaabab\n"
                                        + "aaababbbababbbaaababbaabbbbbababaababbbaaabaabbabaababbbbbaabbbbbabaaabababbbbaaaaaabbabbbababaa\n"
                                        + "abaababbaabbaaaaabbbaaaa\n"
                                        + "abbaaaababbabaaabbaabbabbaabbbaabaababaa\n"
                                        + "aaaaabaaaabbaaaaabababaa\n"
                                        + "baaaaaababaaaabaababbaaaaaabbbabbaababababaaabaaabbbbabbaabaaabb\n"
                                        + "bbbbabaabbbbbaabbabbaabaabbaaabbbbabaaaababbbaab\n"
                                        + "abbabbbbabbabaaaabbabbba\n"
                                        + "baaabbbbbabbababaaaabbbb\n"
                                        + "abaabababaaabbaaaaabaabbabaaaaabbabbababbbaababa\n"
                                        + "abaaaabaaababaabbabbbbaabaabaabaaaabaaaababaaabbaabbbaabbbbaabbb\n"
                                        + "bbaaabbabbbababbbaaabbaaaaababbb\n"
                                        + "bbaaabbabaabaaaabbabbabaaaaaaaaaabbaaaabbbabaabaababbababbbbbbba\n"
                                        + "aababbbabbababbbabaabbba\n"
                                        + "aabbbabbbaaabbabbbbbbbbbbbbabaababbaababababbbaaabbaabaa\n"
                                        + "aaaaaaaaabaaaaaabbbabbaababbbaaaaaabaaab\n"
                                        + "bbaaabaabbabbabaabbabbaaababbaab\n"
                                        + "abaaabbaaaabbaaaabaabababbbbbbaaaaabbbbb\n"
                                        + "baabbaababaababaaabaaabbabaaabaa\n"
                                        + "bbbabbbabbababbbaaababaa\n"
                                        + "bbabaabbbbbbaababbabbbbb\n"
                                        + "abbbbababbbabbaaabbbabab\n"
                                        + "baaabbbababaabbbbbabbaab\n"
                                        + "aaaaaaaaaabaaabbababaabb\n"
                                        + "bababbaaabbaabbbaabbaaab\n"
                                        + "babbaababbaaaabaabaababbaaaabaaa\n"
                                        + "bbbabbabaabaaabbaaaabbabababbaaaabaaabbb\n"
                                        + "aabaaaaababaabaaaaaababb\n"
                                        + "aabbabababbaababaaaababb\n"
                                        + "bbbbabbabbbaabbabababbbbbbaaaabababaabbaaaabbbbbaabbbbba\n"
                                        + "ababaaabababbbbaabbaaabbabbbbaaaaabbbaabbbabbabaabaabaab\n"
                                        + "aabbababbabbabbbaaabbaba\n"
                                        + "abaabbabbaabaaaabbbaaabb\n"
                                        + "babaaabaaabbaababbbabaaa\n"
                                        + "bababbabbaabbabbaabbaaaaaabaaabbabbabbbbaaabbaba\n"
                                        + "babbabbaabaabbabaababbbb\n"
                                        + "babbbbaaabaaabbabbaabbbabbbbabbbbbabaababbbbaaababaabaaabbabbbaaaaaabaab\n"
                                        + "baabbaabbbbbbaaabbabbbbb\n"
                                        + "bbbababbbaabbbaabaabbbbabbababbbbaaaaabbaabbbaab\n"
                                        + "aabbaaaaabbabbaaababbbbbbaabbbbaaaaabbbbbbababab\n"
                                        + "baabbabbaaabbbaabbbbabababbaaabb\n"
                                        + "babbabbbbbaaaaabbbaaaaaaaaaabaaabaaaaaaaaabbbbbbbaaaabbbababaabbaabbbaaa\n"
                                        + "bbbaabbabbabaabaabaabbaa\n"
                                        + "abbaaaabbbbabbabbaabaaaaabaaaaabbbbabbabbaababaaabaabbbaaabbabbb\n"
                                        + "bbbabaabbbbaababaaababaa\n"
                                        + "aabaabbbbaabaabbbabaaaaaabbbbbbb\n"
                                        + "aaabaaaabaaabbaabbaabbbaabababab\n"
                                        + "abbaaabaabaaaabaabbbbbab\n"
                                        + "aaaaabaabaaabbaaababaabaaaaaabbabbaaabbbaaaaaababbbbaabbbaabaabababbbaababababab\n"
                                        + "bbbbaaaabbbaabaaaabaaabbababbaaaaaaabbbababaaaabbbbaaaab\n"
                                        + "bbbabaabbbaaaaabbabbaaab\n"
                                        + "abbaaaabaaaaaabaaabbbbaaabbbbaababaabbba\n"
                                        + "baabbaaaaaabbaaabaababbb\n"
                                        + "aaabaabbbabbaabababaabbbaabbaababaabaaababaaabbb\n"
                                        + "bbabaababbbabbabaabbaaab\n"
                                        + "bbaaaaabbbaabaaaaaabbaaa\n"
                                        + "bbbbbaaabbbabaabbaababbabaaaabbaabbababa\n"
                                        + "aabbbbaabbaaabaababbbbbababbbbbaabbaabbbbaaaabbbababbaab\n"
                                        + "aabbbabbaaabbaaabaababbaabaaaaaaababaaabaaabbbbaaabaaabaaaabbaabababaaaabaaabababbbaaaab\n"
                                        + "aaabaaaabbbbabaaababbbbbabbaaaaa\n"
                                        + "abaabbbbabbaaabaaaaaabaabbbbbbaa\n"
                                        + "bbaaabaaaaaabbabaabbbbab\n"
                                        + "baaaaaabaaababbabbbbaaab\n"
                                        + "bbabaabbbabbbaaaaabbabbaaabbaababbabaabbaaabaaaaaaabaaba\n"
                                        + "abbbbbaabaabbbabbabbaaaabaaaaaba\n"
                                        + "aaabbaaabbbbaaaababaabbbbbbabbbaaabaaabbbaabbabaaabbaaab\n"
                                        + "babbaababbbbaaaabbbbaabaaabbbbaaabbabbba\n"
                                        + "baababbabbaaaaabbbababaabbabbaaa\n"
                                        + "aabbababbbaaaabaabbabaaabbbbbaaabaaabbbaabbbabab\n"
                                        + "abbbaabaabaabaababababbaabbbbaabbbabbaabbaabbaaa\n"
                                        + "baaabaaabaaabaaabaaaaaba\n"
                                        + "bbbabaabaabbbabbbbabbaaa\n"
                                        + "bbaaabaabbbbaaaabbabbabaabbababb\n"
                                        + "abababbbabaaabbabaaaabbbaaaabbabbaababbabbaabbbb\n"
                                        + "bbbbbaababbaaaabbaaabaababbbaaab\n"
                                        + "baabbabbbbaaaababaabbaaabaababaabaaaabab\n"
                                        + "baababbaabbbbbbaaabbabbabbbbababbabbbbbbaabbaabb\n"
                                        + "baabaaaabaaabbbaabababbbaaabbaba\n"
                                        + "abaabbabbaabbaaaaaabaaababbaabaabbbaaaaa\n"
                                        + "baabaaaaabbaabbbabaabbba\n"
                                        + "bbbaabbababbaabaaaaaaabb\n"
                                        + "bbbbabaababaabbbbbababaabaaabaabaaaabbaa\n"
                                        + "aabaababbaabbbbababbaabababaabaabaabbaaaabababab\n"
                                        + "abaaaaabbbbaabaabaabbaba\n"
                                        + "bbbbaabbbaabaaabaabbaababaabbabbbabaaaaaaaabaaba\n"
                                        + "aabbabbaabaaaaaabbabaababbbaabaababaaabb\n"
                                        + "abaaaababbbaabaaaabaaaaabaabaaaabaaabaaaaaaabaab\n"
                                        + "aaaaaabaaabbbababbbbbababbbbababaabbbaab\n"
                                        + "bbbabbababbaabbbabababaa\n"
                                        + "baabbbaaaababbbabbbaaaba\n"
                                        + "baaaaaabaabbbabbbaaaaaabababaaba\n"
                                        + "bbbbaaaaabbbabbabbbbaabaaaaaababbbaabbbb\n"
                                        + "aaabababbaabbaaaaabbbbab\n"
                                        + "abbbbaaabbaabbababaaabbabaaaabba\n"
                                        + "bbaaaababaaabbaaabbbaaaa\n"
                                        + "ababbbbbaaaaaabaabbabbbbaaabbbbbabababaa\n"
                                        + "bbabaabaabbabaaabbbaabbb\n"
                                        + "aababbbaabbbabbabaaabbbbbbabaabaabbbbaaaabaabbaabababaab\n"
                                        + "aababbabbabbabbaabaaaaaabbbababbabbabbbbabbaabba\n"
                                        + "aabbbbbababaaababbaaabaababababbbabbaaabaaabbbaabbbabbab\n"
                                        + "ababbbabbabaaabaabaabaaababaaaaa\n"
                                        + "abbbbbbabbbaabbaabbabaaabbbbabaaabbbbbaa\n"
                                        + "bbaaaaabaabbaabaaabbabaa\n"
                                        + "bbbbaabbabbbaababbaababa\n"
                                        + "babababbababbbbabbabbaaa\n"
                                        + "aabaabbbaaabbbaabbbbabaaabbababa\n"
                                        + "abbbbbabaaabbaaaaabbbabaabbbbaaabbbaaabbbaaababa\n"
                                        + "baabbaaaaaabaabbbaabbbaaaaabbbaaaabbaababaaaabbbaaaabbba\n"
                                        + "abaaabbaababbaaababbaabaaaaaabababaabaab\n"
                                        + "bbbabbabaababbbabaababaa\n"
                                        + "bbaabbabbbbaabbabbbbaaab\n"
                                        + "abbbbabababbbabbbbbbabbbbbabaaaaabbaaabb\n"
                                        + "aabaabbbbbbbaabbabbabbbbaabaabbbbaabbaaaabaabbabaaaababbabbabbab\n"
                                        + "aabaaaaabaaabaabbbabbaabaababbabbbaababababbbbab\n"
                                        + "baabaabaabbaababababaaba\n"
                                        + "aabaaaaaabbbbbabbaabaabb\n"
                                        + "aabaaabbaaabbbbaaaaaaaaabaaaaaba\n"
                                        + "babbbabbbbbbabbaaaabbaaabababbbbabbbaabbbaababbabbaabbbbabbbbbaabaaaabba\n"
                                        + "baabaababaaabbbbabbaabba\n"
                                        + "bbababaabbaabbbaabbbaabbababaaabbababbaaabbbaaabbbaabbbb\n"
                                        + "abaaabbabbaaabbaaabaabaa\n"
                                        + "babababbabbabbbbbababbaaaaabaabbaabaabbbabaaabababababaabaababab\n"
                                        + "bbabaabbaababaabbbaabaaaabbbbaabaaaaaabb\n"
                                        + "aababbaaabababbbbababbbbbbbbabbaabbaaaaabaababaa\n"
                                        + "abaabbabbaaabbaabaaabbba\n"
                                        + "bbbbaabaaababbababbbbbaa\n"
                                        + "baaabbbbbbbbbaaabaabbaaabbaabaab\n"
                                        + "aabbbababbababaaabbbaabbbbabaaab\n"
                                        + "bbbaabaaabbbabbaabbbbaaaabbbaabbabababbaabbbababbbaabbbb\n"
                                        + "aababbbabbabaababaaababbaabbbbaabbaabababbaaaabbaababaaa\n"
                                        + "bbaababbbabaabaaaabbbbbb\n"
                                        + "bbbabbbbabbabaaaababbbbabbbabaababaabbbbaababbbbabbbaaababbbabaabbabbbaa\n"
                                        + "bababbbbaabbaaaabbabbbab\n"
                                        + "bbabbabaaabaabbbaabbabaa\n"
                                        + "baabaaaaababbaaabbbbbabb\n"
                                        + "bababababbbbabbaabbaaaabaaabbabb\n"
                                        + "baaaaaababaaaaabbbaaabbb\n"
                                        + "ababbbbababababaabbabbab\n"
                                        + "baabbbaaabbabbbbbbaaaabb\n"
                                        + "bbbabaabbbaabbbabbabbbbb\n"
                                        + "aabaababaaaabbabbabbabaa\n"
                                        + "bbbbbabaabbbaaaabbaababaabaaababbbaabbabaababaaabbbaabaa\n"
                                        + "abbbaababababbbbabababba\n"
                                        + "bababbabbbbbabbabbbaababbaaabbabbabaabbaaabbbaabababbbaa\n"
                                        + "baabbbaabbbabbbbbbaaabab\n"
                                        + "abbbaabbaabaaabbbbbbababbbbbaabbbabaaabbabbbaaababbabbab\n"
                                        + "bbbbaaaaababbbbbaabbabbabbbbbaababbababbbabbaaaabbabaaab\n"
                                        + "bbbabbbbbaabaaababbbbaaaabbbabbbabbbabab\n"
                                        + "abbbaababbbbbbbbaaaabbabbaaabbbb\n"
                                        + "bbbababbaabbbabaabbbabab\n"
                                        + "ababbaaabbaaaaabaaaababa\n"
                                        + "bbbbabbaabaabbbabbabbbbbbbbbabbbaabbbababaaaabbaaaaaaabbbbaaaaaa\n"
                                        + "bbabaabbabababbbaaabbbaabaaabbaaabababbbabbbaaaaaaaabbaa\n"
                                        + "aaaaaaaaaaabbbbaaaabbabbaaaaabba";

}
