package aoc2020;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

public class Day7 {
    public static void main(String[] args) {
//        String input = TEST_INPUT;
        String input = INPUT;
        a(input);
        b(input);
    }


    private static void b(String input) {
    }

    private static void a(String input) {
        Map<String, List<Hold>> map = new HashMap<>();
        for (String line : input.split("\n")) {
            String outer = line.substring(0, line.indexOf(" bags contain"));
            String[] contains = line.substring(line.indexOf("contain") + 8, line.length() - 1).split(", ");
            for (String c : contains) {
                if (c.equals("no other bags")) {
                    map.computeIfAbsent(outer, k -> new ArrayList<>());
                } else {
                    int ix = c.indexOf(" ");
                    int cnt = Integer.parseInt(c.substring(0, ix));
                    String bag = c.substring(ix + 1, c.lastIndexOf(" "));
                    map.computeIfAbsent(outer, k -> new ArrayList<>()).add(new Hold(cnt, bag));
                }
            }
        }
        Set<String> canContain = new HashSet<>();
        for (Entry<String, List<Hold>> e : map.entrySet()) {
            containsShinyGold(map, new HashSet<>(), e.getKey(), canContain);
        }
        canContain.remove("shiny gold");
        System.out.println(canContain.size());

        System.out.println(count(map, "shiny gold") - 1);
    }

    private static int count(Map<String, List<Hold>> map, String bag) {
        int cnt = 1;
        for (Hold hold : map.getOrDefault(bag, Collections.emptyList())) {
            cnt += hold.cnt * count(map, hold.bag);
        }
        return cnt;
    }

    static boolean containsShinyGold(Map<String, List<Hold>> map, Set<String> checked, String bag, Set<String> canContain) {
        if (bag.equals("shiny gold")) {
            return true;
        }
        for (Hold hold : map.getOrDefault(bag, Collections.emptyList())) {
            if (containsShinyGold(map, checked, hold.bag, canContain)) {
                canContain.add(bag);
                return true;
            }
        }
        return false;
    }

    static class Hold {
        final int cnt;
        final String bag;

        Hold(int cnt, String bag) {
            this.cnt = cnt;
            this.bag = bag;
        }
    }

    private static final String TEST_INPUT = "light red bags contain 1 bright white bag, 2 muted yellow bags.\n"
                                             + "dark orange bags contain 3 bright white bags, 4 muted yellow bags.\n"
                                             + "bright white bags contain 1 shiny gold bag.\n"
                                             + "muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.\n"
                                             + "shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.\n"
                                             + "dark olive bags contain 3 faded blue bags, 4 dotted black bags.\n"
                                             + "vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.\n"
                                             + "faded blue bags contain no other bags.\n"
                                             + "dotted black bags contain no other bags.";

    private static final String INPUT = "pale cyan bags contain 2 posh black bags, 4 wavy gold bags, 2 vibrant brown bags.\n"
                                        + "dull lavender bags contain 3 pale tomato bags.\n"
                                        + "light red bags contain 3 wavy teal bags, 3 plaid aqua bags, 4 drab lavender bags, 2 bright coral bags.\n"
                                        + "wavy green bags contain 3 wavy indigo bags.\n"
                                        + "bright blue bags contain 5 vibrant tan bags.\n"
                                        + "dotted fuchsia bags contain 5 dark orange bags, 1 shiny coral bag.\n"
                                        + "pale tomato bags contain 2 bright magenta bags, 5 dull lime bags.\n"
                                        + "light black bags contain 1 posh lavender bag, 5 dotted gold bags, 4 faded bronze bags.\n"
                                        + "wavy turquoise bags contain 4 pale teal bags, 2 dim brown bags, 5 muted lime bags.\n"
                                        + "striped red bags contain 4 faded brown bags, 4 dotted purple bags.\n"
                                        + "wavy silver bags contain 5 muted chartreuse bags, 1 light silver bag, 3 striped silver bags.\n"
                                        + "posh lavender bags contain 5 striped silver bags, 3 wavy beige bags, 3 dim brown bags, 5 clear indigo bags.\n"
                                        + "pale maroon bags contain 1 striped white bag, 4 light blue bags.\n"
                                        + "drab turquoise bags contain 2 shiny tomato bags.\n"
                                        + "dark aqua bags contain 2 plaid silver bags.\n"
                                        + "vibrant coral bags contain 3 wavy lime bags, 2 shiny gold bags, 1 dotted orange bag, 3 muted indigo bags.\n"
                                        + "clear green bags contain 1 clear olive bag.\n"
                                        + "striped indigo bags contain 3 striped turquoise bags.\n"
                                        + "clear lime bags contain 3 mirrored green bags, 2 light tan bags.\n"
                                        + "drab bronze bags contain 5 plaid lavender bags, 1 muted yellow bag, 5 vibrant coral bags.\n"
                                        + "drab lavender bags contain 1 posh tomato bag, 4 muted salmon bags, 4 dull lime bags.\n"
                                        + "striped aqua bags contain 1 pale maroon bag.\n"
                                        + "wavy gray bags contain 3 light tan bags, 2 pale white bags, 2 bright magenta bags, 5 muted salmon bags.\n"
                                        + "faded aqua bags contain 1 plaid salmon bag, 4 dotted yellow bags.\n"
                                        + "drab cyan bags contain 1 posh tomato bag, 4 shiny turquoise bags.\n"
                                        + "vibrant blue bags contain no other bags.\n"
                                        + "light lime bags contain 3 vibrant purple bags.\n"
                                        + "clear gray bags contain 3 mirrored olive bags, 3 clear crimson bags, 5 dark orange bags, 2 dim gold bags.\n"
                                        + "bright magenta bags contain no other bags.\n"
                                        + "wavy purple bags contain 4 dim gold bags, 5 light green bags.\n"
                                        + "muted bronze bags contain 2 pale beige bags, 2 clear turquoise bags, 5 posh white bags, 1 wavy gray bag.\n"
                                        + "striped violet bags contain 1 light gold bag.\n"
                                        + "dull salmon bags contain 2 posh gray bags, 2 dotted blue bags.\n"
                                        + "striped orange bags contain 3 faded coral bags, 3 dotted lavender bags.\n"
                                        + "drab coral bags contain 1 wavy indigo bag, 1 dull black bag, 3 mirrored chartreuse bags.\n"
                                        + "plaid yellow bags contain 5 faded cyan bags.\n"
                                        + "dark maroon bags contain 2 mirrored silver bags, 5 muted salmon bags, 1 dull tomato bag.\n"
                                        + "dark yellow bags contain 1 drab maroon bag, 5 faded cyan bags, 4 clear indigo bags.\n"
                                        + "posh teal bags contain 3 vibrant maroon bags, 3 posh salmon bags.\n"
                                        + "mirrored black bags contain 1 drab fuchsia bag, 2 posh red bags.\n"
                                        + "drab salmon bags contain 2 dull plum bags.\n"
                                        + "muted green bags contain 4 plaid gray bags, 2 dim turquoise bags, 2 dull coral bags, 4 dim white bags.\n"
                                        + "bright indigo bags contain 1 bright turquoise bag, 4 dark beige bags.\n"
                                        + "wavy fuchsia bags contain 1 clear violet bag, 4 striped bronze bags, 1 mirrored indigo bag, 1 shiny cyan bag.\n"
                                        + "bright brown bags contain 5 dark purple bags.\n"
                                        + "dull turquoise bags contain 3 dim yellow bags, 2 dim indigo bags.\n"
                                        + "pale coral bags contain 4 posh indigo bags.\n"
                                        + "striped green bags contain 4 dull green bags, 5 dotted turquoise bags, 3 pale red bags, 2 dark gold bags.\n"
                                        + "faded maroon bags contain 3 dim green bags, 4 wavy purple bags.\n"
                                        + "vibrant lime bags contain 3 shiny fuchsia bags, 1 pale red bag, 1 vibrant bronze bag.\n"
                                        + "shiny plum bags contain 2 bright maroon bags, 5 dull tomato bags, 2 plaid salmon bags, 3 bright lime bags.\n"
                                        + "faded silver bags contain 1 posh turquoise bag, 5 posh white bags, 5 wavy lime bags, 3 shiny coral bags.\n"
                                        + "mirrored tomato bags contain 3 dotted tomato bags, 4 vibrant blue bags, 4 dull yellow bags, 5 clear chartreuse bags.\n"
                                        + "pale red bags contain 5 vibrant indigo bags, 4 vibrant red bags, 3 bright magenta bags, 3 dim indigo bags.\n"
                                        + "drab blue bags contain 2 bright magenta bags.\n"
                                        + "dim purple bags contain 4 drab lavender bags, 4 plaid yellow bags, 5 dull white bags, 3 clear white bags.\n"
                                        + "dim red bags contain 5 striped silver bags, 1 shiny red bag.\n"
                                        + "dim lime bags contain 5 plaid bronze bags, 5 drab salmon bags.\n"
                                        + "mirrored beige bags contain 3 bright tomato bags, 2 dull lime bags.\n"
                                        + "bright lime bags contain 5 clear chartreuse bags.\n"
                                        + "clear chartreuse bags contain 1 muted white bag, 1 vibrant bronze bag, 2 vibrant maroon bags, 4 clear lime bags.\n"
                                        + "dotted indigo bags contain 4 pale olive bags, 1 bright violet bag, 3 drab gray bags.\n"
                                        + "striped crimson bags contain 3 muted salmon bags.\n"
                                        + "plaid green bags contain 3 posh tomato bags.\n"
                                        + "dim brown bags contain 3 striped teal bags, 3 vibrant aqua bags, 3 plaid yellow bags.\n"
                                        + "faded turquoise bags contain 2 dim blue bags, 3 clear green bags, 3 striped bronze bags, 2 dim beige bags.\n"
                                        + "dotted coral bags contain 2 vibrant silver bags, 3 plaid crimson bags, 4 dull silver bags, 1 muted blue bag.\n"
                                        + "mirrored magenta bags contain 3 striped teal bags, 1 mirrored black bag, 4 shiny black bags.\n"
                                        + "shiny gray bags contain 3 bright magenta bags.\n"
                                        + "mirrored violet bags contain 5 drab blue bags, 5 dark brown bags.\n"
                                        + "dark beige bags contain 2 vibrant blue bags, 2 bright magenta bags, 1 dim indigo bag.\n"
                                        + "dark bronze bags contain 3 vibrant chartreuse bags, 2 posh turquoise bags, 4 faded aqua bags.\n"
                                        + "clear turquoise bags contain 1 mirrored green bag, 1 faded indigo bag, 4 shiny aqua bags, 4 dim tomato bags.\n"
                                        + "dark silver bags contain 5 posh purple bags, 4 dull silver bags.\n"
                                        + "dull tan bags contain 2 striped brown bags, 3 vibrant salmon bags, 1 drab gold bag.\n"
                                        + "mirrored gray bags contain 2 dim white bags, 4 muted white bags, 1 muted orange bag, 3 muted magenta bags.\n"
                                        + "faded black bags contain 3 faded aqua bags, 4 drab white bags, 2 dull lavender bags, 1 bright purple bag.\n"
                                        + "light fuchsia bags contain 3 pale magenta bags.\n"
                                        + "wavy lavender bags contain no other bags.\n"
                                        + "dull black bags contain 1 mirrored teal bag.\n"
                                        + "vibrant chartreuse bags contain 1 dull violet bag, 4 posh turquoise bags.\n"
                                        + "posh yellow bags contain 5 wavy gold bags.\n"
                                        + "shiny teal bags contain 2 drab salmon bags, 5 striped crimson bags.\n"
                                        + "plaid fuchsia bags contain 3 dim brown bags, 2 posh bronze bags, 1 striped aqua bag, 1 shiny chartreuse bag.\n"
                                        + "faded yellow bags contain 1 dotted tan bag, 3 dark coral bags.\n"
                                        + "mirrored orange bags contain 3 pale coral bags.\n"
                                        + "wavy indigo bags contain 5 shiny coral bags, 2 shiny yellow bags, 2 striped brown bags.\n"
                                        + "dotted salmon bags contain 1 drab turquoise bag, 1 vibrant lime bag, 3 dull chartreuse bags, 1 vibrant maroon bag.\n"
                                        + "dull magenta bags contain 3 shiny coral bags, 5 dull violet bags, 5 mirrored violet bags.\n"
                                        + "shiny tomato bags contain 1 dim salmon bag, 1 dim olive bag.\n"
                                        + "drab gold bags contain 3 drab maroon bags, 1 dotted black bag, 4 plaid orange bags.\n"
                                        + "bright yellow bags contain 4 muted teal bags, 1 faded maroon bag, 5 posh chartreuse bags, 5 plaid indigo bags.\n"
                                        + "dull plum bags contain 1 shiny salmon bag, 3 light tan bags.\n"
                                        + "posh gray bags contain 3 muted lime bags, 2 dotted green bags.\n"
                                        + "clear violet bags contain 5 vibrant maroon bags.\n"
                                        + "dotted bronze bags contain 3 light tan bags, 4 shiny yellow bags, 3 mirrored brown bags, 1 plaid yellow bag.\n"
                                        + "mirrored lime bags contain 2 bright teal bags, 2 dim gold bags, 2 dull tomato bags, 3 wavy green bags.\n"
                                        + "shiny indigo bags contain 3 dull silver bags, 2 dim cyan bags, 2 striped magenta bags.\n"
                                        + "vibrant crimson bags contain 2 light chartreuse bags.\n"
                                        + "dim magenta bags contain 5 plaid olive bags, 2 muted green bags, 4 bright crimson bags.\n"
                                        + "dim blue bags contain 1 bright silver bag, 2 shiny gray bags.\n"
                                        + "plaid teal bags contain 4 shiny aqua bags, 1 dull fuchsia bag, 4 bright lime bags.\n"
                                        + "dull teal bags contain 2 dotted black bags.\n"
                                        + "plaid gray bags contain 5 muted brown bags.\n"
                                        + "pale teal bags contain 5 striped olive bags, 1 dotted fuchsia bag, 3 dark teal bags, 2 dim purple bags.\n"
                                        + "clear beige bags contain 3 pale lime bags, 4 striped aqua bags, 3 mirrored red bags.\n"
                                        + "mirrored green bags contain 4 mirrored olive bags, 5 dim salmon bags, 4 vibrant bronze bags.\n"
                                        + "plaid aqua bags contain 2 pale white bags, 1 dull plum bag, 4 mirrored olive bags, 3 dim maroon bags.\n"
                                        + "pale aqua bags contain 5 bright salmon bags, 4 vibrant silver bags, 2 light orange bags.\n"
                                        + "plaid crimson bags contain 3 striped magenta bags.\n"
                                        + "mirrored red bags contain 5 dull coral bags, 5 pale yellow bags, 5 drab maroon bags, 2 dim gray bags.\n"
                                        + "pale black bags contain 1 light red bag, 4 faded teal bags.\n"
                                        + "dim turquoise bags contain 5 faded purple bags, 4 wavy fuchsia bags, 3 vibrant purple bags, 2 pale beige bags.\n"
                                        + "dim lavender bags contain 1 light blue bag.\n"
                                        + "pale gray bags contain 3 mirrored red bags, 5 light indigo bags.\n"
                                        + "clear magenta bags contain 5 bright gold bags, 5 dim lavender bags, 1 wavy lavender bag.\n"
                                        + "dull gold bags contain 4 dull fuchsia bags, 3 vibrant tan bags.\n"
                                        + "dim salmon bags contain 5 dull yellow bags, 4 pale beige bags.\n"
                                        + "drab magenta bags contain 2 vibrant salmon bags.\n"
                                        + "vibrant green bags contain 3 bright purple bags, 5 wavy brown bags, 5 dotted gray bags, 1 posh bronze bag.\n"
                                        + "dull brown bags contain 1 wavy tan bag, 1 shiny salmon bag.\n"
                                        + "clear white bags contain 5 bright lime bags, 3 light tan bags.\n"
                                        + "dotted lavender bags contain 5 wavy cyan bags, 2 dark indigo bags, 4 shiny gold bags.\n"
                                        + "dotted purple bags contain 5 dull teal bags, 3 shiny plum bags.\n"
                                        + "drab yellow bags contain 3 faded beige bags, 3 light silver bags.\n"
                                        + "dark orange bags contain 5 bright lime bags.\n"
                                        + "dotted cyan bags contain 1 vibrant lime bag, 1 wavy maroon bag, 2 dull tan bags, 5 shiny salmon bags.\n"
                                        + "posh indigo bags contain 5 dull yellow bags, 1 vibrant bronze bag.\n"
                                        + "dull chartreuse bags contain 2 wavy lavender bags, 5 vibrant blue bags.\n"
                                        + "posh blue bags contain 3 wavy maroon bags.\n"
                                        + "dim teal bags contain 3 muted turquoise bags, 1 vibrant black bag, 5 dotted tomato bags.\n"
                                        + "pale purple bags contain 1 striped olive bag.\n"
                                        + "drab chartreuse bags contain 1 clear orange bag, 2 plaid turquoise bags, 2 drab maroon bags.\n"
                                        + "plaid white bags contain 4 plaid indigo bags, 5 vibrant lime bags.\n"
                                        + "vibrant bronze bags contain 5 vibrant blue bags, 1 drab blue bag, 1 dull lime bag.\n"
                                        + "bright bronze bags contain 3 muted magenta bags, 3 dotted black bags, 1 pale lime bag, 2 dull violet bags.\n"
                                        + "dark indigo bags contain 3 bright maroon bags.\n"
                                        + "muted lavender bags contain 1 light white bag, 2 clear white bags, 2 posh white bags, 3 dim purple bags.\n"
                                        + "vibrant violet bags contain 5 dull magenta bags, 4 posh coral bags.\n"
                                        + "drab beige bags contain 2 plaid magenta bags, 2 muted bronze bags, 2 muted purple bags.\n"
                                        + "drab plum bags contain 4 mirrored tomato bags, 3 light lavender bags, 3 mirrored green bags, 5 muted salmon bags.\n"
                                        + "mirrored fuchsia bags contain 1 mirrored tomato bag, 5 dotted black bags, 2 posh white bags.\n"
                                        + "pale crimson bags contain 4 light plum bags.\n"
                                        + "dotted black bags contain 3 bright maroon bags.\n"
                                        + "wavy tomato bags contain 1 dim black bag, 5 vibrant coral bags, 1 mirrored purple bag.\n"
                                        + "bright aqua bags contain 5 pale lime bags, 3 striped teal bags.\n"
                                        + "vibrant purple bags contain 2 clear turquoise bags, 4 vibrant bronze bags, 1 dark lime bag, 3 clear crimson bags.\n"
                                        + "vibrant tan bags contain 4 posh black bags.\n"
                                        + "plaid turquoise bags contain 2 dotted violet bags, 5 mirrored plum bags.\n"
                                        + "dim violet bags contain 3 dotted orange bags.\n"
                                        + "bright tan bags contain 2 dark indigo bags, 4 faded purple bags, 4 dim blue bags.\n"
                                        + "muted chartreuse bags contain 4 dotted black bags, 5 mirrored tomato bags.\n"
                                        + "muted gold bags contain 2 wavy gray bags, 4 clear gold bags, 1 shiny gold bag.\n"
                                        + "dull indigo bags contain 3 mirrored maroon bags.\n"
                                        + "clear aqua bags contain 4 dim plum bags, 5 bright bronze bags.\n"
                                        + "muted maroon bags contain 1 striped crimson bag, 3 vibrant aqua bags.\n"
                                        + "muted blue bags contain 4 clear magenta bags, 4 pale bronze bags, 2 dull black bags, 4 striped olive bags.\n"
                                        + "drab aqua bags contain 3 faded crimson bags.\n"
                                        + "shiny olive bags contain 4 shiny salmon bags, 2 wavy plum bags, 4 pale bronze bags, 3 posh gold bags.\n"
                                        + "striped bronze bags contain 4 plaid olive bags, 4 plaid indigo bags, 1 pale white bag, 3 striped magenta bags.\n"
                                        + "mirrored gold bags contain 2 faded lavender bags.\n"
                                        + "faded blue bags contain 1 plaid bronze bag, 3 dim olive bags, 2 wavy crimson bags, 4 plaid silver bags.\n"
                                        + "plaid lime bags contain 2 dim yellow bags.\n"
                                        + "mirrored brown bags contain 4 light crimson bags.\n"
                                        + "plaid red bags contain 5 shiny aqua bags, 5 wavy lavender bags, 1 posh beige bag.\n"
                                        + "mirrored coral bags contain 4 mirrored lime bags, 5 muted orange bags, 5 dotted salmon bags, 1 faded purple bag.\n"
                                        + "mirrored olive bags contain 2 vibrant blue bags.\n"
                                        + "pale orange bags contain 4 wavy lime bags.\n"
                                        + "drab maroon bags contain 1 shiny yellow bag, 3 dull yellow bags, 1 wavy lavender bag, 2 dim salmon bags.\n"
                                        + "drab purple bags contain 5 bright tomato bags, 4 striped bronze bags, 2 bright chartreuse bags, 2 dark violet bags.\n"
                                        + "striped lime bags contain 5 posh turquoise bags, 1 dim purple bag.\n"
                                        + "wavy beige bags contain 5 shiny tomato bags, 3 drab lavender bags, 1 shiny orange bag.\n"
                                        + "bright gold bags contain 5 vibrant red bags, 1 shiny orange bag, 3 striped bronze bags.\n"
                                        + "muted magenta bags contain 4 light olive bags, 3 dotted tan bags.\n"
                                        + "dark lime bags contain 5 wavy lavender bags, 4 clear maroon bags, 2 striped beige bags, 4 plaid salmon bags.\n"
                                        + "pale silver bags contain 3 faded lavender bags, 2 dotted purple bags, 3 wavy crimson bags.\n"
                                        + "posh turquoise bags contain 5 dim yellow bags, 4 posh lime bags, 5 shiny orange bags.\n"
                                        + "shiny coral bags contain 2 dull tomato bags.\n"
                                        + "dim tomato bags contain 3 shiny aqua bags, 3 light cyan bags.\n"
                                        + "plaid tomato bags contain 3 faded indigo bags.\n"
                                        + "clear tan bags contain 3 mirrored indigo bags.\n"
                                        + "wavy maroon bags contain 1 dark silver bag.\n"
                                        + "drab teal bags contain 5 muted salmon bags, 4 plaid yellow bags, 4 bright red bags, 2 posh teal bags.\n"
                                        + "dim plum bags contain 5 posh salmon bags, 5 faded purple bags, 2 posh brown bags.\n"
                                        + "bright fuchsia bags contain 2 dark beige bags, 3 faded yellow bags.\n"
                                        + "clear silver bags contain 2 plaid tomato bags, 4 muted chartreuse bags.\n"
                                        + "shiny purple bags contain 5 muted lavender bags, 2 clear turquoise bags, 4 muted teal bags.\n"
                                        + "dark red bags contain 3 plaid plum bags, 2 dim indigo bags, 2 wavy gray bags.\n"
                                        + "dark white bags contain 4 muted bronze bags, 5 mirrored gold bags, 3 plaid lavender bags.\n"
                                        + "drab silver bags contain 1 dark gold bag, 3 muted white bags.\n"
                                        + "dark green bags contain 3 posh turquoise bags.\n"
                                        + "striped white bags contain 1 vibrant maroon bag, 1 shiny salmon bag.\n"
                                        + "striped lavender bags contain 1 light tomato bag, 5 light lime bags, 1 posh gold bag.\n"
                                        + "mirrored tan bags contain 2 posh fuchsia bags.\n"
                                        + "pale salmon bags contain 4 shiny blue bags.\n"
                                        + "dark black bags contain 1 dotted coral bag, 1 faded crimson bag, 4 drab violet bags, 5 clear chartreuse bags.\n"
                                        + "vibrant red bags contain 1 dim gold bag, 2 dull yellow bags, 1 faded brown bag, 4 light cyan bags.\n"
                                        + "pale turquoise bags contain 5 clear cyan bags.\n"
                                        + "bright olive bags contain 1 clear turquoise bag, 4 bright teal bags, 3 striped maroon bags, 1 striped gold bag.\n"
                                        + "shiny green bags contain 5 dim lime bags, 3 wavy brown bags, 2 faded magenta bags, 5 drab maroon bags.\n"
                                        + "vibrant tomato bags contain 3 striped plum bags, 2 vibrant maroon bags, 4 muted silver bags, 3 striped chartreuse bags.\n"
                                        + "vibrant yellow bags contain 3 pale beige bags, 4 dim orange bags, 4 dotted cyan bags.\n"
                                        + "muted aqua bags contain 3 vibrant purple bags.\n"
                                        + "dull orange bags contain 2 striped gray bags, 3 vibrant bronze bags, 2 bright turquoise bags.\n"
                                        + "wavy cyan bags contain 2 drab maroon bags, 4 shiny aqua bags, 5 clear lime bags.\n"
                                        + "faded tan bags contain 3 muted turquoise bags, 2 plaid purple bags, 3 clear crimson bags.\n"
                                        + "light maroon bags contain 5 wavy chartreuse bags, 3 mirrored silver bags, 5 muted plum bags, 2 mirrored blue bags.\n"
                                        + "shiny lavender bags contain 1 dark silver bag, 5 clear teal bags, 5 dark red bags, 4 faded red bags.\n"
                                        + "striped fuchsia bags contain 4 clear gold bags, 3 bright magenta bags, 3 bright aqua bags.\n"
                                        + "striped plum bags contain 4 bright lime bags, 5 dotted black bags, 5 drab beige bags.\n"
                                        + "dotted red bags contain 4 dim gold bags, 3 dim indigo bags, 4 striped olive bags, 5 dim white bags.\n"
                                        + "mirrored chartreuse bags contain 5 posh tomato bags.\n"
                                        + "dim white bags contain 5 clear maroon bags.\n"
                                        + "muted black bags contain 2 posh turquoise bags, 3 clear lavender bags, 2 shiny aqua bags, 2 pale red bags.\n"
                                        + "muted silver bags contain 4 striped white bags, 5 dotted tomato bags, 4 mirrored fuchsia bags, 2 clear maroon bags.\n"
                                        + "dotted lime bags contain 1 muted aqua bag, 3 mirrored tan bags.\n"
                                        + "faded chartreuse bags contain 4 vibrant violet bags, 5 faded magenta bags, 5 dim teal bags, 2 dim green bags.\n"
                                        + "light turquoise bags contain 1 dotted purple bag.\n"
                                        + "plaid cyan bags contain 1 bright magenta bag, 2 wavy chartreuse bags, 5 vibrant silver bags, 3 pale crimson bags.\n"
                                        + "dull maroon bags contain 5 dim black bags.\n"
                                        + "wavy violet bags contain 1 faded yellow bag.\n"
                                        + "vibrant teal bags contain 5 dim lime bags, 2 vibrant gold bags, 2 dim beige bags.\n"
                                        + "pale fuchsia bags contain 3 striped olive bags.\n"
                                        + "light brown bags contain 3 shiny chartreuse bags, 2 wavy purple bags.\n"
                                        + "dull green bags contain 3 striped orange bags, 2 posh indigo bags, 3 faded blue bags.\n"
                                        + "dark blue bags contain 5 striped magenta bags, 3 striped gray bags, 4 pale coral bags.\n"
                                        + "mirrored lavender bags contain 3 posh black bags.\n"
                                        + "shiny brown bags contain 5 dotted magenta bags, 4 dim chartreuse bags, 1 posh cyan bag.\n"
                                        + "muted brown bags contain 3 dull black bags, 3 pale maroon bags, 5 posh brown bags, 2 striped gray bags.\n"
                                        + "faded orange bags contain 1 dark orange bag.\n"
                                        + "muted fuchsia bags contain 3 plaid salmon bags.\n"
                                        + "clear plum bags contain 3 shiny red bags, 4 dim silver bags.\n"
                                        + "bright coral bags contain 4 pale yellow bags, 2 muted magenta bags, 2 bright chartreuse bags, 3 light olive bags.\n"
                                        + "muted coral bags contain 4 striped green bags.\n"
                                        + "drab olive bags contain 3 shiny salmon bags, 4 clear cyan bags.\n"
                                        + "dim silver bags contain 2 shiny plum bags.\n"
                                        + "wavy plum bags contain 3 mirrored fuchsia bags, 5 pale maroon bags, 5 posh salmon bags.\n"
                                        + "plaid coral bags contain 1 mirrored gold bag.\n"
                                        + "posh beige bags contain 3 mirrored maroon bags, 3 drab chartreuse bags, 3 dark salmon bags, 1 clear green bag.\n"
                                        + "drab green bags contain 1 bright teal bag, 3 muted chartreuse bags.\n"
                                        + "bright crimson bags contain 3 striped orange bags, 4 wavy plum bags.\n"
                                        + "posh chartreuse bags contain 5 clear white bags, 3 light red bags.\n"
                                        + "dim gray bags contain 1 mirrored fuchsia bag, 3 muted teal bags, 4 clear maroon bags, 5 striped white bags.\n"
                                        + "striped brown bags contain 2 muted orange bags.\n"
                                        + "dim tan bags contain 3 clear gold bags, 5 clear salmon bags, 2 dark chartreuse bags.\n"
                                        + "striped magenta bags contain 2 plaid indigo bags, 5 drab lavender bags, 2 dotted fuchsia bags, 4 shiny aqua bags.\n"
                                        + "dotted violet bags contain 3 dull tomato bags.\n"
                                        + "dotted tan bags contain 1 dark orange bag, 2 drab blue bags.\n"
                                        + "shiny beige bags contain 1 drab gold bag.\n"
                                        + "light plum bags contain 5 plaid tomato bags, 5 wavy gray bags, 1 dull tomato bag.\n"
                                        + "muted indigo bags contain 3 dim salmon bags.\n"
                                        + "clear red bags contain 3 mirrored beige bags.\n"
                                        + "mirrored silver bags contain 2 wavy plum bags, 4 vibrant magenta bags.\n"
                                        + "dark lavender bags contain 2 wavy violet bags, 5 muted green bags, 2 dim purple bags.\n"
                                        + "clear teal bags contain 4 wavy crimson bags.\n"
                                        + "light purple bags contain 5 faded black bags.\n"
                                        + "light salmon bags contain 3 vibrant beige bags, 3 striped white bags, 5 pale magenta bags, 5 muted blue bags.\n"
                                        + "dull gray bags contain 5 dim lavender bags.\n"
                                        + "posh aqua bags contain 1 light olive bag, 4 mirrored purple bags, 4 vibrant gold bags, 1 shiny aqua bag.\n"
                                        + "pale chartreuse bags contain 5 faded indigo bags.\n"
                                        + "striped cyan bags contain 1 shiny olive bag, 3 bright tomato bags, 1 faded beige bag.\n"
                                        + "clear coral bags contain 5 clear violet bags, 1 plaid tomato bag.\n"
                                        + "bright cyan bags contain 3 mirrored violet bags, 5 plaid magenta bags, 4 vibrant bronze bags.\n"
                                        + "posh tomato bags contain 3 shiny aqua bags, 1 pale beige bag.\n"
                                        + "bright lavender bags contain 4 clear beige bags, 2 faded lavender bags, 3 faded aqua bags, 5 pale purple bags.\n"
                                        + "dotted teal bags contain 5 plaid salmon bags, 1 posh turquoise bag, 2 muted silver bags.\n"
                                        + "clear tomato bags contain 5 bright indigo bags.\n"
                                        + "dotted silver bags contain 2 mirrored indigo bags.\n"
                                        + "plaid plum bags contain 4 light crimson bags.\n"
                                        + "wavy magenta bags contain 2 posh indigo bags, 2 vibrant indigo bags.\n"
                                        + "dull tomato bags contain 4 dull lime bags, 4 faded brown bags.\n"
                                        + "vibrant black bags contain 5 light crimson bags, 5 pale lavender bags, 3 dull blue bags, 2 pale coral bags.\n"
                                        + "pale bronze bags contain 3 vibrant violet bags.\n"
                                        + "wavy lime bags contain 5 shiny yellow bags, 2 pale white bags, 1 clear gold bag, 5 mirrored chartreuse bags.\n"
                                        + "striped gray bags contain 3 shiny tomato bags, 3 dull coral bags, 1 shiny aqua bag, 2 dark orange bags.\n"
                                        + "faded crimson bags contain 4 pale white bags, 3 muted bronze bags, 2 posh blue bags, 3 bright coral bags.\n"
                                        + "wavy orange bags contain 2 shiny indigo bags.\n"
                                        + "dotted white bags contain 1 striped tan bag, 4 bright silver bags, 1 shiny fuchsia bag, 3 posh gray bags.\n"
                                        + "posh bronze bags contain 4 muted silver bags, 1 light lavender bag.\n"
                                        + "dotted magenta bags contain 5 clear fuchsia bags, 4 faded indigo bags, 3 dull turquoise bags, 4 muted orange bags.\n"
                                        + "dull cyan bags contain 3 clear teal bags, 3 dim white bags, 3 dull tomato bags, 5 vibrant purple bags.\n"
                                        + "clear gold bags contain 4 dim gold bags, 3 dull lime bags, 4 faded brown bags, 4 wavy gray bags.\n"
                                        + "bright beige bags contain 3 dull cyan bags, 4 bright indigo bags, 2 dull lime bags.\n"
                                        + "clear orange bags contain 5 shiny salmon bags.\n"
                                        + "plaid silver bags contain 5 dotted purple bags, 1 dim maroon bag, 3 muted gold bags.\n"
                                        + "shiny white bags contain 1 light brown bag, 1 mirrored lime bag.\n"
                                        + "dark gray bags contain 5 shiny cyan bags, 2 drab tomato bags.\n"
                                        + "drab white bags contain 4 shiny tomato bags, 3 shiny gold bags, 3 dull lime bags, 3 plaid orange bags.\n"
                                        + "vibrant cyan bags contain 2 wavy purple bags, 4 light gold bags, 1 pale indigo bag, 2 striped fuchsia bags.\n"
                                        + "shiny yellow bags contain 4 shiny aqua bags, 2 dim salmon bags, 3 posh tomato bags, 5 muted salmon bags.\n"
                                        + "posh coral bags contain 2 striped gray bags, 4 dark orange bags, 5 posh magenta bags.\n"
                                        + "clear salmon bags contain 4 posh yellow bags, 2 pale violet bags, 3 mirrored violet bags.\n"
                                        + "posh olive bags contain 2 mirrored red bags, 3 faded gold bags.\n"
                                        + "faded fuchsia bags contain 5 bright gold bags, 3 pale tomato bags, 2 dotted bronze bags, 1 mirrored green bag.\n"
                                        + "striped maroon bags contain 4 posh maroon bags, 4 dim indigo bags, 5 shiny aqua bags, 4 posh lime bags.\n"
                                        + "dark violet bags contain 5 plaid tomato bags, 3 bright lime bags, 4 light lavender bags, 4 dark brown bags.\n"
                                        + "dim maroon bags contain 1 dark beige bag, 4 wavy gray bags, 5 shiny coral bags, 1 pale white bag.\n"
                                        + "wavy crimson bags contain 1 light tan bag, 5 dark beige bags.\n"
                                        + "plaid magenta bags contain 1 shiny turquoise bag, 1 dark lime bag, 5 dim salmon bags.\n"
                                        + "clear indigo bags contain 4 muted maroon bags.\n"
                                        + "clear olive bags contain 5 mirrored teal bags, 1 plaid lime bag, 3 dull magenta bags, 5 wavy gray bags.\n"
                                        + "mirrored white bags contain 3 pale gold bags.\n"
                                        + "wavy blue bags contain 1 dotted aqua bag, 5 dark green bags.\n"
                                        + "faded cyan bags contain 4 wavy gray bags, 5 vibrant bronze bags, 1 mirrored olive bag, 3 drab blue bags.\n"
                                        + "faded gray bags contain 2 drab brown bags, 4 dotted coral bags, 5 dim turquoise bags, 1 mirrored maroon bag.\n"
                                        + "dim coral bags contain 5 shiny olive bags, 3 light plum bags.\n"
                                        + "vibrant fuchsia bags contain 5 shiny chartreuse bags, 5 wavy bronze bags, 2 bright red bags.\n"
                                        + "dotted tomato bags contain 5 faded indigo bags, 3 vibrant maroon bags, 4 shiny coral bags.\n"
                                        + "faded salmon bags contain 3 dull silver bags, 2 wavy bronze bags, 2 drab teal bags.\n"
                                        + "vibrant orange bags contain 1 dotted beige bag.\n"
                                        + "muted violet bags contain 5 posh lime bags.\n"
                                        + "striped tan bags contain 3 muted lime bags.\n"
                                        + "drab violet bags contain 3 vibrant chartreuse bags, 5 posh turquoise bags, 1 bright cyan bag.\n"
                                        + "bright purple bags contain 2 vibrant bronze bags, 3 wavy beige bags, 2 plaid bronze bags.\n"
                                        + "vibrant maroon bags contain no other bags.\n"
                                        + "muted teal bags contain 2 bright turquoise bags.\n"
                                        + "bright plum bags contain 5 dark gold bags, 2 shiny turquoise bags, 1 dull yellow bag.\n"
                                        + "shiny crimson bags contain 3 wavy magenta bags.\n"
                                        + "wavy teal bags contain 5 faded indigo bags, 4 dotted gray bags, 3 pale chartreuse bags, 3 vibrant coral bags.\n"
                                        + "shiny blue bags contain 2 shiny salmon bags, 4 light tan bags, 1 dim salmon bag.\n"
                                        + "mirrored maroon bags contain 1 drab fuchsia bag, 3 dotted green bags, 3 muted white bags.\n"
                                        + "clear maroon bags contain 2 vibrant red bags, 5 bright maroon bags, 4 light olive bags.\n"
                                        + "bright salmon bags contain 1 dotted red bag, 4 vibrant beige bags, 3 dark maroon bags, 3 clear lavender bags.\n"
                                        + "pale gold bags contain 3 plaid olive bags.\n"
                                        + "faded lime bags contain 3 faded maroon bags, 5 mirrored aqua bags.\n"
                                        + "faded magenta bags contain 4 plaid orange bags, 5 vibrant violet bags, 1 dotted green bag, 3 wavy crimson bags.\n"
                                        + "wavy aqua bags contain 5 drab yellow bags, 5 posh bronze bags.\n"
                                        + "faded brown bags contain 3 mirrored green bags, 5 dim salmon bags, 4 vibrant blue bags, 1 wavy gray bag.\n"
                                        + "dark purple bags contain 4 pale beige bags, 3 drab lavender bags.\n"
                                        + "dull lime bags contain no other bags.\n"
                                        + "light orange bags contain 1 vibrant white bag, 1 striped magenta bag.\n"
                                        + "mirrored plum bags contain 1 clear green bag, 4 faded blue bags.\n"
                                        + "vibrant brown bags contain 4 dark crimson bags, 5 light plum bags.\n"
                                        + "shiny turquoise bags contain 1 dark lime bag.\n"
                                        + "dark plum bags contain 2 wavy coral bags, 2 striped gray bags, 4 muted blue bags, 2 dull aqua bags.\n"
                                        + "shiny red bags contain 1 plaid gray bag, 4 wavy beige bags, 5 dark red bags.\n"
                                        + "posh violet bags contain 5 striped chartreuse bags, 2 pale maroon bags, 1 dull lime bag.\n"
                                        + "light silver bags contain 2 clear silver bags, 1 dark indigo bag, 2 dim salmon bags, 2 drab salmon bags.\n"
                                        + "plaid orange bags contain 4 dim gold bags, 2 bright magenta bags, 4 drab lavender bags.\n"
                                        + "vibrant silver bags contain 5 posh plum bags, 3 vibrant aqua bags, 2 light lavender bags.\n"
                                        + "faded tomato bags contain 1 pale coral bag, 2 posh gold bags.\n"
                                        + "shiny silver bags contain 4 faded orange bags, 1 striped white bag, 2 faded turquoise bags, 5 striped gray bags.\n"
                                        + "plaid purple bags contain 2 posh olive bags, 3 pale maroon bags, 3 pale gold bags, 1 faded white bag.\n"
                                        + "light tomato bags contain 2 vibrant indigo bags, 4 dark orange bags, 5 muted bronze bags, 4 plaid tomato bags.\n"
                                        + "dull aqua bags contain 5 bright lime bags.\n"
                                        + "drab red bags contain 5 posh teal bags.\n"
                                        + "dotted gray bags contain 2 vibrant salmon bags, 4 mirrored chartreuse bags, 1 dotted tomato bag, 4 posh magenta bags.\n"
                                        + "dull bronze bags contain 3 mirrored brown bags.\n"
                                        + "shiny aqua bags contain no other bags.\n"
                                        + "dim gold bags contain no other bags.\n"
                                        + "pale blue bags contain 4 posh gray bags.\n"
                                        + "faded purple bags contain 5 shiny blue bags, 5 plaid salmon bags, 4 pale tomato bags, 2 dark gold bags.\n"
                                        + "striped teal bags contain 4 mirrored green bags.\n"
                                        + "shiny orange bags contain 4 faded lavender bags, 2 muted salmon bags, 2 dim indigo bags.\n"
                                        + "wavy yellow bags contain 5 clear silver bags, 2 shiny brown bags.\n"
                                        + "vibrant turquoise bags contain 1 vibrant magenta bag, 4 dull fuchsia bags, 5 mirrored green bags.\n"
                                        + "dark teal bags contain 5 dim tomato bags.\n"
                                        + "posh brown bags contain 3 dark orange bags.\n"
                                        + "vibrant gray bags contain 2 dark beige bags, 2 wavy teal bags, 3 light purple bags.\n"
                                        + "drab black bags contain 1 mirrored maroon bag, 3 pale silver bags, 3 dark brown bags, 1 shiny gray bag.\n"
                                        + "light blue bags contain 2 dim olive bags, 2 striped magenta bags.\n"
                                        + "muted turquoise bags contain 3 dim lime bags, 3 shiny coral bags.\n"
                                        + "faded red bags contain 5 clear gray bags.\n"
                                        + "bright chartreuse bags contain 4 plaid teal bags, 5 drab salmon bags, 5 wavy cyan bags.\n"
                                        + "light magenta bags contain 5 light aqua bags, 4 light crimson bags, 3 dark yellow bags, 1 light tomato bag.\n"
                                        + "striped coral bags contain 3 mirrored white bags.\n"
                                        + "shiny maroon bags contain 1 vibrant red bag, 3 bright red bags.\n"
                                        + "striped yellow bags contain 1 bright orange bag, 2 faded plum bags, 3 light olive bags, 3 shiny aqua bags.\n"
                                        + "dull olive bags contain 2 posh fuchsia bags, 2 dull coral bags, 2 faded red bags.\n"
                                        + "dotted yellow bags contain 1 drab salmon bag, 3 pale fuchsia bags.\n"
                                        + "light bronze bags contain 3 drab cyan bags, 5 mirrored orange bags, 4 plaid crimson bags.\n"
                                        + "shiny chartreuse bags contain 1 wavy cyan bag, 4 shiny tomato bags.\n"
                                        + "dull yellow bags contain no other bags.\n"
                                        + "faded plum bags contain 5 vibrant blue bags, 5 clear indigo bags, 5 posh teal bags, 4 posh plum bags.\n"
                                        + "wavy salmon bags contain 4 striped teal bags, 3 wavy tan bags, 1 clear white bag.\n"
                                        + "posh salmon bags contain 4 dull chartreuse bags, 4 shiny yellow bags, 2 dotted black bags, 3 clear lime bags.\n"
                                        + "dull white bags contain 2 dim olive bags, 4 vibrant bronze bags, 4 faded cyan bags.\n"
                                        + "shiny gold bags contain 5 bright maroon bags, 5 shiny aqua bags, 2 clear lime bags, 2 muted white bags.\n"
                                        + "posh plum bags contain 4 posh purple bags, 2 wavy beige bags, 5 plaid plum bags.\n"
                                        + "shiny magenta bags contain 4 shiny tan bags, 2 dull green bags, 3 mirrored purple bags.\n"
                                        + "wavy olive bags contain 4 vibrant olive bags, 2 clear fuchsia bags, 1 light plum bag, 2 dark violet bags.\n"
                                        + "muted lime bags contain 4 posh white bags, 4 shiny tomato bags.\n"
                                        + "light indigo bags contain 2 clear turquoise bags, 3 vibrant black bags, 3 striped lime bags.\n"
                                        + "muted yellow bags contain 3 mirrored tomato bags.\n"
                                        + "faded beige bags contain 5 clear red bags, 3 dull brown bags, 4 dark red bags, 1 vibrant magenta bag.\n"
                                        + "striped turquoise bags contain 2 bright aqua bags, 5 dim cyan bags, 1 pale lavender bag.\n"
                                        + "pale beige bags contain no other bags.\n"
                                        + "dull silver bags contain 3 bright lime bags, 2 pale tomato bags, 3 mirrored green bags.\n"
                                        + "clear cyan bags contain 1 vibrant blue bag, 2 faded cyan bags, 1 faded brown bag.\n"
                                        + "posh green bags contain 2 vibrant gray bags, 1 pale magenta bag.\n"
                                        + "muted beige bags contain 2 drab blue bags, 3 vibrant magenta bags, 5 pale tomato bags.\n"
                                        + "bright silver bags contain 4 dull brown bags, 4 vibrant violet bags, 4 dim violet bags.\n"
                                        + "mirrored bronze bags contain 2 bright indigo bags, 3 shiny coral bags.\n"
                                        + "dull red bags contain 4 dull plum bags, 1 striped black bag, 1 dim teal bag, 4 dim white bags.\n"
                                        + "dim chartreuse bags contain 3 drab maroon bags.\n"
                                        + "drab crimson bags contain 5 dull turquoise bags, 3 posh gold bags, 4 bright gold bags, 2 muted indigo bags.\n"
                                        + "wavy brown bags contain 1 muted white bag.\n"
                                        + "plaid violet bags contain 2 faded tomato bags.\n"
                                        + "muted salmon bags contain 1 light cyan bag, 1 vibrant blue bag.\n"
                                        + "mirrored salmon bags contain 1 dotted green bag, 2 plaid salmon bags.\n"
                                        + "posh lime bags contain 1 vibrant blue bag.\n"
                                        + "shiny tan bags contain 2 bright red bags, 1 dim maroon bag, 3 vibrant salmon bags.\n"
                                        + "vibrant aqua bags contain 5 shiny orange bags, 2 dull coral bags, 4 vibrant bronze bags, 5 dark indigo bags.\n"
                                        + "posh magenta bags contain 5 dim maroon bags, 2 wavy indigo bags.\n"
                                        + "posh red bags contain 4 dull black bags, 2 shiny tomato bags, 4 faded beige bags.\n"
                                        + "mirrored indigo bags contain 4 faded magenta bags, 1 light red bag, 3 muted gray bags, 2 plaid lavender bags.\n"
                                        + "drab indigo bags contain 4 dull tan bags, 2 dark coral bags.\n"
                                        + "vibrant lavender bags contain 5 posh turquoise bags, 4 posh bronze bags, 5 light tomato bags.\n"
                                        + "mirrored blue bags contain 1 striped bronze bag, 4 plaid salmon bags, 3 posh lime bags, 4 mirrored green bags.\n"
                                        + "plaid blue bags contain 4 bright violet bags, 5 clear red bags.\n"
                                        + "dark tan bags contain 3 faded chartreuse bags, 1 posh gold bag, 5 light chartreuse bags.\n"
                                        + "bright teal bags contain 3 pale yellow bags, 1 vibrant white bag, 3 shiny salmon bags, 1 plaid indigo bag.\n"
                                        + "dark gold bags contain 1 mirrored green bag.\n"
                                        + "plaid beige bags contain 5 dim cyan bags.\n"
                                        + "pale plum bags contain 4 striped olive bags, 1 mirrored violet bag.\n"
                                        + "drab orange bags contain 1 plaid cyan bag, 2 vibrant green bags, 4 striped crimson bags, 2 posh teal bags.\n"
                                        + "faded teal bags contain 4 muted salmon bags, 1 dim tomato bag, 5 clear white bags.\n"
                                        + "posh cyan bags contain 3 shiny gray bags, 2 posh indigo bags.\n"
                                        + "plaid tan bags contain 4 plaid silver bags, 2 dark beige bags, 3 plaid salmon bags, 5 light beige bags.\n"
                                        + "muted olive bags contain 5 vibrant salmon bags, 2 dull orange bags.\n"
                                        + "muted tan bags contain 5 wavy gold bags, 2 striped orange bags, 4 plaid lavender bags.\n"
                                        + "posh tan bags contain 3 shiny lavender bags, 5 vibrant red bags, 4 light bronze bags.\n"
                                        + "bright tomato bags contain 3 dull lime bags, 3 wavy gray bags.\n"
                                        + "dark turquoise bags contain 3 vibrant coral bags, 4 wavy beige bags.\n"
                                        + "faded indigo bags contain 4 wavy gray bags.\n"
                                        + "clear blue bags contain 2 pale yellow bags.\n"
                                        + "light gold bags contain 5 light olive bags, 4 clear white bags, 3 plaid silver bags, 2 bright maroon bags.\n"
                                        + "light lavender bags contain 2 dotted black bags, 4 plaid tomato bags, 4 dark orange bags, 5 shiny blue bags.\n"
                                        + "faded coral bags contain 5 pale gold bags, 4 dull black bags.\n"
                                        + "vibrant salmon bags contain 2 faded teal bags, 4 drab lavender bags, 5 clear teal bags, 1 dim olive bag.\n"
                                        + "muted orange bags contain 1 posh salmon bag, 2 light cyan bags, 5 shiny tomato bags, 4 dim olive bags.\n"
                                        + "clear black bags contain 3 wavy bronze bags, 4 wavy lime bags, 4 shiny black bags.\n"
                                        + "pale violet bags contain 1 faded violet bag, 3 pale chartreuse bags, 5 drab blue bags.\n"
                                        + "dotted plum bags contain 2 muted chartreuse bags, 3 vibrant turquoise bags, 5 posh brown bags.\n"
                                        + "plaid maroon bags contain 1 posh coral bag, 1 dull fuchsia bag.\n"
                                        + "dotted brown bags contain 1 posh lime bag, 5 dull turquoise bags.\n"
                                        + "pale green bags contain 3 drab magenta bags, 4 dim salmon bags, 1 vibrant chartreuse bag.\n"
                                        + "dark tomato bags contain 2 clear indigo bags, 1 light plum bag, 2 dull turquoise bags.\n"
                                        + "striped silver bags contain 5 dark red bags, 4 faded purple bags.\n"
                                        + "shiny fuchsia bags contain 2 dark gold bags, 3 dull tomato bags.\n"
                                        + "mirrored aqua bags contain 5 dark bronze bags.\n"
                                        + "dim beige bags contain 5 dull white bags.\n"
                                        + "dark chartreuse bags contain 4 light crimson bags, 3 dim salmon bags, 2 dark orange bags.\n"
                                        + "plaid chartreuse bags contain 4 drab blue bags.\n"
                                        + "dim green bags contain 4 muted bronze bags, 1 shiny indigo bag.\n"
                                        + "mirrored crimson bags contain 5 wavy fuchsia bags, 2 vibrant magenta bags.\n"
                                        + "clear yellow bags contain 3 plaid bronze bags, 1 light tan bag.\n"
                                        + "bright turquoise bags contain 3 shiny salmon bags.\n"
                                        + "drab brown bags contain 1 vibrant fuchsia bag.\n"
                                        + "dim bronze bags contain 2 dim aqua bags, 4 dim beige bags.\n"
                                        + "dim black bags contain 1 posh purple bag, 4 mirrored bronze bags, 5 posh plum bags.\n"
                                        + "plaid gold bags contain 4 posh silver bags, 5 light turquoise bags, 3 vibrant black bags.\n"
                                        + "drab lime bags contain 1 muted gold bag, 4 dotted red bags.\n"
                                        + "bright red bags contain 1 dull yellow bag, 4 mirrored gold bags.\n"
                                        + "vibrant white bags contain 2 dull lime bags, 2 faded indigo bags, 1 faded brown bag, 1 muted salmon bag.\n"
                                        + "drab fuchsia bags contain 3 pale beige bags, 3 dark orange bags.\n"
                                        + "striped tomato bags contain 1 dark lime bag, 5 dull coral bags.\n"
                                        + "faded green bags contain 2 wavy blue bags.\n"
                                        + "vibrant olive bags contain 3 bright tomato bags, 4 wavy beige bags.\n"
                                        + "dark coral bags contain 5 faded teal bags, 1 mirrored tomato bag, 3 dark orange bags, 5 plaid lime bags.\n"
                                        + "bright violet bags contain 4 dark lime bags.\n"
                                        + "wavy tan bags contain 4 light tan bags, 3 vibrant red bags, 2 mirrored olive bags.\n"
                                        + "dotted beige bags contain 5 striped gray bags, 4 posh plum bags, 1 bright turquoise bag, 4 striped fuchsia bags.\n"
                                        + "dotted turquoise bags contain 3 mirrored green bags, 4 posh gold bags, 5 drab plum bags.\n"
                                        + "striped beige bags contain 1 clear gold bag, 1 vibrant white bag, 3 faded cyan bags, 2 shiny gold bags.\n"
                                        + "posh silver bags contain 2 vibrant gold bags, 2 mirrored violet bags.\n"
                                        + "mirrored purple bags contain 2 dim yellow bags, 2 dull tomato bags.\n"
                                        + "shiny lime bags contain 4 clear olive bags, 4 mirrored silver bags, 1 muted tomato bag.\n"
                                        + "muted cyan bags contain 1 posh coral bag, 5 drab blue bags, 4 wavy lavender bags.\n"
                                        + "light aqua bags contain 1 dark orange bag.\n"
                                        + "shiny cyan bags contain 2 dark maroon bags, 5 shiny salmon bags, 5 muted salmon bags, 2 wavy bronze bags.\n"
                                        + "posh white bags contain 1 posh fuchsia bag.\n"
                                        + "vibrant plum bags contain 4 light crimson bags.\n"
                                        + "dotted blue bags contain 1 shiny tan bag, 3 light plum bags, 5 dotted gray bags.\n"
                                        + "posh maroon bags contain 5 mirrored violet bags.\n"
                                        + "dull violet bags contain 1 faded teal bag, 2 wavy cyan bags, 3 dull silver bags, 3 vibrant red bags.\n"
                                        + "posh gold bags contain 4 muted salmon bags, 4 dull plum bags, 3 muted bronze bags.\n"
                                        + "dim orange bags contain 2 dull coral bags.\n"
                                        + "dim aqua bags contain 1 drab maroon bag.\n"
                                        + "striped salmon bags contain 4 muted white bags.\n"
                                        + "dark cyan bags contain 3 plaid maroon bags.\n"
                                        + "wavy red bags contain 2 wavy maroon bags, 2 vibrant chartreuse bags, 5 wavy salmon bags.\n"
                                        + "light yellow bags contain 4 posh lime bags, 1 light white bag.\n"
                                        + "striped blue bags contain 5 plaid magenta bags, 5 vibrant gold bags.\n"
                                        + "dark olive bags contain 4 dim maroon bags, 2 shiny tan bags, 5 wavy green bags.\n"
                                        + "vibrant gold bags contain 1 dull beige bag, 4 posh turquoise bags.\n"
                                        + "muted white bags contain 1 dim indigo bag, 5 dull lime bags, 5 shiny aqua bags.\n"
                                        + "light violet bags contain 5 wavy bronze bags.\n"
                                        + "pale olive bags contain 1 dim gold bag, 2 shiny coral bags.\n"
                                        + "light gray bags contain 3 bright gold bags.\n"
                                        + "dim indigo bags contain 3 posh tomato bags, 5 pale tomato bags, 4 shiny aqua bags.\n"
                                        + "pale indigo bags contain 4 pale bronze bags, 5 light chartreuse bags.\n"
                                        + "muted red bags contain 3 clear white bags, 4 dull lavender bags, 5 muted purple bags.\n"
                                        + "plaid olive bags contain 3 dark orange bags, 3 dim gold bags.\n"
                                        + "dotted maroon bags contain 3 faded purple bags, 5 light green bags.\n"
                                        + "bright orange bags contain 1 shiny black bag, 2 dim lavender bags, 1 shiny olive bag.\n"
                                        + "wavy chartreuse bags contain 3 clear lime bags, 4 pale maroon bags.\n"
                                        + "mirrored turquoise bags contain 2 striped crimson bags, 4 vibrant bronze bags, 5 dotted lavender bags, 2 clear silver bags.\n"
                                        + "dull purple bags contain 4 posh crimson bags.\n"
                                        + "faded bronze bags contain 1 clear fuchsia bag, 2 light fuchsia bags, 2 pale chartreuse bags.\n"
                                        + "clear bronze bags contain 3 pale chartreuse bags, 5 dull tan bags, 1 vibrant tan bag.\n"
                                        + "vibrant magenta bags contain 4 shiny fuchsia bags, 2 shiny coral bags, 3 faded indigo bags, 4 pale tomato bags.\n"
                                        + "striped chartreuse bags contain 2 shiny orange bags, 3 mirrored tomato bags, 1 clear lime bag.\n"
                                        + "dotted green bags contain 1 pale beige bag, 2 mirrored bronze bags, 2 wavy crimson bags.\n"
                                        + "wavy white bags contain 3 posh magenta bags, 3 muted yellow bags, 3 wavy crimson bags, 4 vibrant olive bags.\n"
                                        + "muted plum bags contain 4 wavy gold bags.\n"
                                        + "faded violet bags contain 3 dark violet bags.\n"
                                        + "dull fuchsia bags contain 4 plaid indigo bags, 1 mirrored brown bag, 5 clear lime bags.\n"
                                        + "bright green bags contain 3 mirrored white bags, 5 dotted silver bags.\n"
                                        + "shiny violet bags contain 4 striped salmon bags.\n"
                                        + "dim fuchsia bags contain 3 striped red bags.\n"
                                        + "faded lavender bags contain 3 wavy tan bags, 2 clear lime bags.\n"
                                        + "dim cyan bags contain 4 drab white bags.\n"
                                        + "dark brown bags contain 5 clear gold bags, 3 vibrant blue bags.\n"
                                        + "clear lavender bags contain 5 striped turquoise bags, 1 light crimson bag, 5 light tan bags, 2 muted gold bags.\n"
                                        + "light green bags contain 3 striped silver bags, 4 bright silver bags, 2 light crimson bags.\n"
                                        + "pale lavender bags contain 5 clear violet bags.\n"
                                        + "dotted orange bags contain 3 dotted tomato bags, 2 dull plum bags, 5 posh purple bags, 2 drab turquoise bags.\n"
                                        + "bright black bags contain 3 posh chartreuse bags, 5 wavy indigo bags, 5 dull crimson bags, 2 clear turquoise bags.\n"
                                        + "dotted gold bags contain 5 striped white bags, 2 striped brown bags, 3 mirrored green bags, 3 dark violet bags.\n"
                                        + "plaid brown bags contain 3 striped chartreuse bags, 3 striped black bags, 2 bright chartreuse bags.\n"
                                        + "wavy coral bags contain 3 dim turquoise bags, 4 dim lime bags.\n"
                                        + "pale brown bags contain 4 dim white bags, 5 bright fuchsia bags, 2 clear orange bags.\n"
                                        + "mirrored teal bags contain 4 pale lavender bags, 5 vibrant maroon bags, 4 striped gray bags, 4 vibrant indigo bags.\n"
                                        + "posh orange bags contain 5 posh magenta bags, 4 posh violet bags, 2 plaid magenta bags, 4 muted cyan bags.\n"
                                        + "dim crimson bags contain 3 drab violet bags, 1 dotted aqua bag.\n"
                                        + "muted gray bags contain 4 vibrant lime bags, 1 dark maroon bag, 2 clear gold bags, 3 plaid gray bags.\n"
                                        + "clear brown bags contain 5 shiny tomato bags, 4 striped tan bags, 5 vibrant lavender bags, 1 pale white bag.\n"
                                        + "posh crimson bags contain 3 dim yellow bags, 4 shiny turquoise bags, 2 vibrant purple bags, 4 mirrored aqua bags.\n"
                                        + "plaid black bags contain 2 shiny tan bags, 1 pale olive bag, 2 wavy tan bags, 1 clear red bag.\n"
                                        + "dark crimson bags contain 3 drab fuchsia bags, 5 faded gold bags.\n"
                                        + "pale tan bags contain 5 posh black bags.\n"
                                        + "wavy bronze bags contain 1 clear lime bag.\n"
                                        + "wavy gold bags contain 2 dull lavender bags, 1 bright turquoise bag, 4 striped brown bags, 5 drab turquoise bags.\n"
                                        + "pale lime bags contain 2 faded cyan bags, 4 muted salmon bags, 4 shiny coral bags, 3 mirrored green bags.\n"
                                        + "dark magenta bags contain 4 faded chartreuse bags, 1 muted brown bag, 4 vibrant salmon bags, 2 dim indigo bags.\n"
                                        + "striped purple bags contain 3 mirrored olive bags.\n"
                                        + "dull crimson bags contain 2 clear orange bags.\n"
                                        + "dull beige bags contain 1 drab turquoise bag, 1 dark indigo bag, 1 dull white bag.\n"
                                        + "dotted aqua bags contain 4 dull chartreuse bags.\n"
                                        + "clear purple bags contain 2 muted beige bags, 3 dull black bags.\n"
                                        + "light crimson bags contain 1 faded brown bag, 1 vibrant red bag, 4 wavy lavender bags, 1 wavy gray bag.\n"
                                        + "clear fuchsia bags contain 1 dark maroon bag, 3 muted salmon bags.\n"
                                        + "muted crimson bags contain 5 light lime bags, 4 posh plum bags, 5 clear fuchsia bags, 1 wavy turquoise bag.\n"
                                        + "muted purple bags contain 3 dull gray bags, 5 posh gray bags.\n"
                                        + "shiny salmon bags contain 5 faded brown bags, 4 clear chartreuse bags.\n"
                                        + "plaid lavender bags contain 1 dim lime bag.\n"
                                        + "vibrant indigo bags contain 5 dim tomato bags, 2 striped beige bags, 2 mirrored olive bags.\n"
                                        + "mirrored cyan bags contain 3 plaid coral bags, 5 faded teal bags, 5 pale indigo bags, 3 bright fuchsia bags.\n"
                                        + "dim yellow bags contain 5 light crimson bags, 1 pale tomato bag.\n"
                                        + "dotted chartreuse bags contain 3 shiny blue bags.\n"
                                        + "light beige bags contain 3 bright teal bags, 1 pale tomato bag, 2 light blue bags.\n"
                                        + "dotted olive bags contain 3 bright indigo bags, 4 muted fuchsia bags.\n"
                                        + "pale white bags contain 1 vibrant maroon bag, 2 pale tomato bags, 2 bright magenta bags.\n"
                                        + "mirrored yellow bags contain 2 drab brown bags, 3 striped salmon bags, 4 clear olive bags, 1 dotted black bag.\n"
                                        + "light olive bags contain 2 bright magenta bags.\n"
                                        + "muted tomato bags contain 4 shiny lavender bags.\n"
                                        + "light chartreuse bags contain 5 light plum bags, 4 light olive bags, 3 dark indigo bags.\n"
                                        + "posh purple bags contain 2 wavy crimson bags.\n"
                                        + "bright maroon bags contain 4 faded indigo bags.\n"
                                        + "dull blue bags contain 3 dark brown bags, 3 dim indigo bags, 5 pale silver bags, 1 mirrored brown bag.\n"
                                        + "light coral bags contain 5 clear teal bags.\n"
                                        + "bright gray bags contain 3 muted black bags, 3 vibrant cyan bags.\n"
                                        + "posh fuchsia bags contain 3 clear gold bags, 1 dim salmon bag, 2 shiny salmon bags.\n"
                                        + "light white bags contain 3 dim cyan bags, 5 clear crimson bags, 3 dull fuchsia bags.\n"
                                        + "light teal bags contain 3 shiny fuchsia bags, 2 muted white bags, 3 shiny black bags.\n"
                                        + "plaid salmon bags contain 2 dotted black bags, 2 dark beige bags, 1 shiny coral bag.\n"
                                        + "wavy black bags contain 5 posh olive bags.\n"
                                        + "drab gray bags contain 3 mirrored tomato bags, 3 light crimson bags.\n"
                                        + "dim olive bags contain 5 clear chartreuse bags.\n"
                                        + "bright white bags contain 2 mirrored tan bags, 1 pale green bag, 5 dull magenta bags, 5 plaid lime bags.\n"
                                        + "striped olive bags contain 3 muted gold bags.\n"
                                        + "faded olive bags contain 1 muted indigo bag.\n"
                                        + "pale yellow bags contain 5 light olive bags, 5 plaid aqua bags, 1 clear white bag, 5 faded purple bags.\n"
                                        + "dull coral bags contain 4 light crimson bags, 5 shiny aqua bags, 5 wavy cyan bags, 3 dark beige bags.\n"
                                        + "vibrant beige bags contain 4 striped olive bags, 5 clear gold bags.\n"
                                        + "dark fuchsia bags contain 1 pale teal bag, 4 dull gray bags.\n"
                                        + "drab tomato bags contain 4 mirrored white bags.\n"
                                        + "clear crimson bags contain 4 pale tomato bags, 3 wavy gray bags, 4 drab blue bags, 1 mirrored olive bag.\n"
                                        + "dotted crimson bags contain 1 plaid crimson bag, 1 dark crimson bag, 1 striped beige bag, 4 pale fuchsia bags.\n"
                                        + "striped black bags contain 4 muted maroon bags.\n"
                                        + "shiny bronze bags contain 1 dotted tan bag, 1 vibrant beige bag, 5 faded tomato bags.\n"
                                        + "light cyan bags contain no other bags.\n"
                                        + "posh black bags contain 2 dim green bags.\n"
                                        + "striped gold bags contain 3 drab tan bags.\n"
                                        + "faded white bags contain 4 pale coral bags.\n"
                                        + "drab tan bags contain 4 clear gold bags, 5 drab silver bags.\n"
                                        + "light tan bags contain 2 dull lime bags, 1 muted salmon bag, 4 pale beige bags.\n"
                                        + "plaid indigo bags contain 3 plaid salmon bags, 1 vibrant maroon bag.\n"
                                        + "faded gold bags contain 3 dark coral bags.\n"
                                        + "dark salmon bags contain 5 bright gold bags, 1 pale white bag.\n"
                                        + "plaid bronze bags contain 3 drab gold bags, 4 dotted black bags.\n"
                                        + "shiny black bags contain 3 bright magenta bags, 2 dark indigo bags, 1 posh plum bag, 5 drab gold bags.\n"
                                        + "pale magenta bags contain 1 clear gold bag, 5 posh fuchsia bags, 2 faded cyan bags.";
}
