package aoc2020;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Day8 {
    public static void main(String[] args) {
//        String input = TEST_INPUT;
        String input = INPUT;
        a(input);
        b(input);
    }

    enum Inst {
        acc, jmp, nop
    }

    static class Instruction {
        final Inst inst;
        final int val;

        Instruction(Inst inst, int val) {
            this.inst = inst;
            this.val = val;
        }
    }

    static class Program {
        final List<Instruction> instructions;
        final boolean[] seen;
        int pointer;
        int acc = 0;

        Program(List<Instruction> instructions) {
            this.instructions = instructions;
            this.seen = new boolean[instructions.size()];
        }

        boolean step() {
            Instruction instruction = instructions.get(pointer);
            switch (instruction.inst) {
            case acc:
                this.acc += instruction.val;
                pointer++;
                break;
            case jmp:
                pointer += instruction.val;
                break;
            case nop:
                pointer++;
                break;
            }
            if (pointer >= seen.length || seen[pointer]) {
                return false;
            }
            seen[pointer] = true;
            return true;
        }
    }

    private static void b(String input) {
        List<Instruction> instructions = input.lines()
                                              .map(l -> new Instruction(
                                                      Inst.valueOf(l.substring(0, l.indexOf(" "))),
                                                      Integer.parseInt(l.substring(l.indexOf(" ") + 1))))
                                              .collect(Collectors.toList());
        for (int i = 0; i < instructions.size(); i++) {
            Instruction instruction = instructions.get(i);
            if (instruction.inst == Inst.jmp) {
                instruction = new Instruction(Inst.nop, instruction.val);
            } else if (instruction.inst == Inst.nop) {
                instruction = new Instruction(Inst.jmp, instruction.val);
            }
            List<Instruction> fix = new ArrayList<>(instructions);
            fix.set(i, instruction);
            Program p = new Program(fix);
            while (p.step()){

            }
            if (p.pointer >= fix.size()) {
                System.out.println(p.acc);
            }
        }
    }

    private static void a(String input) {
        List<Instruction> instructions = input.lines()
                                              .map(l -> new Instruction(
                                                      Inst.valueOf(l.substring(0, l.indexOf(" "))),
                                                      Integer.parseInt(l.substring(l.indexOf(" ") + 1))))
                                              .collect(Collectors.toList());
        Program p = new Program(instructions);
        while (p.step()){

        }
        System.out.println(p.acc);

    }

    private static final String TEST_INPUT = "nop +0\n"
                                             + "acc +1\n"
                                             + "jmp +4\n"
                                             + "acc +3\n"
                                             + "jmp -3\n"
                                             + "acc -99\n"
                                             + "acc +1\n"
                                             + "jmp -4\n"
                                             + "acc +6";

    private static final String INPUT = "acc +8\n"
                                        + "nop +139\n"
                                        + "nop +383\n"
                                        + "jmp +628\n"
                                        + "acc -6\n"
                                        + "acc +29\n"
                                        + "acc +9\n"
                                        + "jmp +457\n"
                                        + "acc +29\n"
                                        + "acc +38\n"
                                        + "nop +451\n"
                                        + "jmp +44\n"
                                        + "acc +24\n"
                                        + "nop +260\n"
                                        + "acc +20\n"
                                        + "jmp +24\n"
                                        + "acc +36\n"
                                        + "acc +41\n"
                                        + "acc +31\n"
                                        + "acc +42\n"
                                        + "jmp +35\n"
                                        + "acc +21\n"
                                        + "nop +216\n"
                                        + "acc +7\n"
                                        + "jmp +42\n"
                                        + "nop +408\n"
                                        + "acc +18\n"
                                        + "acc -4\n"
                                        + "jmp +532\n"
                                        + "acc -8\n"
                                        + "acc +13\n"
                                        + "jmp +529\n"
                                        + "acc +36\n"
                                        + "jmp +257\n"
                                        + "acc +26\n"
                                        + "acc +24\n"
                                        + "acc -11\n"
                                        + "nop +508\n"
                                        + "jmp +249\n"
                                        + "acc +44\n"
                                        + "acc +25\n"
                                        + "jmp +464\n"
                                        + "acc +47\n"
                                        + "jmp +318\n"
                                        + "acc -6\n"
                                        + "acc -1\n"
                                        + "jmp +175\n"
                                        + "acc +19\n"
                                        + "acc +25\n"
                                        + "acc +24\n"
                                        + "jmp +523\n"
                                        + "acc -7\n"
                                        + "acc +45\n"
                                        + "jmp +353\n"
                                        + "jmp +67\n"
                                        + "acc -1\n"
                                        + "jmp -17\n"
                                        + "acc -9\n"
                                        + "jmp +180\n"
                                        + "acc +19\n"
                                        + "acc -15\n"
                                        + "acc +5\n"
                                        + "jmp +52\n"
                                        + "nop +312\n"
                                        + "acc +38\n"
                                        + "jmp -6\n"
                                        + "acc +6\n"
                                        + "acc -11\n"
                                        + "acc -6\n"
                                        + "jmp +357\n"
                                        + "jmp +455\n"
                                        + "acc +27\n"
                                        + "acc +29\n"
                                        + "acc +9\n"
                                        + "nop +414\n"
                                        + "jmp +380\n"
                                        + "jmp +1\n"
                                        + "acc +33\n"
                                        + "jmp +47\n"
                                        + "acc +12\n"
                                        + "acc +34\n"
                                        + "acc -9\n"
                                        + "acc +17\n"
                                        + "jmp +214\n"
                                        + "jmp +125\n"
                                        + "acc +38\n"
                                        + "acc +38\n"
                                        + "acc +16\n"
                                        + "jmp +310\n"
                                        + "acc +9\n"
                                        + "acc +10\n"
                                        + "acc -2\n"
                                        + "nop -84\n"
                                        + "jmp +329\n"
                                        + "nop +120\n"
                                        + "nop -70\n"
                                        + "jmp -88\n"
                                        + "jmp +1\n"
                                        + "jmp +1\n"
                                        + "acc +23\n"
                                        + "jmp -34\n"
                                        + "nop +372\n"
                                        + "acc +18\n"
                                        + "acc +3\n"
                                        + "acc +24\n"
                                        + "jmp -50\n"
                                        + "acc -11\n"
                                        + "acc +27\n"
                                        + "nop +441\n"
                                        + "jmp +443\n"
                                        + "acc +44\n"
                                        + "acc -3\n"
                                        + "acc +7\n"
                                        + "jmp +389\n"
                                        + "acc -5\n"
                                        + "acc +36\n"
                                        + "acc -17\n"
                                        + "acc +15\n"
                                        + "jmp +13\n"
                                        + "acc +39\n"
                                        + "jmp +407\n"
                                        + "acc +8\n"
                                        + "acc +21\n"
                                        + "jmp +360\n"
                                        + "jmp +425\n"
                                        + "acc +7\n"
                                        + "acc +29\n"
                                        + "acc +6\n"
                                        + "jmp +10\n"
                                        + "jmp +1\n"
                                        + "jmp +426\n"
                                        + "acc +23\n"
                                        + "jmp +3\n"
                                        + "nop +2\n"
                                        + "jmp +1\n"
                                        + "jmp +240\n"
                                        + "acc +16\n"
                                        + "jmp -2\n"
                                        + "jmp +47\n"
                                        + "jmp +488\n"
                                        + "jmp +1\n"
                                        + "acc +45\n"
                                        + "jmp +1\n"
                                        + "acc +20\n"
                                        + "jmp +344\n"
                                        + "jmp +407\n"
                                        + "acc +2\n"
                                        + "acc +3\n"
                                        + "jmp +117\n"
                                        + "acc +50\n"
                                        + "jmp -134\n"
                                        + "acc +1\n"
                                        + "jmp +238\n"
                                        + "acc +27\n"
                                        + "acc -11\n"
                                        + "acc +16\n"
                                        + "nop +134\n"
                                        + "jmp +116\n"
                                        + "acc -16\n"
                                        + "nop +393\n"
                                        + "jmp +2\n"
                                        + "jmp +24\n"
                                        + "nop +98\n"
                                        + "acc +36\n"
                                        + "acc +0\n"
                                        + "nop +268\n"
                                        + "jmp +131\n"
                                        + "nop +294\n"
                                        + "acc +23\n"
                                        + "acc +26\n"
                                        + "acc +43\n"
                                        + "jmp +358\n"
                                        + "nop +316\n"
                                        + "jmp +300\n"
                                        + "acc +22\n"
                                        + "acc +47\n"
                                        + "acc +19\n"
                                        + "acc +2\n"
                                        + "jmp +228\n"
                                        + "jmp +176\n"
                                        + "acc -4\n"
                                        + "acc +20\n"
                                        + "nop +83\n"
                                        + "acc -19\n"
                                        + "jmp -99\n"
                                        + "acc +39\n"
                                        + "nop +374\n"
                                        + "acc +3\n"
                                        + "jmp +57\n"
                                        + "jmp +1\n"
                                        + "acc +42\n"
                                        + "jmp +404\n"
                                        + "acc +4\n"
                                        + "acc -4\n"
                                        + "acc -10\n"
                                        + "nop +293\n"
                                        + "jmp +349\n"
                                        + "acc -9\n"
                                        + "acc +33\n"
                                        + "jmp +284\n"
                                        + "nop +1\n"
                                        + "acc +18\n"
                                        + "acc -1\n"
                                        + "acc -5\n"
                                        + "jmp +411\n"
                                        + "acc +4\n"
                                        + "acc -6\n"
                                        + "acc +16\n"
                                        + "jmp +313\n"
                                        + "acc +0\n"
                                        + "acc +39\n"
                                        + "jmp +3\n"
                                        + "acc -13\n"
                                        + "jmp +148\n"
                                        + "nop +51\n"
                                        + "nop -207\n"
                                        + "nop +357\n"
                                        + "acc -19\n"
                                        + "jmp +409\n"
                                        + "acc +32\n"
                                        + "jmp +103\n"
                                        + "acc +5\n"
                                        + "jmp +116\n"
                                        + "nop +399\n"
                                        + "acc +19\n"
                                        + "acc +39\n"
                                        + "nop +78\n"
                                        + "jmp +298\n"
                                        + "acc -16\n"
                                        + "acc +31\n"
                                        + "jmp +1\n"
                                        + "acc +45\n"
                                        + "jmp -207\n"
                                        + "acc +6\n"
                                        + "acc +36\n"
                                        + "acc +34\n"
                                        + "acc +47\n"
                                        + "jmp -112\n"
                                        + "acc +23\n"
                                        + "acc +4\n"
                                        + "jmp +289\n"
                                        + "acc -17\n"
                                        + "nop +307\n"
                                        + "nop -92\n"
                                        + "jmp -146\n"
                                        + "jmp +293\n"
                                        + "nop +44\n"
                                        + "acc +5\n"
                                        + "acc +2\n"
                                        + "acc -19\n"
                                        + "jmp +172\n"
                                        + "acc +10\n"
                                        + "acc +49\n"
                                        + "acc -2\n"
                                        + "jmp +6\n"
                                        + "acc +3\n"
                                        + "jmp +1\n"
                                        + "acc -19\n"
                                        + "acc +35\n"
                                        + "jmp +328\n"
                                        + "acc +38\n"
                                        + "acc -5\n"
                                        + "nop -83\n"
                                        + "jmp -138\n"
                                        + "jmp -55\n"
                                        + "acc +35\n"
                                        + "jmp +1\n"
                                        + "jmp -216\n"
                                        + "nop +220\n"
                                        + "jmp +116\n"
                                        + "jmp -78\n"
                                        + "nop +331\n"
                                        + "jmp +118\n"
                                        + "jmp +287\n"
                                        + "jmp -258\n"
                                        + "jmp -181\n"
                                        + "nop +85\n"
                                        + "acc +31\n"
                                        + "acc +10\n"
                                        + "acc -13\n"
                                        + "jmp +175\n"
                                        + "jmp +66\n"
                                        + "acc +34\n"
                                        + "acc +6\n"
                                        + "nop -126\n"
                                        + "acc +38\n"
                                        + "jmp +4\n"
                                        + "acc +18\n"
                                        + "jmp -13\n"
                                        + "jmp -8\n"
                                        + "jmp +1\n"
                                        + "acc -9\n"
                                        + "acc +31\n"
                                        + "nop +92\n"
                                        + "jmp +118\n"
                                        + "nop +21\n"
                                        + "jmp +110\n"
                                        + "acc +20\n"
                                        + "acc +20\n"
                                        + "jmp +280\n"
                                        + "jmp -142\n"
                                        + "jmp +8\n"
                                        + "nop -286\n"
                                        + "jmp +170\n"
                                        + "acc +22\n"
                                        + "acc +29\n"
                                        + "nop -127\n"
                                        + "jmp +36\n"
                                        + "jmp +328\n"
                                        + "acc +27\n"
                                        + "jmp -110\n"
                                        + "acc +28\n"
                                        + "acc +44\n"
                                        + "acc +34\n"
                                        + "acc +43\n"
                                        + "jmp -42\n"
                                        + "acc -19\n"
                                        + "jmp +185\n"
                                        + "acc -8\n"
                                        + "nop -3\n"
                                        + "acc +31\n"
                                        + "acc -11\n"
                                        + "jmp +142\n"
                                        + "acc +49\n"
                                        + "acc -2\n"
                                        + "acc +28\n"
                                        + "acc +17\n"
                                        + "jmp +167\n"
                                        + "acc +16\n"
                                        + "jmp +165\n"
                                        + "jmp -190\n"
                                        + "jmp -117\n"
                                        + "acc +0\n"
                                        + "acc +16\n"
                                        + "jmp +1\n"
                                        + "acc -10\n"
                                        + "jmp -39\n"
                                        + "jmp +69\n"
                                        + "jmp -187\n"
                                        + "nop -101\n"
                                        + "jmp +1\n"
                                        + "acc +12\n"
                                        + "jmp +218\n"
                                        + "acc -6\n"
                                        + "jmp -300\n"
                                        + "acc +10\n"
                                        + "jmp +104\n"
                                        + "jmp +1\n"
                                        + "acc +36\n"
                                        + "jmp -243\n"
                                        + "nop +138\n"
                                        + "acc -15\n"
                                        + "acc +13\n"
                                        + "nop +278\n"
                                        + "jmp -192\n"
                                        + "acc +13\n"
                                        + "jmp +275\n"
                                        + "acc +0\n"
                                        + "nop +92\n"
                                        + "nop +214\n"
                                        + "jmp -90\n"
                                        + "acc +44\n"
                                        + "nop +225\n"
                                        + "acc +9\n"
                                        + "jmp -348\n"
                                        + "acc +16\n"
                                        + "jmp -334\n"
                                        + "nop -335\n"
                                        + "acc -16\n"
                                        + "acc -9\n"
                                        + "jmp -89\n"
                                        + "acc +35\n"
                                        + "acc +2\n"
                                        + "acc +26\n"
                                        + "jmp +68\n"
                                        + "acc -19\n"
                                        + "acc +14\n"
                                        + "acc -19\n"
                                        + "acc -19\n"
                                        + "jmp +262\n"
                                        + "acc -16\n"
                                        + "nop -246\n"
                                        + "nop -251\n"
                                        + "acc +26\n"
                                        + "jmp +143\n"
                                        + "nop +48\n"
                                        + "acc +48\n"
                                        + "jmp +249\n"
                                        + "acc -8\n"
                                        + "jmp +9\n"
                                        + "acc +42\n"
                                        + "acc +12\n"
                                        + "acc +19\n"
                                        + "acc -4\n"
                                        + "jmp +213\n"
                                        + "acc +1\n"
                                        + "acc +29\n"
                                        + "jmp -259\n"
                                        + "acc +3\n"
                                        + "acc +17\n"
                                        + "acc -13\n"
                                        + "jmp -131\n"
                                        + "acc +16\n"
                                        + "acc -9\n"
                                        + "acc +28\n"
                                        + "jmp +222\n"
                                        + "acc +42\n"
                                        + "acc +20\n"
                                        + "acc -3\n"
                                        + "acc +50\n"
                                        + "jmp -339\n"
                                        + "jmp +1\n"
                                        + "acc +1\n"
                                        + "nop -315\n"
                                        + "acc +44\n"
                                        + "acc +50\n"
                                        + "jmp -143\n"
                                        + "nop -87\n"
                                        + "nop +155\n"
                                        + "jmp +1\n"
                                        + "nop +44\n"
                                        + "jmp +158\n"
                                        + "nop -10\n"
                                        + "acc +9\n"
                                        + "jmp +90\n"
                                        + "jmp +89\n"
                                        + "acc +27\n"
                                        + "acc -5\n"
                                        + "acc -8\n"
                                        + "acc +40\n"
                                        + "jmp +3\n"
                                        + "nop -360\n"
                                        + "jmp +117\n"
                                        + "acc -14\n"
                                        + "acc -16\n"
                                        + "nop -184\n"
                                        + "acc +20\n"
                                        + "jmp +185\n"
                                        + "acc -2\n"
                                        + "acc +36\n"
                                        + "nop +24\n"
                                        + "jmp +195\n"
                                        + "acc -8\n"
                                        + "acc -3\n"
                                        + "acc +7\n"
                                        + "jmp -84\n"
                                        + "acc +0\n"
                                        + "acc -12\n"
                                        + "acc +43\n"
                                        + "jmp -270\n"
                                        + "nop -434\n"
                                        + "acc -15\n"
                                        + "jmp +163\n"
                                        + "acc +14\n"
                                        + "jmp +29\n"
                                        + "acc +32\n"
                                        + "acc +26\n"
                                        + "acc +13\n"
                                        + "jmp -91\n"
                                        + "acc +30\n"
                                        + "jmp -163\n"
                                        + "nop +175\n"
                                        + "jmp -175\n"
                                        + "jmp +20\n"
                                        + "acc +0\n"
                                        + "nop -426\n"
                                        + "acc +22\n"
                                        + "acc -6\n"
                                        + "jmp -83\n"
                                        + "acc +12\n"
                                        + "acc +43\n"
                                        + "acc +31\n"
                                        + "jmp -46\n"
                                        + "acc +27\n"
                                        + "acc +26\n"
                                        + "acc +24\n"
                                        + "acc -12\n"
                                        + "jmp +118\n"
                                        + "nop -88\n"
                                        + "nop -251\n"
                                        + "acc -15\n"
                                        + "acc +3\n"
                                        + "jmp -450\n"
                                        + "acc +11\n"
                                        + "acc +19\n"
                                        + "jmp -406\n"
                                        + "acc +39\n"
                                        + "jmp -45\n"
                                        + "acc +40\n"
                                        + "acc -7\n"
                                        + "acc +22\n"
                                        + "nop -329\n"
                                        + "jmp -160\n"
                                        + "jmp +80\n"
                                        + "acc +0\n"
                                        + "acc -4\n"
                                        + "jmp +31\n"
                                        + "acc +11\n"
                                        + "acc -2\n"
                                        + "acc +3\n"
                                        + "acc +48\n"
                                        + "jmp -366\n"
                                        + "acc -16\n"
                                        + "jmp -345\n"
                                        + "jmp -259\n"
                                        + "acc -8\n"
                                        + "acc +29\n"
                                        + "acc +4\n"
                                        + "acc +2\n"
                                        + "jmp -208\n"
                                        + "acc -6\n"
                                        + "acc +48\n"
                                        + "acc -3\n"
                                        + "jmp +82\n"
                                        + "acc +1\n"
                                        + "acc +47\n"
                                        + "acc +40\n"
                                        + "acc +31\n"
                                        + "jmp -214\n"
                                        + "acc +10\n"
                                        + "jmp -328\n"
                                        + "acc -18\n"
                                        + "acc +39\n"
                                        + "jmp +2\n"
                                        + "jmp -403\n"
                                        + "jmp +48\n"
                                        + "jmp +19\n"
                                        + "jmp -468\n"
                                        + "jmp -397\n"
                                        + "acc +40\n"
                                        + "acc +39\n"
                                        + "acc +22\n"
                                        + "jmp +1\n"
                                        + "jmp -305\n"
                                        + "acc +22\n"
                                        + "acc -5\n"
                                        + "acc +23\n"
                                        + "jmp -399\n"
                                        + "acc +21\n"
                                        + "jmp +17\n"
                                        + "nop -239\n"
                                        + "acc +0\n"
                                        + "acc +29\n"
                                        + "acc +2\n"
                                        + "jmp -56\n"
                                        + "acc -14\n"
                                        + "acc +23\n"
                                        + "jmp -375\n"
                                        + "jmp -450\n"
                                        + "nop +1\n"
                                        + "jmp -29\n"
                                        + "jmp -208\n"
                                        + "nop +50\n"
                                        + "jmp -468\n"
                                        + "acc +3\n"
                                        + "jmp +5\n"
                                        + "jmp -347\n"
                                        + "acc +21\n"
                                        + "acc +35\n"
                                        + "jmp -527\n"
                                        + "acc -4\n"
                                        + "acc -14\n"
                                        + "acc -5\n"
                                        + "nop +24\n"
                                        + "jmp -418\n"
                                        + "jmp +66\n"
                                        + "acc +8\n"
                                        + "acc -16\n"
                                        + "jmp -447\n"
                                        + "nop -324\n"
                                        + "acc +27\n"
                                        + "acc +4\n"
                                        + "jmp -393\n"
                                        + "jmp -276\n"
                                        + "jmp +1\n"
                                        + "acc +37\n"
                                        + "acc +15\n"
                                        + "nop -304\n"
                                        + "jmp -534\n"
                                        + "acc -16\n"
                                        + "nop -514\n"
                                        + "acc +11\n"
                                        + "jmp -331\n"
                                        + "nop -69\n"
                                        + "acc +14\n"
                                        + "acc +44\n"
                                        + "jmp -125\n"
                                        + "acc +3\n"
                                        + "acc +5\n"
                                        + "acc +0\n"
                                        + "nop -381\n"
                                        + "jmp -440\n"
                                        + "acc +48\n"
                                        + "nop -561\n"
                                        + "jmp -543\n"
                                        + "acc -10\n"
                                        + "acc +44\n"
                                        + "acc -16\n"
                                        + "acc +45\n"
                                        + "jmp -177\n"
                                        + "acc +36\n"
                                        + "jmp -576\n"
                                        + "acc +36\n"
                                        + "acc +14\n"
                                        + "nop -323\n"
                                        + "jmp -163\n"
                                        + "jmp -118\n"
                                        + "acc -1\n"
                                        + "acc -14\n"
                                        + "acc +7\n"
                                        + "acc +7\n"
                                        + "jmp +11\n"
                                        + "acc +31\n"
                                        + "nop -309\n"
                                        + "jmp -109\n"
                                        + "acc +41\n"
                                        + "acc +11\n"
                                        + "acc +4\n"
                                        + "jmp -52\n"
                                        + "acc +9\n"
                                        + "acc +16\n"
                                        + "jmp -481\n"
                                        + "jmp -161\n"
                                        + "acc -8\n"
                                        + "acc +13\n"
                                        + "acc +16\n"
                                        + "jmp -488\n"
                                        + "acc +30\n"
                                        + "jmp -390\n"
                                        + "nop -313\n"
                                        + "jmp -333\n"
                                        + "jmp -44\n"
                                        + "acc +38\n"
                                        + "acc +33\n"
                                        + "acc +38\n"
                                        + "jmp -619\n"
                                        + "jmp -186\n"
                                        + "acc +49\n"
                                        + "acc -5\n"
                                        + "acc -16\n"
                                        + "jmp -214\n"
                                        + "acc +16\n"
                                        + "acc +35\n"
                                        + "nop -584\n"
                                        + "acc -12\n"
                                        + "jmp +1";
}
