package aoc2022;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Stack;
import java.util.regex.MatchResult;
import java.util.regex.Pattern;

public class Day5 {
    public static void main(String[] args) {
        a(TEST_INPUT);
        a(INPUT);
        b(TEST_INPUT);
        b(INPUT);
    }

    private static void b(String data) {
        Input input = parse(data);
        for (Move move : input.moves) {
            Stack<Character> from = input.stacks.get(move.from());
            Stack<Character> to = input.stacks.get(move.to());
            Stack<Character> tmp = new Stack<>();
            for (int i = 0; i < move.amount; i++) {
                char ch = from.pop();
                tmp.push(ch);
            }
            for (int i = 0; i < move.amount; i++) {
                char ch = tmp.pop();
                to.push(ch);
            }
        }
        input.stacks.entrySet().stream()
                    .sorted(Comparator.comparingInt(Entry::getKey))
                    .map(e->e.getValue().peek())
                    .forEach(System.out::print);
        System.out.println();
    }

    private static void a(String data) {
        Input input = parse(data);
        for (Move move : input.moves) {
            Stack<Character> from = input.stacks.get(move.from());
            Stack<Character> to = input.stacks.get(move.to());
            for (int i = 0; i < move.amount; i++) {
                char ch = from.pop();
                to.push(ch);
            }
        }
        input.stacks.entrySet().stream()
                    .sorted(Comparator.comparingInt(Entry::getKey))
                    .map(e->e.getValue().peek())
                    .forEach(System.out::print);
        System.out.println();
    }

    record Input(Map<Integer,Stack<Character>> stacks, List<Move> moves) {

    }

    record Move(int amount, int from, int to) {

    }

    static Input parse(String data) {
        String[] parts = data.split("\n\n");
        String[] cratesData = parts[0].split("\n");
        List<Integer> numericIxs = new ArrayList<>();
        String base = cratesData[cratesData.length - 1];
        for (int i = 0; i < base.length(); i++) {
            if (Character.isDigit(base.charAt(i))) {
                numericIxs.add(i);
            }
        }

        Map<Integer, Stack<Character>> stacks = new HashMap<>();
        for (Integer numericIx : numericIxs) {
            int nr = Character.digit(base.charAt(numericIx), 10);
            Stack<Character> stack = new Stack<>();
            stacks.put(nr, stack);
            for (int i = cratesData.length - 2; i >= 0; i--) {
                char ch = cratesData[i].charAt(numericIx);
                if (Character.isLetter(ch)) {
                    stack.push(ch);
                }
            }
        }

        Pattern numerics = Pattern.compile("\\d+");
        List<Move> moves = parts[1].lines().map(line -> {
                    int[] ints = numerics.matcher(line).results().map(MatchResult::group).mapToInt(Integer::parseInt).toArray();
                    return new Move(ints[0], ints[1], ints[2]);
                }
        ).toList();
        return new Input(stacks, moves);
    }

    private static final String TEST_INPUT = "    [D]    \n"
                                             + "[N] [C]    \n"
                                             + "[Z] [M] [P]\n"
                                             + " 1   2   3 \n"
                                             + "\n"
                                             + "move 1 from 2 to 1\n"
                                             + "move 3 from 1 to 3\n"
                                             + "move 2 from 2 to 1\n"
                                             + "move 1 from 1 to 2";

    private static final String INPUT = "[N]     [Q]         [N]            \n"
                                        + "[R]     [F] [Q]     [G] [M]        \n"
                                        + "[J]     [Z] [T]     [R] [H] [J]    \n"
                                        + "[T] [H] [G] [R]     [B] [N] [T]    \n"
                                        + "[Z] [J] [J] [G] [F] [Z] [S] [M]    \n"
                                        + "[B] [N] [N] [N] [Q] [W] [L] [Q] [S]\n"
                                        + "[D] [S] [R] [V] [T] [C] [C] [N] [G]\n"
                                        + "[F] [R] [C] [F] [L] [Q] [F] [D] [P]\n"
                                        + " 1   2   3   4   5   6   7   8   9 \n"
                                        + "\n"
                                        + "move 3 from 9 to 4\n"
                                        + "move 2 from 5 to 2\n"
                                        + "move 8 from 1 to 9\n"
                                        + "move 4 from 7 to 1\n"
                                        + "move 5 from 3 to 8\n"
                                        + "move 3 from 3 to 7\n"
                                        + "move 11 from 8 to 3\n"
                                        + "move 7 from 3 to 6\n"
                                        + "move 2 from 5 to 9\n"
                                        + "move 3 from 1 to 6\n"
                                        + "move 6 from 2 to 4\n"
                                        + "move 6 from 7 to 5\n"
                                        + "move 1 from 6 to 1\n"
                                        + "move 1 from 9 to 4\n"
                                        + "move 16 from 4 to 9\n"
                                        + "move 2 from 1 to 2\n"
                                        + "move 1 from 4 to 6\n"
                                        + "move 1 from 3 to 7\n"
                                        + "move 2 from 2 to 4\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 22 from 9 to 8\n"
                                        + "move 1 from 6 to 3\n"
                                        + "move 18 from 8 to 5\n"
                                        + "move 3 from 8 to 2\n"
                                        + "move 3 from 2 to 9\n"
                                        + "move 13 from 6 to 7\n"
                                        + "move 1 from 6 to 7\n"
                                        + "move 4 from 3 to 6\n"
                                        + "move 2 from 6 to 3\n"
                                        + "move 2 from 3 to 8\n"
                                        + "move 3 from 7 to 8\n"
                                        + "move 14 from 5 to 2\n"
                                        + "move 3 from 2 to 5\n"
                                        + "move 2 from 8 to 4\n"
                                        + "move 4 from 8 to 6\n"
                                        + "move 4 from 6 to 4\n"
                                        + "move 11 from 5 to 2\n"
                                        + "move 3 from 9 to 2\n"
                                        + "move 7 from 2 to 3\n"
                                        + "move 11 from 7 to 2\n"
                                        + "move 1 from 5 to 7\n"
                                        + "move 5 from 6 to 8\n"
                                        + "move 30 from 2 to 7\n"
                                        + "move 23 from 7 to 2\n"
                                        + "move 4 from 3 to 4\n"
                                        + "move 3 from 9 to 6\n"
                                        + "move 4 from 8 to 2\n"
                                        + "move 1 from 8 to 2\n"
                                        + "move 2 from 7 to 9\n"
                                        + "move 4 from 2 to 3\n"
                                        + "move 1 from 5 to 9\n"
                                        + "move 6 from 4 to 7\n"
                                        + "move 5 from 3 to 6\n"
                                        + "move 1 from 3 to 6\n"
                                        + "move 1 from 9 to 2\n"
                                        + "move 16 from 2 to 5\n"
                                        + "move 7 from 7 to 6\n"
                                        + "move 9 from 2 to 1\n"
                                        + "move 2 from 1 to 4\n"
                                        + "move 8 from 5 to 3\n"
                                        + "move 5 from 7 to 4\n"
                                        + "move 1 from 9 to 8\n"
                                        + "move 9 from 3 to 6\n"
                                        + "move 25 from 6 to 8\n"
                                        + "move 2 from 9 to 5\n"
                                        + "move 3 from 4 to 2\n"
                                        + "move 7 from 4 to 1\n"
                                        + "move 1 from 8 to 7\n"
                                        + "move 6 from 5 to 2\n"
                                        + "move 11 from 8 to 5\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 10 from 1 to 2\n"
                                        + "move 6 from 5 to 1\n"
                                        + "move 1 from 4 to 2\n"
                                        + "move 13 from 8 to 1\n"
                                        + "move 17 from 1 to 2\n"
                                        + "move 5 from 1 to 9\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 1 from 1 to 3\n"
                                        + "move 1 from 3 to 6\n"
                                        + "move 1 from 9 to 3\n"
                                        + "move 2 from 4 to 5\n"
                                        + "move 1 from 4 to 8\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 8 from 5 to 7\n"
                                        + "move 1 from 8 to 1\n"
                                        + "move 7 from 7 to 6\n"
                                        + "move 2 from 1 to 2\n"
                                        + "move 1 from 3 to 6\n"
                                        + "move 2 from 5 to 4\n"
                                        + "move 8 from 2 to 1\n"
                                        + "move 1 from 9 to 7\n"
                                        + "move 1 from 5 to 1\n"
                                        + "move 2 from 7 to 3\n"
                                        + "move 2 from 3 to 7\n"
                                        + "move 2 from 7 to 8\n"
                                        + "move 2 from 1 to 5\n"
                                        + "move 3 from 9 to 2\n"
                                        + "move 2 from 8 to 9\n"
                                        + "move 1 from 9 to 2\n"
                                        + "move 1 from 9 to 8\n"
                                        + "move 1 from 8 to 7\n"
                                        + "move 6 from 6 to 5\n"
                                        + "move 1 from 6 to 2\n"
                                        + "move 2 from 4 to 5\n"
                                        + "move 2 from 6 to 8\n"
                                        + "move 1 from 7 to 1\n"
                                        + "move 2 from 8 to 4\n"
                                        + "move 11 from 2 to 5\n"
                                        + "move 18 from 5 to 6\n"
                                        + "move 6 from 2 to 6\n"
                                        + "move 10 from 2 to 7\n"
                                        + "move 1 from 4 to 3\n"
                                        + "move 7 from 2 to 8\n"
                                        + "move 7 from 1 to 4\n"
                                        + "move 6 from 7 to 8\n"
                                        + "move 2 from 7 to 3\n"
                                        + "move 8 from 4 to 7\n"
                                        + "move 1 from 1 to 3\n"
                                        + "move 1 from 2 to 1\n"
                                        + "move 4 from 7 to 1\n"
                                        + "move 4 from 1 to 3\n"
                                        + "move 2 from 3 to 9\n"
                                        + "move 2 from 5 to 4\n"
                                        + "move 1 from 2 to 1\n"
                                        + "move 2 from 1 to 5\n"
                                        + "move 1 from 3 to 1\n"
                                        + "move 2 from 5 to 2\n"
                                        + "move 1 from 2 to 6\n"
                                        + "move 5 from 7 to 4\n"
                                        + "move 1 from 1 to 2\n"
                                        + "move 10 from 8 to 1\n"
                                        + "move 2 from 2 to 7\n"
                                        + "move 2 from 7 to 1\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 1 from 5 to 7\n"
                                        + "move 3 from 8 to 7\n"
                                        + "move 3 from 3 to 6\n"
                                        + "move 3 from 7 to 1\n"
                                        + "move 5 from 1 to 4\n"
                                        + "move 1 from 7 to 6\n"
                                        + "move 22 from 6 to 3\n"
                                        + "move 2 from 6 to 2\n"
                                        + "move 19 from 3 to 4\n"
                                        + "move 15 from 4 to 8\n"
                                        + "move 9 from 8 to 4\n"
                                        + "move 5 from 6 to 8\n"
                                        + "move 2 from 2 to 8\n"
                                        + "move 2 from 9 to 4\n"
                                        + "move 7 from 1 to 5\n"
                                        + "move 1 from 1 to 3\n"
                                        + "move 1 from 9 to 7\n"
                                        + "move 5 from 8 to 3\n"
                                        + "move 4 from 8 to 1\n"
                                        + "move 5 from 1 to 5\n"
                                        + "move 10 from 4 to 3\n"
                                        + "move 3 from 4 to 2\n"
                                        + "move 2 from 8 to 3\n"
                                        + "move 12 from 4 to 8\n"
                                        + "move 1 from 7 to 6\n"
                                        + "move 3 from 2 to 9\n"
                                        + "move 2 from 4 to 5\n"
                                        + "move 5 from 3 to 7\n"
                                        + "move 1 from 7 to 2\n"
                                        + "move 1 from 1 to 6\n"
                                        + "move 1 from 7 to 2\n"
                                        + "move 15 from 3 to 8\n"
                                        + "move 10 from 5 to 6\n"
                                        + "move 3 from 7 to 8\n"
                                        + "move 1 from 5 to 8\n"
                                        + "move 1 from 2 to 3\n"
                                        + "move 7 from 6 to 1\n"
                                        + "move 3 from 5 to 3\n"
                                        + "move 5 from 3 to 5\n"
                                        + "move 3 from 5 to 4\n"
                                        + "move 2 from 4 to 9\n"
                                        + "move 2 from 3 to 5\n"
                                        + "move 14 from 8 to 5\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 16 from 5 to 3\n"
                                        + "move 16 from 3 to 6\n"
                                        + "move 2 from 9 to 8\n"
                                        + "move 21 from 6 to 7\n"
                                        + "move 2 from 1 to 7\n"
                                        + "move 1 from 2 to 7\n"
                                        + "move 4 from 1 to 7\n"
                                        + "move 1 from 4 to 7\n"
                                        + "move 16 from 8 to 5\n"
                                        + "move 20 from 7 to 4\n"
                                        + "move 1 from 9 to 8\n"
                                        + "move 1 from 7 to 4\n"
                                        + "move 3 from 8 to 6\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 2 from 1 to 4\n"
                                        + "move 2 from 5 to 2\n"
                                        + "move 5 from 4 to 7\n"
                                        + "move 1 from 6 to 9\n"
                                        + "move 11 from 7 to 6\n"
                                        + "move 2 from 7 to 5\n"
                                        + "move 12 from 6 to 2\n"
                                        + "move 13 from 2 to 1\n"
                                        + "move 1 from 2 to 3\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 6 from 4 to 1\n"
                                        + "move 1 from 6 to 7\n"
                                        + "move 7 from 4 to 9\n"
                                        + "move 8 from 9 to 3\n"
                                        + "move 2 from 8 to 3\n"
                                        + "move 10 from 5 to 4\n"
                                        + "move 11 from 1 to 8\n"
                                        + "move 1 from 1 to 3\n"
                                        + "move 5 from 1 to 8\n"
                                        + "move 8 from 5 to 6\n"
                                        + "move 13 from 8 to 9\n"
                                        + "move 12 from 3 to 5\n"
                                        + "move 12 from 5 to 9\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 1 from 1 to 2\n"
                                        + "move 1 from 1 to 4\n"
                                        + "move 3 from 8 to 5\n"
                                        + "move 1 from 2 to 5\n"
                                        + "move 1 from 4 to 8\n"
                                        + "move 5 from 6 to 3\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 13 from 4 to 7\n"
                                        + "move 3 from 7 to 6\n"
                                        + "move 1 from 1 to 4\n"
                                        + "move 4 from 4 to 2\n"
                                        + "move 1 from 6 to 3\n"
                                        + "move 2 from 5 to 9\n"
                                        + "move 2 from 5 to 9\n"
                                        + "move 1 from 4 to 8\n"
                                        + "move 6 from 9 to 4\n"
                                        + "move 22 from 9 to 2\n"
                                        + "move 8 from 7 to 4\n"
                                        + "move 7 from 2 to 1\n"
                                        + "move 3 from 3 to 8\n"
                                        + "move 2 from 6 to 7\n"
                                        + "move 14 from 4 to 2\n"
                                        + "move 2 from 6 to 1\n"
                                        + "move 1 from 8 to 7\n"
                                        + "move 3 from 3 to 9\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 3 from 1 to 9\n"
                                        + "move 3 from 9 to 3\n"
                                        + "move 31 from 2 to 8\n"
                                        + "move 8 from 8 to 4\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 9 from 4 to 5\n"
                                        + "move 7 from 5 to 6\n"
                                        + "move 2 from 5 to 1\n"
                                        + "move 1 from 2 to 1\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 1 from 2 to 9\n"
                                        + "move 2 from 6 to 4\n"
                                        + "move 4 from 7 to 4\n"
                                        + "move 4 from 9 to 8\n"
                                        + "move 6 from 4 to 1\n"
                                        + "move 1 from 3 to 2\n"
                                        + "move 1 from 3 to 6\n"
                                        + "move 1 from 9 to 2\n"
                                        + "move 2 from 2 to 4\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 1 from 3 to 1\n"
                                        + "move 17 from 1 to 9\n"
                                        + "move 4 from 6 to 2\n"
                                        + "move 1 from 9 to 7\n"
                                        + "move 4 from 9 to 7\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 3 from 7 to 6\n"
                                        + "move 1 from 4 to 9\n"
                                        + "move 10 from 8 to 5\n"
                                        + "move 6 from 6 to 5\n"
                                        + "move 1 from 7 to 2\n"
                                        + "move 1 from 1 to 4\n"
                                        + "move 1 from 4 to 5\n"
                                        + "move 9 from 8 to 3\n"
                                        + "move 4 from 3 to 9\n"
                                        + "move 1 from 4 to 6\n"
                                        + "move 1 from 6 to 5\n"
                                        + "move 1 from 4 to 8\n"
                                        + "move 2 from 3 to 8\n"
                                        + "move 1 from 3 to 8\n"
                                        + "move 3 from 8 to 9\n"
                                        + "move 5 from 2 to 9\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 5 from 8 to 7\n"
                                        + "move 3 from 8 to 4\n"
                                        + "move 2 from 8 to 5\n"
                                        + "move 24 from 9 to 7\n"
                                        + "move 1 from 3 to 5\n"
                                        + "move 2 from 9 to 4\n"
                                        + "move 22 from 7 to 9\n"
                                        + "move 1 from 3 to 4\n"
                                        + "move 6 from 4 to 6\n"
                                        + "move 4 from 6 to 7\n"
                                        + "move 10 from 5 to 3\n"
                                        + "move 8 from 3 to 5\n"
                                        + "move 2 from 3 to 4\n"
                                        + "move 2 from 4 to 6\n"
                                        + "move 10 from 7 to 3\n"
                                        + "move 21 from 9 to 1\n"
                                        + "move 2 from 3 to 4\n"
                                        + "move 4 from 3 to 8\n"
                                        + "move 2 from 4 to 8\n"
                                        + "move 1 from 7 to 8\n"
                                        + "move 4 from 6 to 8\n"
                                        + "move 3 from 5 to 4\n"
                                        + "move 8 from 8 to 2\n"
                                        + "move 18 from 1 to 6\n"
                                        + "move 3 from 4 to 1\n"
                                        + "move 1 from 2 to 8\n"
                                        + "move 5 from 1 to 8\n"
                                        + "move 3 from 3 to 6\n"
                                        + "move 3 from 2 to 9\n"
                                        + "move 3 from 8 to 1\n"
                                        + "move 11 from 5 to 2\n"
                                        + "move 3 from 8 to 7\n"
                                        + "move 10 from 2 to 9\n"
                                        + "move 1 from 7 to 9\n"
                                        + "move 3 from 8 to 1\n"
                                        + "move 2 from 7 to 8\n"
                                        + "move 6 from 9 to 5\n"
                                        + "move 4 from 2 to 8\n"
                                        + "move 8 from 5 to 8\n"
                                        + "move 1 from 3 to 7\n"
                                        + "move 2 from 5 to 6\n"
                                        + "move 3 from 1 to 6\n"
                                        + "move 2 from 1 to 6\n"
                                        + "move 4 from 9 to 8\n"
                                        + "move 4 from 9 to 8\n"
                                        + "move 1 from 9 to 4\n"
                                        + "move 9 from 6 to 9\n"
                                        + "move 16 from 6 to 9\n"
                                        + "move 1 from 4 to 7\n"
                                        + "move 1 from 2 to 9\n"
                                        + "move 5 from 8 to 5\n"
                                        + "move 4 from 5 to 1\n"
                                        + "move 6 from 1 to 7\n"
                                        + "move 12 from 8 to 4\n"
                                        + "move 5 from 8 to 1\n"
                                        + "move 6 from 9 to 3\n"
                                        + "move 1 from 1 to 6\n"
                                        + "move 2 from 5 to 8\n"
                                        + "move 12 from 4 to 7\n"
                                        + "move 2 from 8 to 4\n"
                                        + "move 1 from 4 to 8\n"
                                        + "move 1 from 7 to 6\n"
                                        + "move 1 from 4 to 6\n"
                                        + "move 14 from 7 to 1\n"
                                        + "move 3 from 3 to 2\n"
                                        + "move 7 from 9 to 7\n"
                                        + "move 3 from 3 to 5\n"
                                        + "move 15 from 1 to 2\n"
                                        + "move 2 from 5 to 9\n"
                                        + "move 1 from 8 to 9\n"
                                        + "move 16 from 9 to 1\n"
                                        + "move 1 from 5 to 9\n"
                                        + "move 5 from 6 to 2\n"
                                        + "move 12 from 7 to 2\n"
                                        + "move 20 from 2 to 6\n"
                                        + "move 10 from 2 to 6\n"
                                        + "move 11 from 1 to 7\n"
                                        + "move 2 from 7 to 4\n"
                                        + "move 2 from 2 to 5\n"
                                        + "move 1 from 2 to 3\n"
                                        + "move 2 from 5 to 6\n"
                                        + "move 1 from 9 to 5\n"
                                        + "move 1 from 5 to 9\n"
                                        + "move 25 from 6 to 7\n"
                                        + "move 25 from 7 to 6\n"
                                        + "move 1 from 3 to 1\n"
                                        + "move 1 from 2 to 5\n"
                                        + "move 1 from 4 to 3\n"
                                        + "move 33 from 6 to 3\n"
                                        + "move 1 from 9 to 5\n"
                                        + "move 2 from 3 to 5\n"
                                        + "move 28 from 3 to 9\n"
                                        + "move 5 from 1 to 9\n"
                                        + "move 4 from 1 to 8\n"
                                        + "move 2 from 3 to 2\n"
                                        + "move 2 from 8 to 1\n"
                                        + "move 1 from 4 to 6\n"
                                        + "move 3 from 5 to 3\n"
                                        + "move 1 from 2 to 4\n"
                                        + "move 2 from 2 to 8\n"
                                        + "move 1 from 6 to 5\n"
                                        + "move 30 from 9 to 2\n"
                                        + "move 7 from 2 to 6\n"
                                        + "move 1 from 1 to 3\n"
                                        + "move 1 from 1 to 7\n"
                                        + "move 1 from 5 to 6\n"
                                        + "move 1 from 5 to 4\n"
                                        + "move 5 from 7 to 4\n"
                                        + "move 4 from 7 to 3\n"
                                        + "move 1 from 3 to 7\n"
                                        + "move 3 from 8 to 7\n"
                                        + "move 8 from 3 to 1\n"
                                        + "move 3 from 1 to 7\n"
                                        + "move 4 from 1 to 4\n"
                                        + "move 3 from 9 to 8\n"
                                        + "move 8 from 6 to 2\n"
                                        + "move 18 from 2 to 6\n"
                                        + "move 6 from 7 to 2\n"
                                        + "move 1 from 1 to 7\n"
                                        + "move 3 from 4 to 7\n"
                                        + "move 5 from 4 to 8\n"
                                        + "move 2 from 8 to 7\n"
                                        + "move 7 from 2 to 5\n"
                                        + "move 5 from 2 to 7\n"
                                        + "move 10 from 7 to 9\n"
                                        + "move 5 from 5 to 9\n"
                                        + "move 1 from 3 to 9\n"
                                        + "move 5 from 2 to 6\n"
                                        + "move 3 from 7 to 9\n"
                                        + "move 2 from 5 to 6\n"
                                        + "move 2 from 2 to 9\n"
                                        + "move 2 from 8 to 7\n"
                                        + "move 1 from 4 to 5\n"
                                        + "move 8 from 9 to 2\n"
                                        + "move 5 from 6 to 7\n"
                                        + "move 4 from 9 to 1\n"
                                        + "move 4 from 8 to 9\n"
                                        + "move 12 from 9 to 1\n"
                                        + "move 16 from 1 to 4\n"
                                        + "move 12 from 6 to 2\n"
                                        + "move 3 from 7 to 6\n"
                                        + "move 3 from 7 to 3\n"
                                        + "move 1 from 9 to 4\n"
                                        + "move 12 from 4 to 5\n"
                                        + "move 2 from 4 to 3\n"
                                        + "move 1 from 7 to 1\n"
                                        + "move 4 from 4 to 3\n"
                                        + "move 1 from 8 to 2\n"
                                        + "move 6 from 3 to 1\n"
                                        + "move 1 from 1 to 8\n"
                                        + "move 7 from 2 to 5\n"
                                        + "move 1 from 8 to 1\n"
                                        + "move 4 from 5 to 4\n"
                                        + "move 5 from 5 to 9\n"
                                        + "move 1 from 3 to 8\n"
                                        + "move 1 from 9 to 7\n"
                                        + "move 1 from 8 to 1\n"
                                        + "move 4 from 5 to 6\n"
                                        + "move 5 from 5 to 9\n"
                                        + "move 7 from 9 to 5\n"
                                        + "move 11 from 6 to 4\n"
                                        + "move 1 from 9 to 4\n"
                                        + "move 1 from 9 to 1\n"
                                        + "move 1 from 7 to 2\n"
                                        + "move 9 from 4 to 3\n"
                                        + "move 5 from 1 to 9\n"
                                        + "move 3 from 5 to 1\n"
                                        + "move 5 from 9 to 8\n"
                                        + "move 8 from 3 to 1\n"
                                        + "move 2 from 5 to 3\n"
                                        + "move 7 from 2 to 5\n"
                                        + "move 1 from 6 to 4\n"
                                        + "move 3 from 5 to 9\n"
                                        + "move 3 from 6 to 9\n"
                                        + "move 3 from 2 to 9\n"
                                        + "move 5 from 3 to 6\n"
                                        + "move 1 from 9 to 5\n"
                                        + "move 4 from 8 to 3\n"
                                        + "move 1 from 8 to 4\n"
                                        + "move 8 from 1 to 3\n"
                                        + "move 12 from 3 to 7\n"
                                        + "move 1 from 2 to 4\n"
                                        + "move 3 from 2 to 8\n"
                                        + "move 6 from 7 to 6\n"
                                        + "move 4 from 5 to 7\n"
                                        + "move 5 from 9 to 7\n"
                                        + "move 2 from 9 to 2\n"
                                        + "move 1 from 9 to 5\n"
                                        + "move 4 from 5 to 1\n"
                                        + "move 1 from 5 to 4\n"
                                        + "move 14 from 7 to 6\n"
                                        + "move 1 from 1 to 7\n"
                                        + "move 10 from 4 to 5\n"
                                        + "move 4 from 1 to 2\n"
                                        + "move 1 from 4 to 6\n"
                                        + "move 1 from 7 to 4\n"
                                        + "move 17 from 6 to 8\n"
                                        + "move 1 from 5 to 7\n"
                                        + "move 10 from 5 to 4\n"
                                        + "move 1 from 2 to 6\n"
                                        + "move 4 from 2 to 6\n"
                                        + "move 13 from 6 to 1\n"
                                        + "move 9 from 4 to 3\n"
                                        + "move 2 from 2 to 4\n"
                                        + "move 1 from 6 to 7\n"
                                        + "move 1 from 4 to 3\n"
                                        + "move 8 from 3 to 5\n"
                                        + "move 1 from 3 to 4\n"
                                        + "move 17 from 1 to 3\n"
                                        + "move 15 from 3 to 7\n"
                                        + "move 3 from 4 to 1\n"
                                        + "move 6 from 8 to 9\n"
                                        + "move 6 from 9 to 1\n"
                                        + "move 2 from 3 to 1\n"
                                        + "move 2 from 5 to 2\n"
                                        + "move 6 from 7 to 6\n"
                                        + "move 3 from 6 to 9";
}
