package aoc2025;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

public class Day11 {
    private static void a(Input input) {
        Map<String, Device> map = input.devices().stream().collect(Collectors.toMap(Device::name, d -> d));
        System.out.println(Explorer.numPaths(map, "you", "out"));
    }

    private static void b(Input input) {
        Map<String, Device> map = input.devices().stream().collect(Collectors.toMap(Device::name, d -> d));
        long svrFft = Explorer.numPaths(map, "svr", "fft", "svr", "dac", "out");
        long fftDec = Explorer.numPaths(map, "fft", "dac", "svr", "fft", "out");
        long decOut = Explorer.numPaths(map, "dac", "out", "svr", "fft", "dac");
        long cnt1 = svrFft * fftDec * decOut;

        long svrDec = Explorer.numPaths(map, "svr", "dac", "svr", "fft", "out");
        long decFft = Explorer.numPaths(map, "dac", "fft", "svr", "dac", "out");
        long fftOut = Explorer.numPaths(map, "fft", "out", "svr", "dac", "fft");
        long cnt2 = svrDec * decFft * fftOut;
        System.out.println(cnt1 + cnt2);
    }

    record Explorer(Map<String, Device> map, Map<Key, Long> cache, Set<String> blocked) {
        record Key(String from, String to) {}

        static long numPaths(Map<String, Device> map, String from, String to, String... blocked) {
            Explorer explorer = new Explorer(map, new HashMap<>(), Set.of(blocked));
            return explorer.countPaths(from, to);
        }

        private long countPaths(String from, String to) {
            if (from.equals(to)) {
                return 1;
            }
            Key key = new Key(from, to);
            Long cached = cache.get(key);
            if (cached == null) {
                cached = map.get(from).attached.stream()
                                               .filter(d -> !blocked.contains(d))
                                               .mapToLong(d -> countPaths(d, to))
                                               .sum();
                cache.put(key, cached);
            }
            return cached;
        }
    }

    record Device(String name, List<String> attached) {}

    record Input(List<Device> devices) {
        static Input parse(String input) {
            return new Input(input.lines().map(line -> {
                String name = line.substring(0, line.indexOf(':')).trim();
                String[] attached = line.substring(line.indexOf(':') + 1).trim().split(" ");
                return new Device(name, List.of(attached));
            }).toList());
        }
    }

    private static final String TEST_INPUT_2 = "svr: aaa bbb\n"
                                               + "aaa: fft\n"
                                               + "fft: ccc\n"
                                               + "bbb: tty\n"
                                               + "tty: ccc\n"
                                               + "ccc: ddd eee\n"
                                               + "ddd: hub\n"
                                               + "hub: fff\n"
                                               + "eee: dac\n"
                                               + "dac: fff\n"
                                               + "fff: ggg hhh\n"
                                               + "ggg: out\n"
                                               + "hhh: out";

    private static final String TEST_INPUT = "aaa: you hhh\n"
                                             + "you: bbb ccc\n"
                                             + "bbb: ddd eee\n"
                                             + "ccc: ddd eee fff\n"
                                             + "ddd: ggg\n"
                                             + "eee: out\n"
                                             + "fff: out\n"
                                             + "ggg: out\n"
                                             + "hhh: ccc fff iii\n"
                                             + "iii: out";

    private static final String INPUT = "wfc: ond mpw vsz\n"
                                        + "qxn: mow khk\n"
                                        + "nzf: rti sqv\n"
                                        + "ehm: von pgy fxk\n"
                                        + "nlt: pdl hwf\n"
                                        + "xqa: qvc cih\n"
                                        + "ghq: ren\n"
                                        + "jze: gbj\n"
                                        + "qrt: bug rxr plt cre vkd\n"
                                        + "vqt: kkx hbz ipe hiq\n"
                                        + "auk: out\n"
                                        + "vkq: lnb kyc\n"
                                        + "evj: jmy\n"
                                        + "ydi: goh gab tpj azd mlq fdi jom qii wyt\n"
                                        + "olh: qrt gbj\n"
                                        + "mmm: yfi dgv ppv wsf\n"
                                        + "zry: cne bqx nlt\n"
                                        + "lim: rlc gih\n"
                                        + "dac: ren cyv fnu\n"
                                        + "ufv: llo ydi\n"
                                        + "bkv: out\n"
                                        + "zne: dja jlj bzj wfc gms\n"
                                        + "gea: kwy stx kxt xmj\n"
                                        + "vjp: ngk\n"
                                        + "zpy: olh\n"
                                        + "gzb: zkz pti dog\n"
                                        + "hiq: sdq veq wss qxn whx\n"
                                        + "zeo: jci inl\n"
                                        + "lqm: lnb kyc\n"
                                        + "maq: ysa bft hcm\n"
                                        + "evv: lnb\n"
                                        + "ujm: udx uvu ntx ehm\n"
                                        + "may: toh\n"
                                        + "rin: ltg\n"
                                        + "vcs: yer\n"
                                        + "uop: xnm\n"
                                        + "fxk: hiq kkx hbz ipe\n"
                                        + "kqv: jpt rxd\n"
                                        + "nwx: kkx fnd hbz ipe\n"
                                        + "seq: uvu udx\n"
                                        + "iez: out\n"
                                        + "sii: vnk\n"
                                        + "you: fuz kat zup ffd kzl dpd rtn ftr qno\n"
                                        + "msu: you\n"
                                        + "huw: maq omi\n"
                                        + "qop: yfr fpt xar fzq\n"
                                        + "mcp: olh jkl\n"
                                        + "xzq: inl\n"
                                        + "ejj: nqh mmm\n"
                                        + "juq: tmi gzb zpk nxw\n"
                                        + "yrn: vnk\n"
                                        + "jdm: vye\n"
                                        + "fev: xot tez\n"
                                        + "wss: wyf\n"
                                        + "phg: xrc hcm bft\n"
                                        + "cpn: nsz upq tuc\n"
                                        + "jds: gpx\n"
                                        + "eca: pvz\n"
                                        + "qqm: fbj mtv sbo zwu\n"
                                        + "kkx: lci jcd pgv zry wqb veq doj hrm fli sdq\n"
                                        + "yqr: goy fnu\n"
                                        + "uvu: fxk czo\n"
                                        + "ufe: hiq kkx ipe hbz\n"
                                        + "qvc: yew nhj yag hnf jge\n"
                                        + "mbd: yzg rcm\n"
                                        + "bfy: xqd nzf\n"
                                        + "ral: jmy qbv rtk\n"
                                        + "cgh: qks xot alh\n"
                                        + "hwr: xar fzq\n"
                                        + "vvg: sym wdp khl\n"
                                        + "ofr: qhc\n"
                                        + "izc: dxc upp\n"
                                        + "jcd: khk cmh mow\n"
                                        + "xmj: wyc ygz\n"
                                        + "xqd: sqv rti ufs\n"
                                        + "htj: yqc tkl glz\n"
                                        + "kmo: kzi\n"
                                        + "piz: uyw yma pcg\n"
                                        + "zge: zag\n"
                                        + "vfm: kvk\n"
                                        + "uyw: obh\n"
                                        + "jom: zdm frc ojx jrd fjw\n"
                                        + "khk: bxi\n"
                                        + "fpt: pgl wvy\n"
                                        + "thw: lnb you\n"
                                        + "upq: uwr\n"
                                        + "kxd: zfc vex cxd tnl\n"
                                        + "rcm: toh hzk\n"
                                        + "mpw: zvf llo ydi\n"
                                        + "bep: ugq\n"
                                        + "pih: kxd jdx grs\n"
                                        + "yyr: sja fye\n"
                                        + "kic: ffp eeo wjb\n"
                                        + "jnx: wvy\n"
                                        + "eav: vnw lbn lpe\n"
                                        + "stx: ygz ngo bgs\n"
                                        + "nhj: fnd kkx hiq\n"
                                        + "bzj: ond mpw vsz\n"
                                        + "xsv: bxf zus wag rxu\n"
                                        + "ffd: vjp\n"
                                        + "vnw: enr ikg krf\n"
                                        + "agq: ofv\n"
                                        + "doj: zwu mtv\n"
                                        + "qew: nne fhl ahb\n"
                                        + "wnq: uvu ehm\n"
                                        + "ftr: xjl viv\n"
                                        + "gnm: tul jtm fft\n"
                                        + "veq: bqx\n"
                                        + "ily: vnk\n"
                                        + "bxi: bxf wag wtf\n"
                                        + "esu: otj lzl cgh\n"
                                        + "khl: kyn\n"
                                        + "goy: lnb you\n"
                                        + "mrd: you\n"
                                        + "ikt: ipe hiq\n"
                                        + "jci: xrc hcm\n"
                                        + "egf: jno rmv\n"
                                        + "ezq: may\n"
                                        + "vsg: qvc jgx\n"
                                        + "zfm: oag apc blg\n"
                                        + "ydr: xrc hcm\n"
                                        + "nly: llo zvf\n"
                                        + "xrc: vup mci xqa qhh vsg dqt vrt yyr vfm pxk nkv\n"
                                        + "uvb: nwx\n"
                                        + "ual: myr krv\n"
                                        + "dja: vsz mpw\n"
                                        + "qeb: kkx ipe hbz hiq\n"
                                        + "tys: jci rio\n"
                                        + "aib: tys zeo gnt\n"
                                        + "rtn: jpt vjp\n"
                                        + "jnh: qvl byz xpt ibx\n"
                                        + "xjl: jds\n"
                                        + "ogd: aji ral use\n"
                                        + "sdq: yqr any bgj\n"
                                        + "pec: ipe\n"
                                        + "fqv: ugq\n"
                                        + "svb: kyc\n"
                                        + "rpw: itt qsb\n"
                                        + "gpx: nzf sgh xqd\n"
                                        + "mow: ohg bxi\n"
                                        + "csk: vvg hsf\n"
                                        + "von: ipe fnd\n"
                                        + "qhh: ibx\n"
                                        + "wmw: tqi ber doh\n"
                                        + "dqt: cih\n"
                                        + "yqc: bft hcm ysa\n"
                                        + "bsq: jdm kzi rir nxk\n"
                                        + "owb: lmw htj ofv\n"
                                        + "yag: kkx\n"
                                        + "fhl: sjq sbz\n"
                                        + "hyp: kyc you\n"
                                        + "tez: bkx\n"
                                        + "thx: ofr zeo\n"
                                        + "vfb: jde ofo\n"
                                        + "tuc: jrz vqt\n"
                                        + "joi: smo afx\n"
                                        + "sqs: nax jgl joi\n"
                                        + "wvy: toh vnk hzk\n"
                                        + "xlf: fnd\n"
                                        + "lay: vey pkr\n"
                                        + "gnt: jci rio qhc\n"
                                        + "rmv: uwf fqb\n"
                                        + "bwk: sja jiv\n"
                                        + "duc: you lnb kyc\n"
                                        + "fqb: out\n"
                                        + "uxn: jgx cih\n"
                                        + "gia: rxd vjp\n"
                                        + "kgl: die vkq\n"
                                        + "ufs: out\n"
                                        + "kvy: zua\n"
                                        + "thi: out\n"
                                        + "wsf: twk\n"
                                        + "oag: mym zua\n"
                                        + "bxf: vin msu loy\n"
                                        + "gxy: jds smg xqh\n"
                                        + "hzl: egf inc\n"
                                        + "zup: ejj\n"
                                        + "kml: uvb myr\n"
                                        + "deb: wlw cpn dka\n"
                                        + "xjb: wkv ejj qpn\n"
                                        + "nnk: ugk\n"
                                        + "lzm: jjv\n"
                                        + "bum: upk shw egy\n"
                                        + "dlb: sii hay ltg rgb\n"
                                        + "jrd: phg kou nql\n"
                                        + "nkv: lvv upp dxc\n"
                                        + "gab: ztn cdj\n"
                                        + "wyc: pkr qpq vey\n"
                                        + "jta: kkx fnd hbz ipe\n"
                                        + "alh: bkx ltx hze\n"
                                        + "wlw: tuc\n"
                                        + "uvh: ydi zvf llo\n"
                                        + "igw: qvl byz\n"
                                        + "uep: aib\n"
                                        + "lpe: ikg enr krf crd\n"
                                        + "vda: rlc gih xvx\n"
                                        + "qno: xmj kxt omo stx kwy\n"
                                        + "qii: frc fjw\n"
                                        + "jdx: tnl fum vex\n"
                                        + "wkv: nlc rje nqh\n"
                                        + "qhj: jjv\n"
                                        + "fpk: xvx\n"
                                        + "rxu: loy msu vin lqm\n"
                                        + "wey: mjb qew rcv ora oad yqa ptp tvr fcu zgf bcz dmd jca dmw gfv itk pka\n"
                                        + "ahf: giq qvw ajg\n"
                                        + "jgl: afx zfk smo kgl\n"
                                        + "lmw: glz tkl\n"
                                        + "gwf: vnk toh\n"
                                        + "fpr: hcm ysa\n"
                                        + "hze: qsp uyb\n"
                                        + "xar: sha wvy\n"
                                        + "yun: ojx zdm\n"
                                        + "esd: vnw cbv lpe\n"
                                        + "hnf: fnd kkx\n"
                                        + "omi: bft hcm ysa xrc\n"
                                        + "cmh: ohg uih xsv\n"
                                        + "sao: out\n"
                                        + "noa: bkv fct cqx\n"
                                        + "mlq: tlg\n"
                                        + "ngo: qpq vey\n"
                                        + "jge: hiq hbz fnd kkx\n"
                                        + "fba: you kyc\n"
                                        + "nsz: vqt jrz\n"
                                        + "qkr: thi iez\n"
                                        + "cqx: out\n"
                                        + "ugq: nnn\n"
                                        + "wxo: lmw htj\n"
                                        + "uwr: kkx fnd ipe\n"
                                        + "rsz: jpt rxd\n"
                                        + "mjb: bff nze\n"
                                        + "xun: llo zvf ydi jhh\n"
                                        + "dpn: xnx\n"
                                        + "agk: wpb gnm ugk\n"
                                        + "ptp: jcw fpk vda lim\n"
                                        + "euq: auk\n"
                                        + "oad: fhl ahb yep nne\n"
                                        + "dwr: jnx yfr\n"
                                        + "kux: eqw\n"
                                        + "tpj: fjw zdm frc\n"
                                        + "qpq: noa ijb\n"
                                        + "vsz: jhh ydi\n"
                                        + "oaa: tmp ehl\n"
                                        + "mci: dxc lvv\n"
                                        + "lgn: eca esv egf inc\n"
                                        + "axf: xrb dhn vsl fxs\n"
                                        + "qsp: auk doh\n"
                                        + "jtm: jdx htf\n"
                                        + "kpy: eeo ffp\n"
                                        + "cwo: jze jkl\n"
                                        + "pgv: cne\n"
                                        + "lci: joi jgl\n"
                                        + "crd: zvf llo\n"
                                        + "qks: hze\n"
                                        + "uih: wtf zus\n"
                                        + "krv: qeb\n"
                                        + "vtg: hzk vnk toh\n"
                                        + "ldy: ysa xrc bft hcm\n"
                                        + "ykn: llo ydi jhh\n"
                                        + "obh: vyp yer\n"
                                        + "rti: out\n"
                                        + "twk: vsl fxs xrb dhn pkx\n"
                                        + "lxk: htj lmw\n"
                                        + "any: goy fnu\n"
                                        + "zua: rrf jde ofo\n"
                                        + "inl: ysa\n"
                                        + "ljh: aji\n"
                                        + "vhk: vnw lpe cbv\n"
                                        + "hcm: nkv igw xqa izc awr\n"
                                        + "sgh: rti sqv\n"
                                        + "ypr: fxs\n"
                                        + "mdu: sii ltg\n"
                                        + "hrm: nax\n"
                                        + "kfo: pka nek dmd jca gfv dmw itk tvr juq zgf mjb qew bum oad ora\n"
                                        + "zpk: oaa\n"
                                        + "enr: llo ydi\n"
                                        + "gfm: ufe\n"
                                        + "rct: jjv wnu\n"
                                        + "oqj: fqb\n"
                                        + "pka: zpk ykm tmi gzb\n"
                                        + "ove: dja jlj wfc gms\n"
                                        + "gyr: wpb\n"
                                        + "yew: kkx ipe hbz hiq\n"
                                        + "fnd: doj veq gey wqb fjr ppw whx\n"
                                        + "mgv: krv uvb\n"
                                        + "blg: zua vfb mck\n"
                                        + "ofv: tkl glz sxb\n"
                                        + "tkt: ord\n"
                                        + "eqw: hzk\n"
                                        + "ead: aib thx htk\n"
                                        + "vnk: jvj agk eav vsk tql vhk zne zge rct ogd dpn nuo ljh qhj nfv ove qck tvi qnw vmf lzm nnk gjj oxu\n"
                                        + "ojx: nql phg\n"
                                        + "dag: lnb you\n"
                                        + "nlk: cgh\n"
                                        + "jlj: vsz ond\n"
                                        + "rrf: fpr tde maq\n"
                                        + "cko: jjv wnu gcq\n"
                                        + "plm: lug cwo\n"
                                        + "sjq: ezq ahf owp\n"
                                        + "vin: you kyc lnb\n"
                                        + "ldb: kvy apc tlg oag\n"
                                        + "ltx: euq wmw uyb tmg qsp\n"
                                        + "yep: sbz sjq\n"
                                        + "fxs: out\n"
                                        + "ehl: luj rcm yzg\n"
                                        + "tmi: imc zkz pti oaa\n"
                                        + "jcw: xvx\n"
                                        + "syi: kwy omo kxt\n"
                                        + "lvv: zgq xlf ikt\n"
                                        + "tlg: vfb\n"
                                        + "bfl: yrn\n"
                                        + "dtz: otj fev cgh lzl\n"
                                        + "dxc: xlf zgq\n"
                                        + "ylj: iab kic\n"
                                        + "yfr: wvy\n"
                                        + "txz: ltg hay rgb\n"
                                        + "wbq: blg apc kvy\n"
                                        + "vkd: hcm\n"
                                        + "yyv: vtg\n"
                                        + "wft: etd hsf fqv vvg\n"
                                        + "bcz: qop dwr\n"
                                        + "vmf: gcq\n"
                                        + "qhc: bft hcm\n"
                                        + "grs: vex zfc tnl cxd fum\n"
                                        + "rjj: ntx uvu\n"
                                        + "wib: duc\n"
                                        + "acd: kyc\n"
                                        + "cbv: enr\n"
                                        + "cdj: rpw rja xnm dnb\n"
                                        + "jhh: zfm ead owb myy qii uep agq rji mlq fdi plm yun lxk goh vmc ldb gab tpj\n"
                                        + "bft: vfm izc vrt yyr igw dqt jnh vsg vel bwk uxn nkv pxk deb xqa mci awr vup fah\n"
                                        + "sym: kyn jdt\n"
                                        + "czo: fnd hbz\n"
                                        + "otj: alh xot qks\n"
                                        + "rcv: bff nze\n"
                                        + "tnl: zvf\n"
                                        + "jca: pyi kux\n"
                                        + "nsh: gxy\n"
                                        + "rxd: ngk hzl\n"
                                        + "zus: evv loy vin\n"
                                        + "zfk: hyp vkq\n"
                                        + "afx: vkq die mrd fba\n"
                                        + "flm: yqr dac ghq bgj\n"
                                        + "nne: sjq zev\n"
                                        + "ohg: wtf wag\n"
                                        + "dmd: xxk\n"
                                        + "yqa: pyi kux\n"
                                        + "omo: lay\n"
                                        + "krf: jhh\n"
                                        + "lnb: zwb piz nsh gea wef nlk fuz dtz gia kqv\n"
                                        + "knl: fyd uvu udx\n"
                                        + "fah: ylj\n"
                                        + "ffp: tfw pec\n"
                                        + "vel: wlw dka\n"
                                        + "qxd: van ulx qkr\n"
                                        + "zkz: tmp ehl\n"
                                        + "qvw: vnk\n"
                                        + "lzl: tez xot alh\n"
                                        + "llo: gab tpj wbq ldb vmc wxo wyt goh qtw lxk yun plm azd fdi rji agq myy owb zfm qii uep rry\n"
                                        + "doe: svb pdd duc\n"
                                        + "yje: qvw giq\n"
                                        + "zcu: jhh\n"
                                        + "ppv: ypr jdg axf\n"
                                        + "xnx: fqv\n"
                                        + "fli: doe vwj wib wyf\n"
                                        + "fcu: nne\n"
                                        + "plt: ysa hcm\n"
                                        + "xpt: kml ual mgv qrq\n"
                                        + "jde: tde fpr\n"
                                        + "jdg: dhn pkx vsl fxs\n"
                                        + "wnu: tkt kmo dyq\n"
                                        + "zwu: acd\n"
                                        + "fuz: kwy xmj\n"
                                        + "iab: sli\n"
                                        + "jjv: bsq dyq kmo nhd\n"
                                        + "kzi: vye ufv xun zcu\n"
                                        + "dog: kfe tmp kvo\n"
                                        + "dgv: axf jdg\n"
                                        + "wtf: loy\n"
                                        + "kwy: ygz\n"
                                        + "rgb: hzk toh\n"
                                        + "bqx: hwf pdl thw mqb dag\n"
                                        + "nax: zfk afx\n"
                                        + "gmw: kyc you\n"
                                        + "fte: yma\n"
                                        + "dhn: out\n"
                                        + "pdl: lnb\n"
                                        + "cne: mqb thw\n"
                                        + "nnn: zvf\n"
                                        + "lbn: ykn ikg\n"
                                        + "ahb: zev sjq\n"
                                        + "nze: jnx fpt xar\n"
                                        + "tvr: qop\n"
                                        + "ord: nly vye xun zcu\n"
                                        + "pdd: you lnb\n"
                                        + "qtw: kvy apc blg\n"
                                        + "dka: upq nsz\n"
                                        + "ofo: tde maq\n"
                                        + "viv: smg xqh\n"
                                        + "shw: dlb\n"
                                        + "dnb: itt\n"
                                        + "rtk: vjr uvh\n"
                                        + "tde: bft xrc\n"
                                        + "jrz: hbz\n"
                                        + "vqi: goo iab xkx kic\n"
                                        + "dyq: nxk rir jdm\n"
                                        + "lky: oad ora rcv bum mjb rpx zgf juq fcu tvr ptp itk gfv dmw jca pka nek iuz\n"
                                        + "nxk: xun zcu nly vye ufv\n"
                                        + "iib: thi jlm\n"
                                        + "vsk: wfc\n"
                                        + "ren: you kyc lnb\n"
                                        + "qsb: ldy\n"
                                        + "goo: gfm eeo ffp sli\n"
                                        + "rlt: cre plt vkd rxr\n"
                                        + "pyz: nsz tuc\n"
                                        + "nfv: upi\n"
                                        + "amu: sgh\n"
                                        + "yed: ghq dac yqr\n"
                                        + "qck: hap\n"
                                        + "tul: grs ymg\n"
                                        + "sha: toh\n"
                                        + "bkx: tmg euq\n"
                                        + "cyv: you lnb\n"
                                        + "ugk: pih jtm tul fft\n"
                                        + "tfw: hiq ipe kkx fnd\n"
                                        + "zfc: ydi\n"
                                        + "ykm: zkz pti imc\n"
                                        + "lug: jze jkl\n"
                                        + "tkl: hcm ysa xrc\n"
                                        + "sja: seq ujm knl rjj\n"
                                        + "yer: qkr iib ulx\n"
                                        + "aji: kbv jmy qbv rtk\n"
                                        + "mtv: gmw\n"
                                        + "wef: viv gxy xjl mdc\n"
                                        + "pfx: hiq fnd\n"
                                        + "nhm: qxd\n"
                                        + "svr: lky kfo bet wey\n"
                                        + "ntx: czo von pgy fxk\n"
                                        + "tvi: gms dja jlj\n"
                                        + "eeo: tfw ufe pfx pec jwa\n"
                                        + "myr: qeb jta nwx\n"
                                        + "nhd: nxk jdm\n"
                                        + "vwj: duc svb\n"
                                        + "gfv: pyi yyv\n"
                                        + "ora: ahb fhl\n"
                                        + "jlm: out\n"
                                        + "esv: rmv jno pvz\n"
                                        + "pok: vnk\n"
                                        + "xxk: rin txz\n"
                                        + "htk: zeo ofr tys xzq gnt\n"
                                        + "ysa: fah qhh xqa vup mci nkv uxn vel bwk pxk igw vrt yyr ngj izc vfm jnh dqt\n"
                                        + "zgf: hwr bff qop dwr\n"
                                        + "sgc: evj\n"
                                        + "zdm: phg kou\n"
                                        + "qvl: ual kml mgv\n"
                                        + "htf: tnl cxd zfc vex\n"
                                        + "nxw: dog pti zkz imc\n"
                                        + "hwd: bkv sao cqx fct\n"
                                        + "xkx: eeo gfm\n"
                                        + "kvo: rcm gwf luj\n"
                                        + "bgs: pkr qpq\n"
                                        + "fct: out\n"
                                        + "mrl: cmh\n"
                                        + "jkl: qrt rlt gbj\n"
                                        + "fdi: thx\n"
                                        + "rje: yfi dgv auw\n"
                                        + "use: jmy qbv rtk\n"
                                        + "bff: fzq\n"
                                        + "xqh: bfy\n"
                                        + "vup: ylj vqi\n"
                                        + "mkh: hcm bft\n"
                                        + "jmy: vjr emc\n"
                                        + "gbj: vkd rxr bug\n"
                                        + "azd: qgv zpy lug\n"
                                        + "mck: ofo jde huw rrf\n"
                                        + "upp: ikt zgq\n"
                                        + "wjb: jwa pfx\n"
                                        + "yfi: twk jdg\n"
                                        + "apc: vfb zua mym\n"
                                        + "frc: nql\n"
                                        + "rji: zpy cwo lug\n"
                                        + "upk: rin mdu\n"
                                        + "ngk: inc egf esv\n"
                                        + "auw: jdg ypr twk\n"
                                        + "pkr: noa hwd\n"
                                        + "sli: ufe tfw\n"
                                        + "jwa: hbz fnd\n"
                                        + "egy: mdu dlb rin\n"
                                        + "fye: rjj wnq seq\n"
                                        + "vey: hwd ijb noa\n"
                                        + "hsf: khl wdp sym\n"
                                        + "bgj: cyv\n"
                                        + "wpb: lts fft jtm tul\n"
                                        + "cxd: zvf\n"
                                        + "xot: bkx ltx\n"
                                        + "itt: egq mkh ydr\n"
                                        + "qnw: lbn vnw cbv\n"
                                        + "jvj: ral use\n"
                                        + "pyi: eqw ily vtg\n"
                                        + "oxu: zag wft xnx csk\n"
                                        + "rry: ztn cdj\n"
                                        + "smg: gpx bfy amu\n"
                                        + "fzq: sha\n"
                                        + "yma: nhm vcs\n"
                                        + "hay: toh vnk\n"
                                        + "egq: ysa bft\n"
                                        + "upi: lts jtm\n"
                                        + "uyb: ber\n"
                                        + "vye: ydi jhh zvf\n"
                                        + "jpt: hzl lgn\n"
                                        + "ijb: cqx sao bkv\n"
                                        + "fbj: gmw acd\n"
                                        + "udx: czo von\n"
                                        + "rqt: kwy omo xmj\n"
                                        + "etd: ugq wdp\n"
                                        + "mym: jde huw rrf\n"
                                        + "ber: out\n"
                                        + "nqh: auw wsf dgv yfi\n"
                                        + "hwf: kyc\n"
                                        + "rir: ufv\n"
                                        + "ygz: vey\n"
                                        + "bug: hcm xrc ysa\n"
                                        + "jiv: wnq knl ujm\n"
                                        + "rlc: vnk toh\n"
                                        + "ltg: hzk toh\n"
                                        + "gjj: gnm upi wpb\n"
                                        + "uwf: out\n"
                                        + "ond: zvf ydi\n"
                                        + "wqb: fbj\n"
                                        + "ppw: doe\n"
                                        + "kyc: gea zwb fte rtn ftr rqt esu ffd hdx gia rsz kqv fuz syi piz wef qno xjb kat nlk zup dtz\n"
                                        + "byz: kml mgv qrq\n"
                                        + "wyf: svb pdd\n"
                                        + "vaq: egq ydr\n"
                                        + "fjw: nql phg\n"
                                        + "zev: ezq bfl ahf owp yje\n"
                                        + "zvf: mlq agq rji rry uep myy ead lxk qtw yun plm jom vmc wxo wyt tpj wbq ldb\n"
                                        + "xrb: out\n"
                                        + "rio: hcm bft ysa\n"
                                        + "imc: kfe\n"
                                        + "xnm: vaq itt\n"
                                        + "wyt: uop cdj ztn\n"
                                        + "ngj: wlw pyz\n"
                                        + "wag: msu\n"
                                        + "fnu: lnb you\n"
                                        + "kyn: jhh ydi llo\n"
                                        + "nuo: csk\n"
                                        + "tmp: luj pok rcm yzg\n"
                                        + "ipe: yed fjr flm sqs qxn lci qqm fli hrm mrl zry\n"
                                        + "ztn: rja rpw dnb xnm\n"
                                        + "iuz: jcw fpk vkv lim vda\n"
                                        + "nql: xrc ysa hcm bft\n"
                                        + "pvz: hid\n"
                                        + "pgy: kkx fnd hbz\n"
                                        + "ymg: cxd tnl\n"
                                        + "pgl: toh hzk\n"
                                        + "dmw: ahb nne\n"
                                        + "vjr: zvf jhh\n"
                                        + "vyp: ulx iib qkr\n"
                                        + "smo: mrd die vkq hyp\n"
                                        + "pkx: out\n"
                                        + "sbz: yje owp ahf bfl\n"
                                        + "tql: dja\n"
                                        + "dpd: cki wkv qpn\n"
                                        + "owp: giq\n"
                                        + "cih: nhj hnf jge\n"
                                        + "ikg: jhh llo\n"
                                        + "cre: xrc ysa bft\n"
                                        + "toh: ove tvi qck vmf qnw lzm nnk cko oxu gjj jvj eav agk vsk tql vhk sgc gyr esd zge zne rct ogd qhj ljh\n"
                                        + "tmg: ber auk doh\n"
                                        + "qpn: rje mmm nqh\n"
                                        + "bet: bcz dmd dmw itk iuz nek mjb rpx qew rcv oad ora yqa ptp tvr juq zgf\n"
                                        + "die: lnb\n"
                                        + "hzk: gjj nuo oxu nfv qhj lzm rct ogd dpn nnk vmf gyr sgc vhk zne ove agk vsk tvi qck\n"
                                        + "jgx: yag nhj yew hnf\n"
                                        + "mqb: lnb\n"
                                        + "zag: bep etd fqv\n"
                                        + "vrt: dxc\n"
                                        + "goh: lug qgv cwo\n"
                                        + "tqi: out\n"
                                        + "gms: mpw\n"
                                        + "gcq: bsq kmo nhd tkt\n"
                                        + "zgq: hbz fnd kkx\n"
                                        + "nek: tmi zpk ykm\n"
                                        + "rxr: hcm bft\n"
                                        + "lts: grs jdx kxd htf\n"
                                        + "jno: hid fqb\n"
                                        + "vvf: lnb\n"
                                        + "awr: sja jiv fye\n"
                                        + "kvk: kpy kic goo\n"
                                        + "pti: tmp kfe mbd\n"
                                        + "fum: jhh ydi llo zvf\n"
                                        + "fft: kxd htf\n"
                                        + "sbo: acd gmw vvf\n"
                                        + "glz: hcm xrc ysa\n"
                                        + "vmc: qgv cwo mcp lug\n"
                                        + "pxk: wlw cpn dka\n"
                                        + "kat: qpn\n"
                                        + "sxb: xrc ysa bft\n"
                                        + "hdx: pcg\n"
                                        + "rpx: xxk egy shw\n"
                                        + "emc: llo jhh\n"
                                        + "luj: toh\n"
                                        + "vsl: out\n"
                                        + "jdt: jhh ydi zvf\n"
                                        + "kxt: bgs\n"
                                        + "qgv: jze jkl olh\n"
                                        + "rja: vaq itt\n"
                                        + "inc: oqj pvz\n"
                                        + "vkv: rlc xvx\n"
                                        + "fyd: fxk pgy von\n"
                                        + "giq: toh hzk vnk\n"
                                        + "van: thi jlm\n"
                                        + "yzg: hzk vnk\n"
                                        + "xvx: hzk\n"
                                        + "kou: xrc ysa bft\n"
                                        + "qrq: uvb krv\n"
                                        + "kzl: viv mdc\n"
                                        + "fjr: joi\n"
                                        + "qbv: uvh emc\n"
                                        + "loy: you\n"
                                        + "pcg: nhm vcs\n"
                                        + "whx: nlt bqx cne\n"
                                        + "ajg: toh hzk\n"
                                        + "ulx: jlm iez\n"
                                        + "kfe: gwf yzg\n"
                                        + "ulb: qks xot tez\n"
                                        + "itk: vkv fpk jcw\n"
                                        + "cki: nlc\n"
                                        + "nlc: ppv\n"
                                        + "gih: vnk hzk\n"
                                        + "myy: htk\n"
                                        + "gey: cmh\n"
                                        + "doh: out\n"
                                        + "ibx: qrq\n"
                                        + "mdc: smg\n"
                                        + "hap: jmy\n"
                                        + "zwb: ulb\n"
                                        + "kbv: vjr uvh\n"
                                        + "hbz: sqs qxn jcd qqm yed\n"
                                        + "sqv: out\n"
                                        + "wdp: kyn nnn\n"
                                        + "vex: llo jhh ydi\n"
                                        + "hid: out";

    public static void main(String[] args) {
        Util.time(() -> a(Input.parse(TEST_INPUT)));
        Util.time(() -> a(Input.parse(INPUT)));
        Util.time(() -> b(Input.parse(TEST_INPUT_2)));
        Util.time(() -> b(Input.parse(INPUT)));
    }
}
