package aoc2024;

import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Queue;
import java.util.Set;

public class Day19 {
    private static void a(Input input) {
        System.out.println(input.designs.stream().filter(design -> canMatch(input.patterns, design)).count());
    }

    static boolean canMatch(List<String> patterns, String design) {
        Queue<String> queue = new LinkedList<>(List.of(""));
        Set<String> seen = new HashSet<>();
        while (!queue.isEmpty()) {
            String current = queue.poll();
            if (seen.add(current)) {
                for (String pattern : patterns) {
                    String next = current + pattern;
                    if (design.startsWith(next)) {
                        if (next.equals(design)) {
                            return true;
                        }
                        queue.add(next);
                    }
                }
            }
        }
        return false;
    }

    private static void b(Input input) {
        System.out.println(input.designs.stream()
                                        .map(d -> new MatchCounter(input.patterns, d))
                                        .mapToLong(mc -> mc.numMatch(""))
                                        .sum());
    }

    static class MatchCounter {
        final List<String> patterns;
        final String design;
        final Map<String, Long> prefixToCount = new HashMap<>();

        MatchCounter(List<String> patterns, String design) {
            this.patterns = patterns;
            this.design = design;
        }

        long numMatch(String prefix) {
            if (prefix.equals(design)) {
                return 1;
            }
            if (!prefixToCount.containsKey(prefix)) {
                long numMatches = 0;
                for (String pattern : patterns) {
                    String next = prefix + pattern;
                    if (design.startsWith(next)) {
                        numMatches += numMatch(next);
                    }
                }
                prefixToCount.put(prefix, numMatches);
            }
            return prefixToCount.get(prefix);
        }
    }

    record Input(List<String> patterns, List<String> designs) {
        static Input parse(String input) {
            String[] parts = input.split("\n\n");
            return new Input(List.of(parts[0].split(", ")), parts[1].lines().toList());
        }
    }

    private static final String TEST_INPUT = "r, wr, b, g, bwu, rb, gb, br\n"
                                             + "\n"
                                             + "brwrr\n"
                                             + "bggr\n"
                                             + "gbbr\n"
                                             + "rrbgbr\n"
                                             + "ubwu\n"
                                             + "bwurrg\n"
                                             + "brgr\n"
                                             + "bbrgwb";

    private static final String INPUT =
            "rwgw, ruwgb, urwbr, wu, uurbubr, gbbr, uwwb, rubgwu, wggwbwr, rugubuww, uw, rgru, rgrr, rrg, rbb, uurbrww, br, uwrwrwgb, bwbw, wgbu, wggu, urg, ugr, ugur, gurrbrr, ubgrruu, bb, rburguu, urgg, wggugggr, brww, bwwgr, wugub, grgg, ugw, grubw, gbwru, rww, wbu, ggwbu, ugurw, ggwb, uubuwgb, bbugw, rgg, wurr, bwbb, wburbb, rbrb, bbrwgw, gwbb, ubggr, gurr, rrr, rburg, uug, bbrubu, bwgu, gwug, guw, buwurgw, rruwggg, ubb, wwb, wbrg, wgr, wgrw, gubrr, rrwru, gbub, rbr, rwr, rubwu, ub, bgwr, gu, ggggwrbr, wrw, grg, rbuwu, bgbr, ugww, wrg, brwub, gruu, gbwbw, wubw, wur, grggwb, uuwuug, wug, rruuw, wgwg, uww, gbgu, rurr, gwguu, gwrwbw, guuww, rbugw, gg, uwbw, ubgrubur, wurrb, rgugurr, wrr, buggb, urwrb, ubuu, rgu, gwggb, uuu, uub, bruubb, bww, uwgb, rrubwg, ubwu, ugu, buwrrbwr, bbr, rbrww, ubuwg, bwwrr, gbwg, bw, gguugu, bgbbw, ggb, wrruuwbr, rug, uur, rgw, gbb, wuwg, r, guug, gwb, wbgr, bbbw, grwgwr, gwg, rurur, bubu, rguu, brb, ugbbbrr, wugrrr, bbw, bbru, bgrbubg, ubw, uruu, wgrgrwwr, bbwrugu, gbbbwur, rubbwbuw, wuwrwbu, brwbru, wub, rbrg, wwbwrbu, grbbu, ubbbwb, urw, gwuw, uu, urwugu, bgw, gw, rbwwwurg, gubr, bbu, rur, rburwgr, gwwgr, gb, rbur, rbw, ug, wurur, gbbrrb, ruuuwugr, wwrgug, gbrugu, wrww, wuwbgw, uwwwgrgb, gww, grwwu, ggu, rrurr, bgr, ubugwu, wwgwur, urrrbw, bwr, wrbgbu, wrwbb, gug, bwu, ruurw, rw, wbb, bbwgwrr, wgg, ugwu, wr, wwwr, w, wbwbuw, guugg, bug, bbbb, brbb, brur, rbg, wuu, wurwgb, rru, urrrbugr, grr, rubu, uugrwbb, bgbrurr, wgw, gub, ugwwgr, urwr, wbwbg, wrrb, rwrgg, ggwgrgw, bwbu, uwb, rg, urr, brrur, wg, u, bu, ubbbrw, brgbbbbu, wgrgu, bgb, ubu, uugubg, bub, rwrr, gggbrw, gwwrww, grub, urgrgw, bru, wgwgb, wubrg, ugrwwbb, wbgwrru, gbwb, wugu, uwwwg, ubr, gwr, bguwb, guwbw, wrb, grw, gwwgbb, wbwwr, grbwub, ubg, bwbgw, rwu, uurb, rbwgur, ubbr, grrr, ubwg, rgwuug, rgb, grrbub, bwb, uwuuubg, wrugb, brurub, wurg, urur, uru, bwwrrr, urwub, uwr, brr, ggg, bbg, bgg, guuruuu, ubwb, uburgbb, gbgrgug, rbwr, uwu, rwwbuugr, ubwwg, wwr, brg, wruububu, bgbb, ww, wrgbu, ugb, gru, bbwgbr, brw, bwwbb, wbr, grbg, wbbb, brbrwwbw, gbgwrrub, wwu, wgb, rruruu, wuggr, urb, bwg, wbg, rbu, wwg, wuw, wrbbugg, rb, rrgrbrg, guu, bwwugr, rwrb, gwbrb, wrugub, ubbrwu, uggbb, ggr, wwru, rgbb, bbgbgrr, wuruw, gbg, ubbwrg, bur, wuwuu, bgu, ruwgur, gbu, wwuwb, ggbgg, ugrbb, bugw, rggrb, rrw, rgwru, ubru, grbbuw, wbrr, wruu, ggw, wbgguuw, rggrugw, gbgwwg, gwwru, gur, rr, wbgb, burbwr, rggu, wgwu, rwuug, gwrbr, wbbwbgb, wurb, gbbuggg, gbbgbg, ur, ugwwu, wgu, bg, urrbgr, gurwg, bbb, urrr, bwurbrr, gbr, gwurb, ugg, uwbbrr, buggr, rub, bwrgbw, uwbb, ububggw, uuwrbbu, rrrwr, ruwgub, bugb, wwrw, gwbg, wwwrrr, urgggwb, gwuwr, www, g, wgrg, wbuwb, grwrg, uuw, wuwgb, buru, rgr, rrgu, urbgb, wgrr, gbuwww, rrgrgw, rgbrg, gugbuw, rrb, rrgbug, ugwbrgw, rwuw, grugrrbr, gbgww, ruw, wubb, gr, ruu, ubbg, brgurb, rwg, gwu, ruwr, grb, uwg, wgww, bgbbrww, buu, rurbgr, rwbw, gwwr, rwwbbugu, grgbr\n"
            + "\n"
            + "rubbgwuwbrwgrgrgrbrbbubgbggrbwrurwuggggwrbrgwbrrwb\n"
            + "urwgurrubuguruwuuuruwbbgrbbuwrbwrruuuubbuububuubrw\n"
            + "gguurrubwbuwgrbrrurrgbgburbrrurwbrrrubburuggbbgb\n"
            + "rgbuuwwwgbbwgurrwurgwgrgrbbbuggwgwugbrwb\n"
            + "rwggurbrgwrrwuururwwubgrurwwrubgguububururwb\n"
            + "ggrgrruwwwgrwuubgrggbbwrrgbrwrwgwwububrubguurggbrwbg\n"
            + "ggurrgrggwrwruuwrbrgbrubrbuggugwgrwgwurbub\n"
            + "wwwwuburrwbwugguwuwgwwrbggbwuwuuuuruwwurbwurgbwbggrr\n"
            + "urburguuwwwgrbrbgbbgbgrbgbubguugwubugwgrruuuugbbbbgubggu\n"
            + "guurrgwububururwgugrguuubrwrguurbuuuugrgbuwru\n"
            + "urwuwuuguwwwgrgbuwbgubwuwuurwuwggbwgubrbrguurrgrwb\n"
            + "bwwbbwuwbubgrbbgwuubrrbwgbggubbrbbwrwuuuguugwrwbub\n"
            + "wwwguwbgrrgbrgggwrgwuuwwwgwgwrgbrbgwgwruuruguubruug\n"
            + "gruuwuwbugubrwbbubrubgrruubuwugurbggrrbbbbg\n"
            + "wurubbwuggrrurbwwgrwubgbwguurbrwgwwwgrwuuuggwbguwwr\n"
            + "ggbguwrwguguwubgurgggrguuwugbuwbwwgwburgbwwuwgbrwbub\n"
            + "gwugrwruguwuugubbbrubbwbuwwwrgburrbbguwbgbgwrwb\n"
            + "grgugwwrgggbbbubububwuggrrgwruwrubwbrbbgwrwrggbuwrururrrrg\n"
            + "guwgggwrwrggbgwrrubrwburbuuububrbwrrrgurwugwggr\n"
            + "wuwwugwrbbuuburuururuwwrggbubwwugbuwugbburrwuwbubgbw\n"
            + "ugbggwbgurubbwrgwgggggwggrruubrgrwrgugwwgurrrbwbrwwur\n"
            + "wurubwrrbbgruurbbgurbbubuggubrrwwgbgwrwuuuwrgwbbrbw\n"
            + "rwwbruubgwrrugggwubgwwubwruuwggwrbwwbbrrwb\n"
            + "ugwgbguggggwwbwgwwuggurbwwgrbbuwurugwwrrrgugburruwb\n"
            + "brrrugbwrwbwwurbgbwwuugrbwbrgwgrgrbgrurwgwurgwruuguwbrurwu\n"
            + "rruwrrbgubguurwwugurrgrwbbuuwuburrbwwbbrggwuwr\n"
            + "uuwrburgruurrbuwwguurwbwwbwggrbubrwuuwuuwrbbg\n"
            + "gbbrrwgggbwwggwgwuurubrrurgwgwgbwgubwggrrbggug\n"
            + "wrwuggugbrwuuubbgrbugubbgurgrrburgwrbugrwb\n"
            + "bbbwgbuwbgrgggugrugwwwbwgrrbbbuubuguuugwburrrwrggwrrruwug\n"
            + "urbwwguugwrgbrrrrrrrbbwggrrubwgwugbbbuurugggrg\n"
            + "uugrugurbbruubwgbwbbbwubbrbbgwuuuwggwwwuubrrrwuwubrgrbrw\n"
            + "wbrugrwrwrrgugwugrrugugwubugrrrwbrwbwrggbwurrbgubgwbgbbgrwb\n"
            + "uwwbbubgrrrurgwrbgurugwbbrbbburggguugbwbrbgwbubuwbbgubgwg\n"
            + "rrbwbrbruwurwbwgggwrguwbbubuwuwurwubgwbwwgbubggwbbubbrbr\n"
            + "wwrwggbwwwrgubwrbwuuwbuuuwbrgwwrbrbrguruwrwbrrgrugb\n"
            + "wwbwrrubbbgwurbrbubwwbbbgbrbgbwbbuggrurbrwgwbubguurrwrwwb\n"
            + "rwurrgwuugrubggwbuubrbuwrggguwbgrbbgrgbbuwggbgwrbwgwbuuru\n"
            + "gwrrugbuurgrrwgbggwggguwwrrbgrbwwrrgwwbwubwbwrgbrgbgwwbgu\n"
            + "brrrwbururwwrwwrrgbwbubgbwgrgwwruuuwgugrwwrgbubru\n"
            + "uugbwguruwuwubburrgbbgbbrwrrbubuguugwgwwbw\n"
            + "gwburgbrwgwwubugrrrbuwugrbbwrrguwrbgbbgrggggbwuuwwgwgbww\n"
            + "rwwwbgwuubugurwbwururgbwbwwrwubgwuuruurbwbwgbwwbuwgg\n"
            + "bwwwbuwwrwgurbbwbguwwgwubwuwgwwubbwwwuwuuubbwr\n"
            + "urugrwggbbrburugwggbwbbuubbrbguuggwurgbrbbbgrbwuw\n"
            + "bgrbrbgbgwrrwgugbubbgbrurwrrgbwbbgrwrwbwwb\n"
            + "gbwubwgurggwbbgwwgbrrubguwgwwbrgwgrgwwwgwwbruwrwbuurwb\n"
            + "wuuwrwrbugruurrrrgwurguggbgwubugrugwwuguwwruuwbrrrwwruggb\n"
            + "ugrugbrrwuuwrwuguggwwgggubuwrrbwrugwwuugwbburrbrwb\n"
            + "wrrggbggbrgurbwguurugbwgrgwwgbwbgrbgwrbrwb\n"
            + "bugubbrwbuwugwwrwbgwugbuuubrwbugwrugggbwwrbgbwuurgw\n"
            + "bwrrwbrruuuugugggwgrgrwwrwwgwwgrbggwruwrwwwgrurwgggwbbw\n"
            + "gwwuwbuwwgwuurwwwgbruwuugruuwrgbbwugwbbwbguguw\n"
            + "uwrwwrurwwuwwwuwuubbbwbbrrwwbrrgbwbwggwgwruurrwb\n"
            + "rguuugbrbgrbwbbrwuuwwubwrrwggrwrgwwrgwuubwgbbwubbwbgbrruwu\n"
            + "gbgrgrwgbbbrwgubugwwuuwrrgbwbwgbwuwrugrbururbwrwrwbubrr\n"
            + "ruwrgurgguuurrggrurbuurubrbbguwbbrrbuuuwrgrwb\n"
            + "guurwgbwrbuurrrbugrbgbbrurbubbuugrgbwugbru\n"
            + "uggbgwrrgrrubgbbgwubwurgbbugububwrwbrgwbbbwwrwb\n"
            + "gwwgbbrrurbwwwrrrbruurbruggbrgwbgurbrwggwbrgurbbbwubbuw\n"
            + "wbgrwbuguguwrbbuurbubgubwgwwbrrrrbugurgggbbgb\n"
            + "buurgwggbbwgrrbruwuwruububuubrrbrrwrgbwbbwbwwururbgurbrrgrwb\n"
            + "rbgggbwrugrgwrwgwurggbrbgwgwgwwrbubbrwrbbuurugrrgwbrggbu\n"
            + "grrbbbwwguwbruwggwruwurrgrbgwubbubggwuugwubuwrrugurwb\n"
            + "rrbububbrrbbuwwuuwggbbwuwuwwrwgwwgwgrburbgrgrw\n"
            + "uuurugrbrrgwbrrggurrbubbuwguwuwgrurwbrbgwurwurw\n"
            + "rwubrwbuuuwbggrbwrwgwwrgrbrrbbwgrrwrwrrgbruggwwwgbbrwuuwrg\n"
            + "bburuwbugrggrwggrwbgbbuurwubuuugrbrrwgwgbrggrgggwbuuwbwbuw\n"
            + "wrbrbugwgrbuwrubwgwuwugbrgbwrwrgwururwrrrggrgurrwb\n"
            + "rggrbururgwuuwgbuwuwrruguugwbgubuwrubuwbrggbggbggrwb\n"
            + "gwurbruwrrgrrwbbwuwbgwrgwubbbuburrgbwrwrwb\n"
            + "urbrugbrwurgrgbrruwrbbrgwbrrbrwurbbbugwuugrwguwr\n"
            + "brrgurwwrguuubrggbggwwbgbgrrwwbburwuwrrwggbwubrrbggugubu\n"
            + "rwgwwuugbwrwrguwrrbrgwrurbwurrggwuwuwbgwgwwguurgrwb\n"
            + "guggggubguggwugbgbbwwgurubwugrbwgububbggbbrwb\n"
            + "wgwrguwggbugwwgrrrrwgwwwwrwwubgugwugbwgwggubwubrwb\n"
            + "grwwgbrwbubbwrwwwubugbgrubuuwbgurwurrugbwrgrrr\n"
            + "uugwwbuubggggruwugrurguwwwbrggggggrwwwrbrgugu\n"
            + "rgubgwbwurrguwgwburwubgrgbubbrbrruugrugbgrwwru\n"
            + "wbwwrubbbguggwbuugrgwguruuggurwggrrbruwbwrgbuw\n"
            + "rgugbrwuurrrrrurubrrgguuwbrrwruggubbbubgbwguurburggbrwb\n"
            + "rbuuggwwurwuuwgubgrbrruwrburugurwuubbburrguuruwr\n"
            + "rwurwrbbubgrwgggwwwbruuubwrwuwuwgrgbrgrgbugwrubrrbwbwbwrwb\n"
            + "gwrgbggrwrgbbbuuggbgrrgrrrruurbrwuugbubgbwur\n"
            + "rrurrwuuwuguuwbububrrwugbwuurbbgguwrwrrgrwwgbrggrburwg\n"
            + "ubruwgwbrubwrgbbrbbubggggwrggrgwbgggbgrburuwrbbrurgrgbbww\n"
            + "wrwgubgbwruugwubbggwugbgwwugwrbruuuwrwbbrrrru\n"
            + "rwubrrgbwrbgrbrwggugbbuugrguruwwwugrgurwb\n"
            + "wrgruuwrgguwwbrurbbugbrgruwrgrwggrbwwbwbgwrbrwubwubrwb\n"
            + "bggwugbrbwbgugwuwwurrwrrrwrgrguwuwurwguggwbrrbugrwr\n"
            + "ugubbwurburwrrbbbgwrbgwuwgbubrrgwgubrubrgrbb\n"
            + "gbwuggwruuuguurrwuurubrbwwbbwwuburgwgwurbbubg\n"
            + "uubwugrgburwubbbuururrwrwrgwurbwrrwurrubrwb\n"
            + "urbrwgwbuugbrwgbugggbbwwbuguuubbubwbguuubgbrrbububrru\n"
            + "rrbwwwbgrgwgurwwuwrbgwrwgrruwbgwbgugurwgrbugrbgbrbruw\n"
            + "ugrwbgrbrburugwbgugwugurrgwgrgwwrbgguwgrwrwb\n"
            + "wwbgbrgrwgggrbrugwwrwrbgubgrwguwbwubwwbgguggbbrgugbugrbbr\n"
            + "ubrwgwuwguwbwgguugrrbwuggwubbwwrrurbwruwbuw\n"
            + "gubrwwrbbrwwbuugrbwwugbgwwbbbugwrgbwbwwbwguggb\n"
            + "rurwgbbggugrwbubugrrwugrubuwwwwrwububgwwrwgwbr\n"
            + "wgbbrbbubgrrwwwgugugurbrubbuwbgwwwgwwgwrbwbw\n"
            + "ubgubwgwrwbuubgbbgrwbubugbbbrugrgwurubwgubguwugrrbu\n"
            + "gruuuwggwwwguwwguubggbguguuugwugwwgugwrwb\n"
            + "wrwbrgbgurwgbrbgurbbbggrbgwgubwbbggwrbwgbbu\n"
            + "bggubwbggbgrrrrggwbwbbgrguurrrggwbgurgrgwbuwbwurg\n"
            + "wuwbggrwwwbubrbwgrgrwgbrurggwwwubwwgwgbwuwwuguuwwgggbb\n"
            + "rwrugrubggrbururrwuwurbrwbuuggrbrbuugrwubbruggrbwuuru\n"
            + "wbrgggbwgrwwubbbguuuugrburubbrbrrrwubwgwguu\n"
            + "wrugrwruurrbwwwurggwbbwbuggrbwuruugwrburrwb\n"
            + "rburbbrwwrwgwbrubgwgwrwgrbwurgubuguwwwruuggbbuwwwggrwb\n"
            + "gwuugurgwwwrwwgbrbwwugwgurwbbbrwuwwwgrgbwbbgbbgruwgwwgwrb\n"
            + "rruwgbbwwrugugugrwubgrguguuwggbrrbrbubbwugurbgbubb\n"
            + "uuubwuburgrrwuugububuuwwrwrgbwbbgwgubwwgwgubrrbgbruggbu\n"
            + "wgrwuruuurwwbrwbwgrrwwrgurrbubwrwbgwrggbrrgugbuu\n"
            + "ugwbrgbbbwrgrgwbrguwrbrrgggbbuubgwbwgbgrwbrrwrrrgbrbgg\n"
            + "rgrggguuguwgbgrgrrgwrbbwbgurrrgwbwwguwbgggrbugugrbrurwb\n"
            + "bbwuwgrbbbbwrbrgbrgbbbburgruggrrrrbwrbbrwb\n"
            + "wbwuuwrruwggubggbgwbwwbggwbgbrrruggbwrrrbrwrb\n"
            + "wuubruggbruggbwbwuuugwrrwuwrgbwwbwuwwwrrgwrr\n"
            + "uwwgrbuubwbwbbrwburbrggburubwgguuwbwgbwburggwrgbrwb\n"
            + "ggbrubuwuurubruuubrbrgwuubguwbgbgwrrubrrrwb\n"
            + "rwgbbburwggwwgbbbrruuurbgrgbggrbgruuggbrgggg\n"
            + "rwwbwgwgwwbrbugbuuwbgggggwgrurbgrgwgwrgbbbuugbbgruwgwwwbg\n"
            + "rbwubbwuugwggrruuuugbruwwwwuuuuurgbgwwwgwbggwgbrurww\n"
            + "rwguwwrgugrbuwrwwbbugurrrwubruwugbrwubrwrgrbggbgr\n"
            + "ubbbugrbugrwgwggbwugwwbgwguubugbggbggrbuuwwbbbbbwr\n"
            + "gburuuwbrwrguwbrubgbwgruuwrwgbrwbrwwgwbgwggw\n"
            + "ggwwwguwgbuwrggbugurrrwwwrbrrbgurbbbgbruwrwwrbgrwwbuugrwb\n"
            + "rgbgrbrrubwuggruuwbgggwguuwwwrrrwuwrrgrubbbgrr\n"
            + "uwwgrrbugrrbwgggwuruwuuwggwbgwggwrbbuwbrrruubuguwugbrurwb\n"
            + "brwruwruwggrrubrwugbgbwwuggggruubrruugbgurrgwwugrurbrr\n"
            + "rgbbrrrbubrgbbbuuggruuurguubwgwgrwwgrbbwruwwb\n"
            + "rrbuuwgbuwwwbggrgbuurrbwwbwbwbrwwubuurrggrbg\n"
            + "urgbuwuwwugbrbguugbrbbggwggwgburgwgrwgurrbwwgrbbgw\n"
            + "uubrrugwggwgwbgbbwggwrrwbruwbrwuurgwwugrwgrwg\n"
            + "rgrguwguwrgwwgruggbwwbugbruubgurgrwuwrugbbggbuwrrggrwuug\n"
            + "uwubrubgbbwrgbgugwwwwwubwwubrburbbuurgwrrbwbubrbw\n"
            + "rgrbbwggrbgrrggrgbububggwggwwwwbrubguwgbuwbruwgugrgwrww\n"
            + "bbrwwrwgbgbgbrwwubbrgwuruwbrbubrrburuurwb\n"
            + "uuwgwgubwwbburwgrrbwgwrugrbwwgbggrurgwbuwru\n"
            + "uuggrgwuguuwwrbwrbuwrbrbgbuburuwwbbgbggbbugwwbu\n"
            + "bwbgwgwbrbbbwwbwrwgwbwgurggguwugrubrubrbrbuwwuugubru\n"
            + "uwuwrgwuubbruurbbbururrurrrbrwggbgbbgwrbuwubgbrrgwuurwb\n"
            + "bwgbbrgbbbbuugurgrburrrugbuubgbbwwwwgbuuwuggbgwguubb\n"
            + "uubwbuurbbwgbrgruwbugguguwbubbgrgbbgwbubggrrbwrwb\n"
            + "rrrguwbgwuwwbrrwrrwguwurbgbrburrwgrrburgwbbrruwwrrwbwrb\n"
            + "rruguburbgwgrgbguggggrugrgwbwwbwrbggwwgbruwuwrwwbubgburgr\n"
            + "rurgbwbugrbrgbgrurruwbubugubbgwuubgrwgrwwwgwbwrwbbwb\n"
            + "bbgbwggwgbbwbuugrrubbubgbrbrgubrugugrwbrwwbg\n"
            + "gwgugbburwwwwgbwwubwrwrwuurruuwuwwurugrrrgb\n"
            + "wwwrrrgruwrrrwuubwbrrurwbwrwrwbwggggrrbwuwggg\n"
            + "gbwrwguguggbwwrrbwgwwbwgbbbgwbuwuwrgwwrgbwuurb\n"
            + "guguuugbrbgruwbwbubwurrwggrubruwwggbwwubguub\n"
            + "uubbrubgrwwwuwrwgugbwbgurgrbbrugbrurguwrwwbbuguuuburwb\n"
            + "gubbuuuuubbwubgrwwguruggrbrgrrubuuuurrwrwb\n"
            + "uwwgbgrgrbrrgrguwgubuuwbwgguwbgurbwugbbrgguw\n"
            + "buwbgrggwwubrgrggbwurubgrbuuuwurrbuwurbbbbbrubgbrbuwwwrw\n"
            + "uwbrrbbwwruurgrrgrwruruwuubrgbrwwgwbugrbbrggrbwwbgrrwb\n"
            + "rbwgwbrguubbbugwguwrgrgbggbrruggrwubrwbgbwwuuwrrgwg\n"
            + "rbrbbgwggwuuburggwwrruruuruggwubruwwbrurubwbu\n"
            + "rbubuuurbwrugurggbwwbugbguuuuuwrubbguwrwb\n"
            + "bbwbubwrbuwgubguwrwrwgbgrrwwruurwwrbugrrurwb\n"
            + "bbuguurruwrrbguuuugwrguubwuubrbggrwubgugbwbwrrurugrugrwb\n"
            + "gbuuwurrbrwwrubgurbuubugrrbwubuurwuwwwgbbgbrwbrrrubggrwbgwb\n"
            + "grggrugrrbruuwbbbrrugbbbbuwbrwurrwgbwbuwrwb\n"
            + "bguurbwgwgbgbgrgrbbwgbbwubbwggrbubrwrbrubrbrgrwbburwb\n"
            + "grrrbrrwubuuggrgrurruuwwubwuuwubrrbburbrwwggrwgurgwgggwr\n"
            + "wbgubuuubwuwbrububrbwgrugrrbrrwbugguwwuuugu\n"
            + "rrgwgrguwruwgrwwrbgrgbbbbbwrgbugbggbrrwb\n"
            + "gwbrrgrruurwurburwbgrbggruuurbrbwubguwgrrburbgwwwu\n"
            + "bwwbugbruwrrguubruwbruuwrrwuwbruwgrwgwruwurgrbgurgruguwbg\n"
            + "brgrrbururwguwbburgurgrggbgubuwgruuuurbrrrrwugg\n"
            + "uwrbugwwrwuwgwwbuugbuurbwwbrwwrgrbggbgwwwrbrbwrrubbgrugw\n"
            + "uuggwbwrrwgrruwgggbggbgbubgwgbugwwrggrgbrgrururgugur\n"
            + "bwwwrugrrgbggbggbwubburrgubgwgwwrbwwgwbgurw\n"
            + "gburbuurwgbwgwwgggwbguwuwruububuwububwuwbgg\n"
            + "gbwggbgguwggbgwwrurwggbuburwrrgrbgbbuwuuuwrggwggwb\n"
            + "gbbwwwgbgwurgrbbwbgguwrwrggguwbugwbrgbwurgwuwgrrug\n"
            + "rgbugwrgugwbbbgggrwgwubbbwuurbrbrwbrgrwuurwgrg\n"
            + "ruwbuwurgwbuwrrrgwbrwrrruwwgggwugbwwrgruwgwubbgrwrrrwu\n"
            + "brrbwbbgwwwuururbrbuuwwwuguwwburbrurwuwgbwrbuubrbbww\n"
            + "rrrwrwugurubugbubbgwgrggwbbggbrugwbwrbggburgbrwr\n"
            + "ubrggrgbgwgruggrgrrwbruubwrrurubrbgwrwbggbrgbbrgwbbbr\n"
            + "ggrbbggrurbrbruwwugwrbrwrrbwgbrwwgubwrbrrgrbbwwwruwggww\n"
            + "wugbrbgwwwwrbugbwwrrburuwrbruruwuuuurbuwwwbgrgbrwb\n"
            + "bbgbgruurgbubburgwruwgrwuuubbwbwgugwbrbuuwwgurrurgwwrrb\n"
            + "wwburbbgbwurubrbrurwwgrwgubbgwbgrguuugurbwuwbuwuwuru\n"
            + "bwrgbuwrrrbubbwugbbrrgwgrbbbuguugrwbrurwrugguubbrubuggrwb\n"
            + "rgrwugwgbuuwubwrguuburuuuwuwbgguwuubggrrbugrbugwbgwwubwwbb\n"
            + "wbwrgurwrwrgggbbgggwwrbrbgurggubbbgrgbwbug\n"
            + "rbwbuwgurbbbgwuubwbgrwwubwbbwbgggwurbbbgbuu\n"
            + "wbburugwgrwwwgwwrwrbubrwuwrbgbwgbbwbrrbwbubbwbruubgrug\n"
            + "wrwggwgwwuuubbgrrwggrguubrgurrwuurubwurggwbrbbbugwuuwubwgu\n"
            + "bggrgbruwguurrurrbwuuwgugbrbwbuwwgwrgurggwburbbwgbuw\n"
            + "wwwbbugrrwwbrbwwgwububbuggrgrurggrwgrurruggbburwwgwurwb\n"
            + "rbrrwubgrwrbrbrggwwrurrwbwrurbwgbubggbrrrwwrwb\n"
            + "wuburwgwrwuwggbwwrgwwwugbwbggrurgbrurruwburuugwrwb\n"
            + "gwbwurbrbuurgwwbuuurrubbbrbwgruwuwuuuugwgbbb\n"
            + "wguwrbrbrgbbbggbggbgbgwgwbrggbggwguwurwwbbwbrrrrbwrwgrwb\n"
            + "wwwbruruubrurbugrrwwuburubbguwwrrbbwbbbrgbbubuwrurugr\n"
            + "brurrgggruwgrburwuggugrrbwbuuwbwuubgurwubruwrgwurbrwb\n"
            + "gwrruuwbrbwwbbbuwbwgrgubgggggwubgugubrbgugwuuburubugruwu\n"
            + "uubwruurruwwbrwburwggugggrguuurrgbbwbuggbwbuuurbgrwb\n"
            + "ggwrurbgrwgbbbruuurbbuubrwururgwwbuuwgrgwrgbubugrbrrgg\n"
            + "gubrurubwbrgrwwgggwwbwwguubbgggbggwbwwrguwrgwuggr\n"
            + "rwwugrbggburrrrbgwwgwgrurbbrguwrrbbbruwubgrgbrrwb\n"
            + "bgrrrbbgrguwgwwgurwwwrwugwwgrgrrwwguugbbruruuuwburbbuur\n"
            + "gwrgubrbubbbbrggrrbgwuwwbgbbuubugwgrwubgbbr\n"
            + "bwwwgwguwrrguruugwwbwgrgrwwbbwbrrgwbburuubbugbbrgggw\n"
            + "wburrbwwgubwbbwrbrgrwrbwugwuwwgwuugwwwgurgrguwuwgrgruu\n"
            + "wggrrrbgbgwurwrrwbrubbwbrwgrrwuugbrwwuwgruwwurw\n"
            + "rrbwggggurwrbwrrwubbrrurwwgbbrwuuwrruuwbrwb\n"
            + "ugwwwrbrbugbgrbuwbubwuggbwwugbgwrrwurrrwrrbgwrub\n"
            + "gbwgguuguuuugwgbuubggwuwbgrrbrbgwwbgugguruwrwggwwrwgwgu\n"
            + "wuubbbugwgrugububgrbgwugrurruwbwrbggwbgbbgurgrgbw\n"
            + "gwugwbbrwbwgwrwbrgurbwuwuugrrrbwwrburubgwrwwbbg\n"
            + "wwrgrrbubbuuwwbuwgrrwrrgggguwrrubbugrgwwbbug\n"
            + "gwubbruruuuwbbgrugbbbgbgwurwgwgwbwbwugggugbwuburwb\n"
            + "grgwgwrugugbgbwwbwubgwgbrgwguuwrrwwwugbgwgbgwruwwrwgwwrwb\n"
            + "rwrggugrwbbwgbubuwuwrrrgguguwrggbwbbwrrwb\n"
            + "rbgbwuwbwrbbwbbgugwgbbbwbrrrugwbrbubgruburwgwrrwb\n"
            + "wrrgbbbbwwuwgrgrrrbgurugbuwuubrgbgrbbbrrwb\n"
            + "ggrbwgwgrugrbrrwgugwguuwubuwwrugbbwwbbwuwggwuu\n"
            + "rwuuwwbugruwrruubuwuruuwubrugwrrwgruwrwrubbruruuwwg\n"
            + "rwrwuwbuwugbubgbbrguwgubuubbuwbwbgurubggbgubgwu\n"
            + "ugrrrruuwruuguwggubguwwwgrwuuwrwugwruwgrrbbw\n"
            + "ggwgwgurwrggrrwgwruuguwrugubrbuurwwruwbgrgrwb\n"
            + "rwbrrwuwbbbgbrrbwburwbbgbggwbbggwggugggrrrwbugg\n"
            + "ugbruwrruwgrbwuggrwwbruwwubrurrggbubgubugbgruugrrwb\n"
            + "wwwuubbwubwrubgubwrugrurbugguurburrrrwgguwwuggugurguwurwr\n"
            + "bwwbrruwbugbwguubbgggbrwbbrurgwbrwgggbgugbbgrbww\n"
            + "brgbwwubgubguwugwwuruubggwwuuwgwgwggbbwwbubbbggu\n"
            + "rbbrbbrurbuwwwguggguwgwggburbggubuwwbrbbubruuwwbgbru\n"
            + "rwuuugbwgwuugurbwrrwwbugbggbuururrbgwbwuuurggrurbgwbgggrrwb\n"
            + "bbgrgwwugwbwugggbugbgubgbgwbbuwrruurbwurwrgwurwb\n"
            + "bgwgguuwggrbbugbgwwwrwurrrbugrgguugrbgwbgwgwggruwwggwwgrwb\n"
            + "urrwggrubuwgbwggbbuwwbwbbwwrrgwrwbgurwurru\n"
            + "uwwbugruuuwggrrrrrbrrrbrurgwrrwwrrwbwbruwbbbuggwuu\n"
            + "wrururubbrugbggubggrbruuuubuubwuggggwwwubbwbbwbgbgbbgurwb\n"
            + "ubrubrbrgugurbuwrwuuwgbgwwrrwrrbbgwgbwruwrrrggggr\n"
            + "rbwguruwbgbgbbbbubbrrrugrruggurwwgrrrbrwb\n"
            + "rurgwubwbwgubwrbgguugrruururgwgbuwwurgugww\n"
            + "bwugrgruugguguwbgrbbbwuuwrrgwrrwrrubgrbrgbrggbww\n"
            + "rrgwbrwggbbgrggugurwgrgbrgwgbwrruwgwggwgrwuwrwbburwwbu\n"
            + "uurbwggwubwgwwguwbbgwwggugrrruggbgwbrrgwrr\n"
            + "grwbwbwrgrwrrubbbgwgrbbwrbgrurwrguwwwwggrbwbrwubbwrggr\n"
            + "gbuwbugrgubbrrbwwrbgwuwrwrbrbrwwbwbwrwuurrruurwb\n"
            + "ubrwurrrwwrbgwwgguubuwwgwbguwggurwbbgrugwbbrubug\n"
            + "rbugbwbguwggwwrwbbgwwuuruwwbrububbrurbubrgwwrbugugwbubggru\n"
            + "uuguruubgwwrrrwwugwurbgwbubrgrurrgwuuuuuggwbgrwbugu\n"
            + "gwwbugrrburuuwbwwbbugguubuuwwbuwbuwgubuwbruuugrgurgbuuubbw\n"
            + "ugwwgubwubbrubbrugbbbrurwgrgubgubugururgwgwwburgr\n"
            + "uggrgbruwrrbwrwgrruurwgguguwrwrwgbrggububgwrbguwbugwwguw\n"
            + "gruruurbgwrggggbrrugrbrgubrurrgugbbgrbgrwwugbrubw\n"
            + "ruggggwgbubuuubbgbburuwwgbbugrwubbrubgbrgbggrgubrb\n"
            + "wrguwbuwbrrbbbwbwrbgrrubwggbuwrrrgugbbrwbrguugrbrwgbrgg\n"
            + "rrgrwbgurgbbrgrbgugwrgrruruuugrgrrbbrrrwb\n"
            + "uuggrwugruuggrurbwggwgrwbwrgrbbbgbwbubugwg\n"
            + "rwwwrwrrbgrrgrgrwrgururgwrwburubwgrguwbuwwrrugugbbrwb\n"
            + "bbgguuwwuwbbuuwgwgurrwrwgbbrgurwgbrrbwrwbrwrbuggbwwrwrbuw\n"
            + "wrwwbgwgwruwrubbwrrwurwubgrrwrggbbgbbbgwwbgwggrbbwbrbbgbg\n"
            + "wgggrbrbwuwgubrguubgrguwrwuuuwbwwubuuwgbgrgbruubb\n"
            + "uggrwrwwbguwurbbburrgwgwururgwrgruwbwuubugubrurbuubrwrbuurwb\n"
            + "wrugguwugrgbuuwrbugrubrggggwwrbuwuurbuwruwwuww\n"
            + "wugwrwbbbrbbbrggrwbuwrwgwwbbrbwwgbruwugwruggggbw\n"
            + "uguurbwgwbbuuguwrwguubuugwurbgwrrbgbrrguwuwug\n"
            + "uwwuubgrrwgwrbbrgwwwbwugbbggbuuuurgubgwugrbgurbbwug\n"
            + "gwuwgwrrwgrwbwggugrbrggubbuburbbbgugrbuwrurrwbrwgggr\n"
            + "wwgrugrwuguwbruwugguurguwrugubwubrbgwwbrwbrwgbwrgwrruwurbr\n"
            + "gwgburrgwuurwburubuuwwwwgbbwbggwwgwuugrgwrbwrrw\n"
            + "rbgwgbbruuwwugugugrubbuugggwgubrguwwgrwgrrrgwbggbuguwu\n"
            + "rwwrrbrggruuubgruburgwubrrguwbwwgrgbwggruggwg\n"
            + "burgwuwugwbbbgrwgrubguuwugrbrbguubwwwrbbrwbrrugubuwwguuurw\n"
            + "gburugwwrwrrugugbbubrwrburrugrubbrurbrwwgrbbww\n"
            + "wuubbrbubbrbuubuwuwwgbuubugbrrgrugwrgwgwwwwwwwuurb\n"
            + "wuwgrrgwbbgrurbrgrrurbbgwuggggbgwuurwggurrwb\n"
            + "grbbggbgrugwbuubruwrgbwrbbwuugwrrugwrggbrurbwrrurbrwb\n"
            + "uuubbgrbwrurbwbuggbbgrwuguuwubrwgbgrrwurubbrwgggwbggrwb\n"
            + "urgwrgbbuwwrbrrrbbrwgwugwwrgrugwbgbbgrwb\n"
            + "wgbrwggguwwruuwwggwwrwbbbugbruwugbbbuuuwwgurrrbwwbubbwgburwb\n"
            + "buggbbgbgbbwwwurwrwrwbruwgwbbgrruwwgruubgwwwuggur\n"
            + "rbgbwubgbbgrurwwguwubrwubbuuggrugurubwuwgrwgubgugwguugrgw\n"
            + "urbbgurbubwwgbbwburrrbgrbwwubggwugbrrbugwrbgubrb\n"
            + "wbrurrrbgrgbgbwwwrwurrwbuuwrwwgrburwrrbgruggubgrguwgbwur\n"
            + "uuururbwrrwgwbwwrwwgwgruwurrbugwrgburgwrwrbrbw\n"
            + "rrwrurbrgubuguwurwgururugbgrbgubrgrgggurggugurgrbbuwgw\n"
            + "rrwuwrugwwbbubbrbrwrbwbwubgubgwwgrbugwgrugbgb\n"
            + "grwgbggwwwgwrwgruggbbgwrgwubgwrwguwgrguuuuuwgbbubgguugg\n"
            + "rbuurugruurwuwgburwgwgugrwgwwgwwgbrrugguwruw\n"
            + "urubgguwggurwbgrwwbubguwggbbbgrugwgrbgbrwgwrrbrbbrguub\n"
            + "wrbrurgwbubbwbbrwbbrugwgbubrwbgrgwguwuugbgugrgbg\n"
            + "rwuruwurgugggrgrrrugrurgggrrubguurbububugugbwurwuwwug\n"
            + "uubwuwrwwgrbbwgrrgubwgguggbrrwuruuwuubgrwuggbgruggbrr\n"
            + "uurbbgrgbrgbbgrgrbwwugbrrubgubgurrbbrrrbubr\n"
            + "guguggbgggwbbwrwrbwbgggrurburgurgbbwwgruru\n"
            + "wbrrbbuurwruuuwugrgubwuuurbrwurwurbwwbwububwbbbrwb\n"
            + "ubbrwgggwrwbwwwrbgbrrrbrubwrgurgbbgbuuuuugbwgwgrwuwwbuu\n"
            + "bwrbggbgrbbgubbwrrrubgwburgrgrrruurwuuggbguwbwwurrwrwb\n"
            + "gwuguuwbruwuuggrbrrbuwurbggbbwguwwgwwbgrurrwb\n"
            + "rrggbbgurwbbbgurbgbggubgrruuwbrbwgbrguwubbggguwbgruwwrwb\n"
            + "uwugbwwwrbbruubwbrgbuuubbgrubururrbrrgwwbgrwgbrwruwrwb\n"
            + "bwurruruwuguwrbuuggbwbrubbrwuwurbgwwbrgurgwuggr\n"
            + "ruuuwugrrurbwrgrbgurbrwbrbubbwwuuwwuwwuugugbbgrbggwr\n"
            + "uugrgwgwwgrbrubbugbgbrguwbbwwgrubbbgbgbruwugrrwb\n"
            + "brbgbwwwbbuuugrwrugbwurrgggbwwuubwruuburrbrr\n"
            + "wrwrgwwrwrugrwrrurbuuwgurgbrgbrwwbwrggwbrbbuugrbbwugrwb\n"
            + "rugbbggbuggwgwwuruwrwbggwgburuubuwugbggbrbgubrwgr\n"
            + "ubrrwuwguwwrbgwbbbrrgrggrgrgwgbrugubuwwwwuwguuurwb\n"
            + "ruguguwuruubbwwwgwgrrrwrwwuuuruuuwuwgwubwwrwu\n"
            + "brggrwrbrwwwuwwbwrgwbwurbuwwrbrgrrugbwugrbguuwb\n"
            + "gwuugwuuuggrgurbbwggrubbwuurruuwrggrggurgrrwrrgbrb\n"
            + "ugwggbgbbrrwgwrbuggurrbuugbwrurbbuggubwbgwgwuwgwrrrwubuwurwb\n"
            + "wwuugrrggrbrrgwuuugbwbwrurrbuwwwubwrbrggubbubbgrrr\n"
            + "ggwuubgurubrurbwgrwwuggururbrgruwgruugugrbwgrbubrbrb\n"
            + "rwggguwwubburgwwuurrurrrgwgbrgbbbrruguwbwugguuurr\n"
            + "rrbwbrrwbuwwbwrrbbbwwubuwgurrguwugguwrbuwuubbwuwrbggbuu\n"
            + "grgrbggrburrbgwbwbuugugbburbrwrrrguuwbugggugrrrgrwrwb\n"
            + "buubrrggburbggwgwgrbgurwbwwwubbwbgbwwuwbwwrwb\n"
            + "wguuurrggwguurburgugugbrwrgbwrrwbgrugwuugbwgbbuubggrugbub\n"
            + "wbwgruuugggrrubbwrwwubugguguwwguubwurwgwwrbgubwrgbbubrwb\n"
            + "ruwrggugbbbbgurwggruuggwwggrwwrwbbbrwguuuuug\n"
            + "bggwwuwgwbuguwggrgurbwugbbbuurwgwuggubgrwbwwwbwgrrbuug\n"
            + "rrgwugbuwugubuuggbrwwguurwuwugwuuuubgrwrrwrbgrgwbuggwr\n"
            + "grguwrrurgbwbwrgwwwrggrwbwgbuwbbbwbggrbrwbbrwb\n"
            + "uubgbrgrwbbgwrbrwwgbgburbuurbubbguuwbgbuuwburbubggguug\n"
            + "gwbgwrbwwwubuwwrwbbwrrrgwuwbrubwbgggubugbwwgggburrbugrgu\n"
            + "bwgwguugggbrrbuggwggwgbrbugurbwwuuwwwugbbubbrwb\n"
            + "rwgwbgbwwuwrbgbgwbrwuwruuubbrbwwuruwbwrbrwrwrgru\n"
            + "wwrbwwwurggbgggugwuggubbbwgrrwrbwwuugwrbubwgrbgrrr\n"
            + "ubrubggrgguugburwgbbrwurbrburuuwwrrbrrwwbgwbgggwugurugwwrwb\n"
            + "gbggrubrgubgubbwwwwuwrbburrgrwbrgrwbrwguuwwuwrgguwrwb\n"
            + "bbwgbrwggwrbwugbgubugwwuwwggbgubwubgggwwrbgrwrwwgb\n"
            + "uubrbgbbguugrruurbrwbbuuuubbwwuruuuwbbgwbgrbwrrrgb\n"
            + "bbbwugurwrwurgbuuugrrruubrwrgwguwubrurgburbgrrwrr\n"
            + "gggwwgwubwwwrrbubuuuggrgrgburugbgbuurbgrugrwrgwgruu\n"
            + "burugbguwbuwgubugubbburrgrrwuruubbrbrwwbwrburubwubbb\n"
            + "wrwbwrbggggbgbruwwwubuurwbgwgrrgrwubwrrbbggrgbwbwbbbuwbbrwb\n"
            + "uuurggrbbwubuwbwbwrgrbbwgrgugbrruguuugrgrubb\n"
            + "buuugbwbbgwrgruuwrbwbgwbbrgwbrgrwruwwwgwruggrb\n"
            + "rgwrrguwuugbgrbubgbuburgrbuuwwgbbwgurrwwubrgwguw\n"
            + "ruuwwurgwurgbuwurruurbbbbugrubrrgwrgurgubbgbbwgugrwb\n"
            + "urrwrwgugrrbbrgggrgubwbrwwgbgururbwruguwwrgburg\n"
            + "rugrggruuubgguuwwwbgbgbbgugrwgurrruubrgburgrrwb\n"
            + "ubwwrugbguwrrrbwuwggrwrwrububurbgruwbgwrbbbgrrrgggwr\n"
            + "wuggwbgwbbbwugrbbwwubgrbwrgrgrrgwuuwgrwgwwurug\n"
            + "bgwwbbbwrrwugwgwwrruggrbwuwbwwgrwrgrrguwgrurwgurgggrrwb\n"
            + "guwrwubwrwwwgugguuwwurbgugbuwrrbwrguuwgbwbbgbgurrgwbbu\n"
            + "gwugguubwruguubuguguugbuuugrrwrrrurrbwgrbwgwugburuu\n"
            + "brwgwrbbgwurgrugggrrbbwruugrgburrwggwguwuuwrrbw\n"
            + "bwbugwurgbgurwwrugurgbbgbuurugggwugubrwb\n"
            + "bbbuuubggggggwrbrgbbwruwuuwugurbubgwgrrguugbwuggrubrwbwgr\n"
            + "wgrrrurugrbgwbgbbrrgurrgwrurrwwwbgrguuggrgurwww\n"
            + "gubbrbwurgwwbbggurwgbgrwrwbrugrwrburgrrugb\n"
            + "uubuubgguwwbrrwwwwubgwbbwbwwwwugguguwburgbrbbbg\n"
            + "ubgrwugugrruwuurrwguggwuwbrwbwrugruuuwrugwwuwrubuugbrwrrrwb\n"
            + "wrgwguugruurububuurwurrwuggrrubbrrrgugwuugwurgrg\n"
            + "bwubggubrrburbrbwggrurwrbwbgbbgwggubggbubrububrwb\n"
            + "urugwwbubbrrwwwrbrwuwbwurwgrurbwbrurbrwrgrruburwb\n"
            + "rruubgwwwgrwrggubgubwrbbgwgbguruwwgrgburgwrg\n"
            + "rgugrgrbbrgwbguwgguguwrrubgwwgwgwuwubwbwrggbwuuuwrrbwgwu\n"
            + "gwuwbwuwwbwwggbbgrgwugwrgugruuubgwguwwgbbrwb\n"
            + "bbwuguwwwuguuuuurrbbububurbwruuubugbgrbuwgrururwb\n"
            + "bbbugrrrbrgburgwuuruwrbwgwrgwgrugbrgububrbwwgrbrgbuwbgguu\n"
            + "bubwuuwwuwbggrwwubruwbubbwwgwrubuguwbuuwugwrbbugr\n"
            + "uwrgubbrrgguggubuuwrrrwrrurbuubrgbbbwgrwub\n"
            + "wbbguubbbbguwuwbwrgwwubwrurgwurbrrwurrbgrbbburw\n"
            + "rgbwugbubggbrbwgbuuubrwgbrruwggbbggbbuggwg\n"
            + "rgrugbgrwbwgwuwrbggrwuburrbguwguguuugwgubrgruwwbw\n"
            + "uuuruwuurbwubrwgwuuwbugrrwggbwwubbugwgubbrwgwwwugbwwrwb\n"
            + "brgbguwuwggbbwrbggggbrbubbwbrwbbgwuubbbbgwrgwgbbwu\n"
            + "uggrgrubuuuwruuurbuwwugbwwgwwguubuggubwwugrrwbggwrgubrbwrw\n"
            + "wbburbgbbrbbggrgrrurwwgurbubwuurwwgwbwrgbguuuwrubwwubuu\n"
            + "buwbgbrwgbubbrbrgwuwbgbrwburgbbrwgguwwbwgbwbgbww\n"
            + "gurwggwurgwbbubbgbgruggbrbubuwbruwwrwguggrbbbrggwgbrgbgu\n"
            + "wbwwwbbbwgruuuwubbrrgbbggwbrgwwbgurbbwgwgwgrbggwrugrugggbrwb\n"
            + "bbgrwgruggrwwurwwrggbruugbbrgwggrrugrwuuugbrrwb\n"
            + "wwbugbwuguwgbrwrwgrrbuwgwuwgwrbbbubwwgbrguwuw\n"
            + "ugwbgbwrrgbwrrrbrwwguggruwugwwurwrrbgwubbwrggugbruuw\n"
            + "bbbruuwuwwurrwbuwbuguuggurgbgbruruwurgbgbgrrwb\n"
            + "bggwgrggrrugwwbuwgbrbbgwbbuwwuwbrgbwbggwbbgggugwggrwbbur\n"
            + "uuurruuuuugrbuwwgrbwwuuwbruggggbgrbuuggbuuuwgrrb\n"
            + "gbgrgubggbgrgguuwbwbrwbggwurgbwwwbrubwgwrggrbwurggrwrrr\n"
            + "ggbrbrbguwguuugubruggbgwbbuwwrbuuugbuuwgww\n"
            + "wurrbururbgrbrgwggwggrgrgrgbgrrgbbwwgbrgwururwb\n"
            + "uubugrgbrubuggrggrbwbbbruwbrrwugugrurwbgwwwbubgrggr\n"
            + "rgwwbwgbwugugrwrrwubrwbgwuwuruggbguubbwbugururu\n"
            + "wbuwrbggrrwbgbrbwwwbbgwbwrrggubrubbwbubrgwrwburbgb\n"
            + "gbwuruuwuwwwbggurugrwgwubbgbwwwurgwbruwgbgrbwrgurwb\n"
            + "gwururwwugrrubbruwbuwrbgwrbruugbuuugggwbubwubb\n"
            + "wgrgrrgwwruugbrrrbwwrwrrgbguwwgwrbgwuuwbgwuwrugg\n"
            + "ugurwrbgrbubwbbgrwgrwrbgwbwuwubgrbuwwrubrggwuguwbgbu\n"
            + "ugrrburuwwrrwgrugbruwgwbbubrbuwbwwruuurgbuwwgwgbwwbuburwb\n"
            + "wurugurbrbubbbbburuubrbrrbwubguwggwubbrbrbrgurrbwwwuggwg\n"
            + "bwrburggbggbbgbuguwbgwwbbbubugwguwbbgbgwbg\n"
            + "gbwrbgbgbrugbbguruuwgurwwruggggbuburbgwwrwb\n"
            + "rubrgwubrrrrrwbwbrurbwwggrrburrugrrubwbbguwbbgrwwrbburrwbr\n"
            + "wgbuurbrrbgrugwgubuwbgurrwwuwgrbrgrbgwrwwbrururuuwrrrwb\n"
            + "grwuuggwugwgrbggggbwbgwububwrgwgburrugurbugurrrwrwrububrwb\n"
            + "bbggugurwurrgggrrbbrurubbwbuwbbwwbrwgrrrubrgur\n"
            + "gwwwugwuguubuuwgbgruruwguugrbbwgbbwwgrgrwwrrrrrbuwbbwburwb";

    public static void main(String[] args) {
        Util.time(() -> a(Input.parse(TEST_INPUT)));
        Util.time(() -> a(Input.parse(INPUT)));
        Util.time(() -> b(Input.parse(TEST_INPUT)));
        Util.time(() -> b(Input.parse(INPUT)));
    }
}
